use axum::Router;

use crate::handlers;
use crate::state::AppState;

/// NeboAI OAuth, account, billing, and status routes.
pub fn routes() -> Router<AppState> {
    Router::new()
        .route(
            "/neboai/oauth/start",
            axum::routing::get(handlers::neboai::oauth_start),
        )
        .route(
            "/neboai/oauth/status",
            axum::routing::get(handlers::neboai::oauth_status),
        )
        .route(
            "/neboai/account",
            axum::routing::get(handlers::neboai::account_status),
        )
        .route(
            "/neboai/account",
            axum::routing::delete(handlers::neboai::account_disconnect),
        )
        .route(
            "/neboai/status",
            axum::routing::get(handlers::neboai::bot_status),
        )
        .route(
            "/neboai/janus/usage",
            axum::routing::get(handlers::neboai::janus_usage),
        )
        .route(
            "/neboai/janus/usage/refresh",
            axum::routing::post(handlers::neboai::janus_usage_refresh),
        )
        .route(
            "/neboai/open",
            axum::routing::get(handlers::neboai::open_neboai),
        )
        .route(
            "/neboai/connect",
            axum::routing::post(handlers::neboai::connect_handler),
        )
        .route(
            "/neboai/billing/prices",
            axum::routing::get(handlers::neboai::billing_prices),
        )
        .route(
            "/neboai/billing/subscription",
            axum::routing::get(handlers::neboai::billing_subscription),
        )
        .route(
            "/neboai/billing/checkout",
            axum::routing::post(handlers::neboai::billing_checkout),
        )
        .route(
            "/neboai/billing/subscribe",
            axum::routing::post(handlers::neboai::billing_subscribe),
        )
        .route(
            "/neboai/billing/portal",
            axum::routing::post(handlers::neboai::billing_portal),
        )
        .route(
            "/neboai/billing/setup-intent",
            axum::routing::post(handlers::neboai::billing_setup_intent),
        )
        .route(
            "/neboai/billing/cancel",
            axum::routing::post(handlers::neboai::billing_cancel),
        )
        .route(
            "/neboai/billing/invoices",
            axum::routing::get(handlers::neboai::billing_invoices),
        )
        .route(
            "/neboai/billing/payment-methods",
            axum::routing::get(handlers::neboai::billing_payment_methods),
        )
        .route(
            "/neboai/referral-code",
            axum::routing::get(handlers::neboai::referral_code),
        )
        .route(
            "/neboai/marketplace/subscriptions",
            axum::routing::get(handlers::neboai::marketplace_list_subscriptions)
                .post(handlers::neboai::marketplace_create_subscription),
        )
        .route(
            "/neboai/marketplace/subscriptions/{id}/cancel",
            axum::routing::post(handlers::neboai::marketplace_cancel_subscription),
        )
        .route(
            "/neboai/reconnect",
            axum::routing::post(handlers::neboai::force_reconnect),
        )
}
