// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

export interface AgentConnectRequest {
	agentId: string
}

export interface AgentConnectResponse {
	connected: boolean
	agentId: string
}

export interface AgentInfo {
	agentId: string
	connected: boolean
	createdAt: string
}

export interface AgentSession {
	id: string
	name?: string
	summary?: string
	messageCount: number
	createdAt: string
	updatedAt: string
}

export interface AgentSettings {
	autonomousMode: boolean
	autoApproveRead: boolean
	autoApproveWrite: boolean
	autoApproveBash: boolean
}

export interface AgentStatusRequest {
}
export interface AgentStatusRequestParams {
}

export interface AgentStatusResponse {
	agentId: string
	connected: boolean
	uptime: number
}

export interface AuthConfigResponse {
	googleEnabled: boolean
	githubEnabled: boolean
}

export interface AuthProfile {
	id: string
	name: string
	provider: string // anthropic, openai, google, ollama
	model?: string
	baseUrl?: string
	priority: number
	isActive: boolean
	createdAt: string
	updatedAt: string
}

export interface CLIAvailability {
	claude: boolean
	codex: boolean
	gemini: boolean
}

export interface ChangePasswordRequest {
	currentPassword: string
	newPassword: string
}

export interface Chat {
	id: string
	title: string
	createdAt: string
	updatedAt: string
}

export interface ChatMessage {
	id: string
	chatId: string
	role: string
	content: string
	metadata?: string
	createdAt: string
}

export interface CompleteSetupResponse {
	success: boolean
}

export interface CreateAdminRequest {
	email: string
	password: string
	name: string
}

export interface CreateAdminResponse {
	token: string
	refreshToken: string
	expiresAt: number
	user: User
}

export interface CreateAuthProfileRequest {
	name: string
	provider: string
	apiKey: string
	model?: string
	baseUrl?: string
	priority?: number
}

export interface CreateAuthProfileResponse {
	profile: AuthProfile
}

export interface CreateChatRequest {
	title?: string
}

export interface CreateChatResponse {
	chat: Chat
}

export interface DayInfo {
	day: string
	messageCount: number
}

export interface DeleteAccountRequest {
	password: string
}

export interface DeleteAgentSessionRequest {
}
export interface DeleteAgentSessionRequestParams {
}

export interface DeleteAuthProfileRequest {
}
export interface DeleteAuthProfileRequestParams {
}

export interface DeleteChatRequest {
}
export interface DeleteChatRequestParams {
}

export interface DeleteNotificationRequest {
}
export interface DeleteNotificationRequestParams {
}

export interface DisconnectOAuthRequest {
}
export interface DisconnectOAuthRequestParams {
}

export interface EmailVerificationRequest {
	token: string
}

export interface Empty {
}

export interface ExtensionChannel {
	id: string
	path: string
}

export interface ExtensionSkill {
	name: string
	description: string
	version: string
	triggers: Array<string>
	tools: Array<string>
	priority: number
	enabled: boolean
	filePath: string
}

export interface ExtensionTool {
	name: string
	description: string
	schema?: string
	requiresApproval: boolean
	isPlugin: boolean
	path?: string
}

export interface ForgotPasswordRequest {
	email: string
}

export interface GetAgentSessionMessagesResponse {
	messages: Array<SessionMessage>
	total: number
}

export interface GetAgentSessionRequest {
}
export interface GetAgentSessionRequestParams {
}

export interface GetAgentSettingsResponse {
	settings: AgentSettings
}

export interface GetAuthProfileRequest {
}
export interface GetAuthProfileRequestParams {
}

export interface GetAuthProfileResponse {
	profile: AuthProfile
}

export interface GetChatRequest {
}
export interface GetChatRequestParams {
}

export interface GetChatResponse {
	chat: Chat
	messages: Array<ChatMessage>
	totalMessages: number // Total messages in chat (may be more than returned)
}

export interface GetHistoryByDayRequest {
}
export interface GetHistoryByDayRequestParams {
}

export interface GetHistoryByDayResponse {
	day: string
	messages: Array<ChatMessage>
}

export interface GetOAuthUrlRequest {
}
export interface GetOAuthUrlRequestParams {
	redirectUrl?: string
}

export interface GetOAuthUrlResponse {
	url: string
	state: string
}

export interface GetPersonalityResponse {
	content: string
}

export interface GetPreferencesResponse {
	preferences: UserPreferences
}

export interface GetSkillRequest {
}
export interface GetSkillRequestParams {
}

export interface GetSkillResponse {
	skill: ExtensionSkill
}

export interface GetUnreadCountResponse {
	count: number
}

export interface GetUserResponse {
	user: User
}

export interface HealthResponse {
	status: string
	version: string
	timestamp: string
}

export interface ListAgentSessionsResponse {
	sessions: Array<AgentSession>
	total: number
}

export interface ListAgentsRequest {
}

export interface ListAgentsResponse {
	agents: Array<AgentInfo>
	total: number
}

export interface ListAuthProfilesResponse {
	profiles: Array<AuthProfile>
}

export interface ListChatDaysRequest {
}
export interface ListChatDaysRequestParams {
	page?: number
	pageSize?: number
}

export interface ListChatDaysResponse {
	days: Array<DayInfo>
}

export interface ListChatsRequest {
}
export interface ListChatsRequestParams {
	page?: number
	pageSize?: number
}

export interface ListChatsResponse {
	chats: Array<Chat>
	total: number
}

export interface ListExtensionsResponse {
	tools: Array<ExtensionTool>
	skills: Array<ExtensionSkill>
	channels: Array<ExtensionChannel>
}

export interface ListModelsResponse {
	models: { [key: string]: Array<ModelInfo> }
	taskRouting?: TaskRouting
	availableCLIs?: CLIAvailability
}

export interface ListNotificationsRequest {
}
export interface ListNotificationsRequestParams {
	page?: number
	pageSize?: number
	unread?: boolean
}

export interface ListNotificationsResponse {
	notifications: Array<Notification>
	unreadCount: number
	totalCount: number
}

export interface ListOAuthProvidersResponse {
	providers: Array<OAuthProvider>
}

export interface LoginRequest {
	email: string
	password: string
}

export interface LoginResponse {
	token: string
	refreshToken: string
	expiresAt: number
}

export interface MarkNotificationReadRequest {
}
export interface MarkNotificationReadRequestParams {
}

export interface MessageResponse {
	message: string
}

export interface ModelInfo {
	id: string
	displayName: string
	contextWindow?: number
	pricing?: ModelPricing
	capabilities?: Array<string>
	isActive: boolean
}

export interface ModelPricing {
	input?: number
	output?: number
	cachedInput?: number
}

export interface Notification {
	id: string
	type: string
	title: string
	body?: string
	actionUrl?: string
	icon?: string
	readAt?: string
	createdAt: string
}

export interface OAuthLoginRequest {
	code: string
	state?: string
}
export interface OAuthLoginRequestParams {
}

export interface OAuthLoginResponse {
	token: string
	refreshToken: string
	expiresAt: number
	isNewUser: boolean
}

export interface OAuthProvider {
	name: string
	connected: boolean
	email?: string
}

export interface RefreshTokenRequest {
	refreshToken: string
}

export interface RefreshTokenResponse {
	token: string
	refreshToken: string
	expiresAt: number
}

export interface RegisterRequest {
	email: string
	password: string
	name: string
}

export interface ResendVerificationRequest {
	email: string
}

export interface ResetPasswordRequest {
	token: string
	newPassword: string
}

export interface SearchChatMessagesRequest {
}
export interface SearchChatMessagesRequestParams {
	query: string
	page?: number
	pageSize?: number
}

export interface SearchChatMessagesResponse {
	messages: Array<ChatMessage>
	total: number
}

export interface SendMessageRequest {
	chatId: string
	content: string
	role?: string
}

export interface SendMessageResponse {
	message: ChatMessage
	chatId: string
}

export interface SessionMessage {
	id: number
	role: string
	content?: string
	createdAt: string
}

export interface SetupStatusResponse {
	setupRequired: boolean
	hasAdmin: boolean
	setupComplete: boolean
}

export interface SimpleAgentStatusResponse {
	connected: boolean
	agentId?: string
	uptime?: number
}

export interface TaskRouting {
	vision?: string
	reasoning?: string
	code?: string
	general?: string
	fallbacks?: { [key: string]: Array<string> }
}

export interface TestAuthProfileRequest {
}
export interface TestAuthProfileRequestParams {
}

export interface TestAuthProfileResponse {
	success: boolean
	message: string
	model?: string
}

export interface ToggleModelRequest {
	active: boolean
}
export interface ToggleModelRequestParams {
}

export interface ToggleSkillRequest {
}
export interface ToggleSkillRequestParams {
}

export interface ToggleSkillResponse {
	name: string
	enabled: boolean
}

export interface UpdateAgentSettingsRequest {
	autonomousMode: boolean
	autoApproveRead: boolean
	autoApproveWrite: boolean
	autoApproveBash: boolean
}

export interface UpdateAuthProfileRequest {
	name?: string
	apiKey?: string
	model?: string
	baseUrl?: string
	priority?: number
	isActive?: boolean
}
export interface UpdateAuthProfileRequestParams {
}

export interface UpdateChatRequest {
	title: string
}
export interface UpdateChatRequestParams {
}

export interface UpdatePersonalityRequest {
	content: string
}

export interface UpdatePersonalityResponse {
	success: boolean
}

export interface UpdatePreferencesRequest {
	emailNotifications?: boolean
	marketingEmails?: boolean
	timezone?: string
	language?: string
	theme?: string
}

export interface UpdateTaskRoutingRequest {
	vision?: string
	reasoning?: string
	code?: string
	general?: string
	fallbacks?: { [key: string]: Array<string> }
}

export interface UpdateUserRequest {
	name?: string
	avatarUrl?: string
}

export interface User {
	id: string
	email: string
	name: string
	avatarUrl?: string
	emailVerified: boolean
	createdAt: string
	updatedAt: string
}

export interface UserPreferences {
	emailNotifications: boolean
	marketingEmails: boolean
	timezone: string
	language: string
	theme: string
}

