// Code generated by scripts/genapi. DO NOT EDIT.
// To regenerate: make gen

import webapi from "./gocliRequest"
import * as components from "./neboComponents"
export * from "./neboComponents"

/**
 * @description "List advisors"
 */
export function listAdvisors() {
	return webapi.get<components.ListAdvisorsResponse>(`/api/v1/agent/advisors`)
}

/**
 * @description "Create advisor"
 */
export function createAdvisor(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/agent/advisors`, req)
}

/**
 * @description "Get advisor"
 */
export function getAdvisor(name: string) {
	return webapi.get<unknown>(`/api/v1/agent/advisors/${name}`)
}

/**
 * @description "Update advisor"
 */
export function updateAdvisor(name: string, req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/agent/advisors/${name}`, req)
}

/**
 * @description "Delete advisor"
 */
export function deleteAdvisor(name: string) {
	return webapi.delete<components.DeleteAdvisorResponse>(`/api/v1/agent/advisors/${name}`)
}

/**
 * @description "Get channel messages"
 */
export function getChannelMessages(channelId: string) {
	return webapi.get<components.GetChannelMessagesResponse>(`/api/v1/agent/channels/${channelId}/messages`)
}

/**
 * @description "Send channel message"
 */
export function sendChannelMessage(channelId: string, req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/agent/channels/${channelId}/send`, req)
}

/**
 * @description "Get heartbeat"
 */
export function getHeartbeat() {
	return webapi.get<components.GetHeartbeatResponse>(`/api/v1/agent/heartbeat`)
}

/**
 * @description "Update heartbeat"
 */
export function updateHeartbeat(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateHeartbeatResponse>(`/api/v1/agent/heartbeat`, req)
}

/**
 * @description "Get lanes"
 */
export function getLanes() {
	return webapi.get<components.GetLanesResponse>(`/api/v1/agent/lanes`)
}

/**
 * @description "List personality presets"
 */
export function listPersonalityPresets() {
	return webapi.get<components.ListPersonalityPresetsResponse>(`/api/v1/agent/personality-presets`)
}

/**
 * @description "Get profile"
 */
export function getProfile() {
	return webapi.get<unknown>(`/api/v1/agent/profile`)
}

/**
 * @description "Update profile"
 */
export function updateProfile(req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/agent/profile`, req)
}

/**
 * @description "List sessions"
 */
export function listSessions() {
	return webapi.get<components.ListSessionsResponse>(`/api/v1/agent/sessions`)
}

/**
 * @description "Delete session"
 */
export function deleteSession(id: string) {
	return webapi.delete<components.DeleteSessionResponse>(`/api/v1/agent/sessions/${id}`)
}

/**
 * @description "Get session messages"
 */
export function getSessionMessages(id: string) {
	return webapi.get<components.GetSessionMessagesResponse>(`/api/v1/agent/sessions/${id}/messages`)
}

/**
 * @description "Get settings"
 */
export function getSettings() {
	return webapi.get<components.GetSettingsResponse>(`/api/v1/agent/settings`)
}

/**
 * @description "Update settings"
 */
export function updateSettings(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateSettingsResponse>(`/api/v1/agent/settings`, req)
}

/**
 * @description "Get status"
 */
export function getStatus() {
	return webapi.get<components.GetStatusResponse>(`/api/v1/agent/status`)
}

/**
 * @description "Get system info"
 */
export function getSystemInfo() {
	return webapi.get<components.GetSystemInfoResponse>(`/api/v1/agent/system-info`)
}

/**
 * @description "Agent ws handler"
 */
export function agentWsHandler() {
	return webapi.get<unknown>(`/api/v1/agent/ws`)
}

/**
 * @description "List agents"
 */
export function listAgents() {
	return webapi.get<components.ListAgentsResponse>(`/api/v1/agents`)
}

/**
 * @description "Create agent"
 */
export function createAgent(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateAgentResponse>(`/api/v1/agents`, req)
}

/**
 * @description "List active agents"
 */
export function listActiveAgents() {
	return webapi.get<components.ListActiveAgentsResponse>(`/api/v1/agents/active`)
}

/**
 * @description "List event sources"
 */
export function listEventSources() {
	return webapi.get<components.ListEventSourcesResponse>(`/api/v1/agents/event-sources`)
}

/**
 * @description "Get agent"
 */
export function getAgent(id: string) {
	return webapi.get<components.GetAgentResponse>(`/api/v1/agents/${id}`)
}

/**
 * @description "Update agent"
 */
export function updateAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateAgentResponse>(`/api/v1/agents/${id}`, req)
}

/**
 * @description "Delete agent"
 */
export function deleteAgent(id: string) {
	return webapi.delete<components.DeleteAgentResponse>(`/api/v1/agents/${id}`)
}

/**
 * @description "Activate agent"
 */
export function activateAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ActivateAgentResponse>(`/api/v1/agents/${id}/activate`, req)
}

/**
 * @description "Apply agent update"
 */
export function applyAgentUpdate(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ApplyAgentUpdateResponse>(`/api/v1/agents/${id}/apply-update`, req)
}

/**
 * @description "Chat with agent"
 */
export function chatWithAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ChatWithAgentResponse>(`/api/v1/agents/${id}/chat`, req)
}

/**
 * @description "List agent chats"
 */
export function listAgentChats(id: string) {
	return webapi.get<components.ListAgentChatsResponse>(`/api/v1/agents/${id}/chats`)
}

/**
 * @description "Create new agent chat"
 */
export function createNewAgentChat(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateNewAgentChatResponse>(`/api/v1/agents/${id}/chats`, req)
}

/**
 * @description "Activate agent chat"
 */
export function activateAgentChat(id: string, chatId: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ActivateAgentChatResponse>(`/api/v1/agents/${id}/chats/${chatId}/activate`, req)
}

/**
 * @description "Check agent update"
 */
export function checkAgentUpdate(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.CheckAgentUpdateResponse>(`/api/v1/agents/${id}/check-update`, req)
}

/**
 * @description "Deactivate agent"
 */
export function deactivateAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.DeactivateAgentResponse>(`/api/v1/agents/${id}/deactivate`, req)
}

/**
 * @description "Duplicate agent"
 */
export function duplicateAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.DuplicateAgentResponse>(`/api/v1/agents/${id}/duplicate`, req)
}

/**
 * @description "Update agent inputs"
 */
export function updateAgentInputs(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateAgentInputsResponse>(`/api/v1/agents/${id}/inputs`, req)
}

/**
 * @description "Install deps"
 */
export function installDeps(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.InstallDepsResponse>(`/api/v1/agents/${id}/install-deps`, req)
}

/**
 * @description "Get agent nav"
 */
export function getAgentNav(id: string) {
	return webapi.get<components.GetAgentNavResponse>(`/api/v1/agents/${id}/nav`)
}

/**
 * @description "Reload agent"
 */
export function reloadAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ReloadAgentResponse>(`/api/v1/agents/${id}/reload`, req)
}

/**
 * @description "List agent runs"
 */
export function listAgentRuns(id: string) {
	return webapi.get<components.ListAgentRunsResponse>(`/api/v1/agents/${id}/runs`)
}

/**
 * @description "Trigger agent setup"
 */
export function triggerAgentSetup(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.TriggerAgentSetupResponse>(`/api/v1/agents/${id}/setup`, req)
}

/**
 * @description "Agent stats"
 */
export function agentStats(id: string) {
	return webapi.get<components.AgentStatsResponse>(`/api/v1/agents/${id}/stats`)
}

/**
 * @description "Get agent surfaces"
 */
export function getAgentSurfaces(id: string) {
	return webapi.get<components.GetAgentSurfacesResponse>(`/api/v1/agents/${id}/surfaces`)
}

/**
 * @description "Get agent theme"
 */
export function getAgentTheme(id: string) {
	return webapi.get<unknown>(`/api/v1/agents/${id}/theme.css`)
}

/**
 * @description "Toggle agent"
 */
export function toggleAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ToggleAgentResponse>(`/api/v1/agents/${id}/toggle`, req)
}

/**
 * @description "List agent workflows"
 */
export function listAgentWorkflows(id: string) {
	return webapi.get<components.ListAgentWorkflowsResponse>(`/api/v1/agents/${id}/workflows`)
}

/**
 * @description "Create agent workflow"
 */
export function createAgentWorkflow(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateAgentWorkflowResponse>(`/api/v1/agents/${id}/workflows`, req)
}

/**
 * @description "Update agent workflow"
 */
export function updateAgentWorkflow(id: string, bindingName: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateAgentWorkflowResponse>(`/api/v1/agents/${id}/workflows/${bindingName}`, req)
}

/**
 * @description "Delete agent workflow"
 */
export function deleteAgentWorkflow(id: string, bindingName: string) {
	return webapi.delete<components.DeleteAgentWorkflowResponse>(`/api/v1/agents/${id}/workflows/${bindingName}`)
}

/**
 * @description "Toggle agent workflow"
 */
export function toggleAgentWorkflow(id: string, bindingName: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ToggleAgentWorkflowResponse>(`/api/v1/agents/${id}/workflows/${bindingName}/toggle`, req)
}

/**
 * @description "Config"
 */
export function config() {
	return webapi.get<components.ConfigResponse>(`/api/v1/auth/config`)
}

/**
 * @description "Forgot password"
 */
export function forgotPassword(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/forgot`, req)
}

/**
 * @description "Login"
 */
export function login(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/login`, req)
}

/**
 * @description "Refresh"
 */
export function refresh(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/refresh`, req)
}

/**
 * @description "Register"
 */
export function register(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/register`, req)
}

/**
 * @description "Resend verification"
 */
export function resendVerification(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/resend`, req)
}

/**
 * @description "Reset password"
 */
export function resetPassword(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/reset`, req)
}

/**
 * @description "Verify email"
 */
export function verifyEmail(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/verify`, req)
}

/**
 * @description "List chats"
 */
export function listChats() {
	return webapi.get<components.ListChatsResponse>(`/api/v1/chats`)
}

/**
 * @description "Create chat"
 */
export function createChat(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/chats`, req)
}

/**
 * @description "Get companion chat"
 */
export function getCompanionChat() {
	return webapi.get<components.GetCompanionChatResponse>(`/api/v1/chats/companion`)
}

/**
 * @description "Create companion chat"
 */
export function createCompanionChat(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateCompanionChatResponse>(`/api/v1/chats/companion/new`, req)
}

/**
 * @description "List chat days"
 */
export function listChatDays() {
	return webapi.get<components.ListChatDaysResponse>(`/api/v1/chats/days`)
}

/**
 * @description "Get chat history by day"
 */
export function getChatHistoryByDay(day: string) {
	return webapi.get<components.GetChatHistoryByDayResponse>(`/api/v1/chats/history/${day}`)
}

/**
 * @description "Send message"
 */
export function sendMessage(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/chats/message`, req)
}

/**
 * @description "Edit message"
 */
export function editMessage(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.EditMessageResponse>(`/api/v1/chats/messages/${id}/edit`, req)
}

/**
 * @description "Search messages"
 */
export function searchMessages() {
	return webapi.get<components.SearchMessagesResponse>(`/api/v1/chats/search`)
}

/**
 * @description "Get tool output"
 */
export function getToolOutput(chatId: string, toolCallId: string) {
	return webapi.get<components.GetToolOutputResponse>(`/api/v1/chats/${chatId}/tool-output/${toolCallId}`)
}

/**
 * @description "Get chat"
 */
export function getChat(id: string) {
	return webapi.get<unknown>(`/api/v1/chats/${id}`)
}

/**
 * @description "Update chat"
 */
export function updateChat(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateChatResponse>(`/api/v1/chats/${id}`, req)
}

/**
 * @description "Delete chat"
 */
export function deleteChat(id: string) {
	return webapi.delete<components.DeleteChatResponse>(`/api/v1/chats/${id}`)
}

/**
 * @description "Get chat messages"
 */
export function getChatMessages(id: string) {
	return webapi.get<components.GetChatMessagesResponse>(`/api/v1/chats/${id}/messages`)
}

/**
 * @description "Submit code"
 */
export function submitCode(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/codes`, req)
}

/**
 * @description "Create edge"
 */
export function createEdge(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateEdgeResponse>(`/api/v1/commander/edges`, req)
}

/**
 * @description "Delete edge"
 */
export function deleteEdge(id: string) {
	return webapi.delete<components.DeleteEdgeResponse>(`/api/v1/commander/edges/${id}`)
}

/**
 * @description "Get graph"
 */
export function getGraph() {
	return webapi.get<components.GetGraphResponse>(`/api/v1/commander/graph`)
}

/**
 * @description "Save layout"
 */
export function saveLayout(req: Record<string, unknown> = {}) {
	return webapi.put<components.SaveLayoutResponse>(`/api/v1/commander/layout`, req)
}

/**
 * @description "Create team"
 */
export function createTeam(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateTeamResponse>(`/api/v1/commander/teams`, req)
}

/**
 * @description "Update team"
 */
export function updateTeam(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateTeamResponse>(`/api/v1/commander/teams/${id}`, req)
}

/**
 * @description "Delete team"
 */
export function deleteTeam(id: string) {
	return webapi.delete<components.DeleteTeamResponse>(`/api/v1/commander/teams/${id}`)
}

/**
 * @description "Approve deps"
 */
export function approveDeps(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/deps/approve`, req)
}

/**
 * @description "Get entity config"
 */
export function getEntityConfig(entityType: string, entityId: string) {
	return webapi.get<components.GetEntityConfigResponse>(`/api/v1/entity-config/${entityType}/${entityId}`)
}

/**
 * @description "Update entity config"
 */
export function updateEntityConfig(entityType: string, entityId: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateEntityConfigResponse>(`/api/v1/entity-config/${entityType}/${entityId}`, req)
}

/**
 * @description "Delete entity config"
 */
export function deleteEntityConfig(entityType: string, entityId: string) {
	return webapi.delete<components.DeleteEntityConfigResponse>(`/api/v1/entity-config/${entityType}/${entityId}`)
}

/**
 * @description "List extensions"
 */
export function listExtensions() {
	return webapi.get<components.ListExtensionsResponse>(`/api/v1/extensions`)
}

/**
 * @description "Browse"
 */
export function browse(req: Record<string, unknown> = {}) {
	return webapi.post<components.BrowseResponse>(`/api/v1/files/browse`, req)
}

/**
 * @description "Pick files"
 */
export function pickFiles(req: Record<string, unknown> = {}) {
	return webapi.post<components.PickFilesResponse>(`/api/v1/files/pick`, req)
}

/**
 * @description "Pick folder"
 */
export function pickFolder(req: Record<string, unknown> = {}) {
	return webapi.post<components.PickFolderResponse>(`/api/v1/files/pick-folder`, req)
}

/**
 * @description "Serve file"
 */
export function serveFile(path: string) {
	return webapi.get<unknown>(`/api/v1/files/${path}`)
}

/**
 * @description "List integrations"
 */
export function listIntegrations() {
	return webapi.get<components.ListIntegrationsResponse>(`/api/v1/integrations`)
}

/**
 * @description "Create integration"
 */
export function createIntegration(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateIntegrationResponse>(`/api/v1/integrations`, req)
}

/**
 * @description "Oauth callback"
 */
export function oauthCallback() {
	return webapi.get<unknown>(`/api/v1/integrations/oauth/callback`)
}

/**
 * @description "List registry"
 */
export function listRegistry() {
	return webapi.get<components.ListRegistryResponse>(`/api/v1/integrations/registry`)
}

/**
 * @description "List tools"
 */
export function listTools() {
	return webapi.get<components.ListToolsResponse>(`/api/v1/integrations/tools`)
}

/**
 * @description "Get integration"
 */
export function getIntegration(id: string) {
	return webapi.get<unknown>(`/api/v1/integrations/${id}`)
}

/**
 * @description "Update integration"
 */
export function updateIntegration(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/integrations/${id}`, req)
}

/**
 * @description "Delete integration"
 */
export function deleteIntegration(id: string) {
	return webapi.delete<components.DeleteIntegrationResponse>(`/api/v1/integrations/${id}`)
}

/**
 * @description "Connect integration"
 */
export function connectIntegration(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ConnectIntegrationResponse>(`/api/v1/integrations/${id}/connect`, req)
}

/**
 * @description "Get oauth url"
 */
export function getOauthUrl(id: string) {
	return webapi.get<components.GetOauthUrlResponse>(`/api/v1/integrations/${id}/oauth-url`)
}

/**
 * @description "Reauthenticate integration"
 */
export function reauthenticateIntegration(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ReauthenticateIntegrationResponse>(`/api/v1/integrations/${id}/reauthenticate`, req)
}

/**
 * @description "Test integration"
 */
export function testIntegration(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.TestIntegrationResponse>(`/api/v1/integrations/${id}/test`, req)
}

/**
 * @description "Local models status"
 */
export function localModelsStatus() {
	return webapi.get<components.LocalModelsStatusResponse>(`/api/v1/local-models/status`)
}

/**
 * @description "List memories"
 */
export function listMemories() {
	return webapi.get<components.ListMemoriesResponse>(`/api/v1/memories`)
}

/**
 * @description "Search memories"
 */
export function searchMemories() {
	return webapi.get<components.SearchMemoriesResponse>(`/api/v1/memories/search`)
}

/**
 * @description "Get stats"
 */
export function getStats() {
	return webapi.get<components.GetStatsResponse>(`/api/v1/memories/stats`)
}

/**
 * @description "Get memory"
 */
export function getMemory(id: string) {
	return webapi.get<components.GetMemoryResponse>(`/api/v1/memories/${id}`)
}

/**
 * @description "Update memory"
 */
export function updateMemory(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateMemoryResponse>(`/api/v1/memories/${id}`, req)
}

/**
 * @description "Delete memory"
 */
export function deleteMemory(id: string) {
	return webapi.delete<components.DeleteMemoryResponse>(`/api/v1/memories/${id}`)
}

/**
 * @description "List models"
 */
export function listModels() {
	return webapi.get<components.ListModelsResponse>(`/api/v1/models`)
}

/**
 * @description "Update cli provider"
 */
export function updateCliProvider(cliId: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateCliProviderResponse>(`/api/v1/models/cli/${cliId}`, req)
}

/**
 * @description "Update model config"
 */
export function updateModelConfig(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateModelConfigResponse>(`/api/v1/models/config`, req)
}

/**
 * @description "Update task routing"
 */
export function updateTaskRouting(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateTaskRoutingResponse>(`/api/v1/models/task-routing`, req)
}

/**
 * @description "Update model"
 */
export function updateModel(provider: string, modelId: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateModelResponse>(`/api/v1/models/${provider}/${modelId}`, req)
}

/**
 * @description "Account status"
 */
export function accountStatus() {
	return webapi.get<unknown>(`/api/v1/neboloop/account`)
}

/**
 * @description "Account disconnect"
 */
export function accountDisconnect() {
	return webapi.delete<unknown>(`/api/v1/neboloop/account`)
}

/**
 * @description "Billing cancel"
 */
export function billingCancel(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboloop/billing/cancel`, req)
}

/**
 * @description "Billing checkout"
 */
export function billingCheckout(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboloop/billing/checkout`, req)
}

/**
 * @description "Billing invoices"
 */
export function billingInvoices() {
	return webapi.get<unknown>(`/api/v1/neboloop/billing/invoices`)
}

/**
 * @description "Billing payment methods"
 */
export function billingPaymentMethods() {
	return webapi.get<unknown>(`/api/v1/neboloop/billing/payment-methods`)
}

/**
 * @description "Billing portal"
 */
export function billingPortal(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboloop/billing/portal`, req)
}

/**
 * @description "Billing prices"
 */
export function billingPrices() {
	return webapi.get<unknown>(`/api/v1/neboloop/billing/prices`)
}

/**
 * @description "Billing setup intent"
 */
export function billingSetupIntent(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboloop/billing/setup-intent`, req)
}

/**
 * @description "Billing subscribe"
 */
export function billingSubscribe(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboloop/billing/subscribe`, req)
}

/**
 * @description "Billing subscription"
 */
export function billingSubscription() {
	return webapi.get<unknown>(`/api/v1/neboloop/billing/subscription`)
}

/**
 * @description "Connect handler"
 */
export function connectHandler(req: Record<string, unknown> = {}) {
	return webapi.post<components.ConnectHandlerResponse>(`/api/v1/neboloop/connect`, req)
}

/**
 * @description "Janus usage"
 */
export function janusUsage() {
	return webapi.get<components.JanusUsageResponse>(`/api/v1/neboloop/janus/usage`)
}

/**
 * @description "Janus usage refresh"
 */
export function janusUsageRefresh(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboloop/janus/usage/refresh`, req)
}

/**
 * @description "Oauth start"
 */
export function oauthStart(params?: { janus?: boolean }) {
	return webapi.get<unknown>(`/api/v1/neboloop/oauth/start`, params)
}

/**
 * @description "Oauth status"
 */
export function oauthStatus(params: { state: string }) {
	return webapi.get<unknown>(`/api/v1/neboloop/oauth/status`, params)
}

/**
 * @description "Open neboloop"
 */
export function openNeboloop() {
	return webapi.get<components.OpenNeboloopResponse>(`/api/v1/neboloop/open`)
}

/**
 * @description "Force reconnect"
 */
export function forceReconnect(req: Record<string, unknown> = {}) {
	return webapi.post<components.ForceReconnectResponse>(`/api/v1/neboloop/reconnect`, req)
}

/**
 * @description "Referral code"
 */
export function referralCode() {
	return webapi.get<unknown>(`/api/v1/neboloop/referral-code`)
}

/**
 * @description "Bot status"
 */
export function botStatus() {
	return webapi.get<components.BotStatusResponse>(`/api/v1/neboloop/status`)
}

/**
 * @description "List notifications"
 */
export function listNotifications() {
	return webapi.get<components.ListNotificationsResponse>(`/api/v1/notifications`)
}

/**
 * @description "Mark all read"
 */
export function markAllRead(req: Record<string, unknown> = {}) {
	return webapi.put<components.MarkAllReadResponse>(`/api/v1/notifications/read-all`, req)
}

/**
 * @description "Unread count"
 */
export function unreadCount() {
	return webapi.get<components.UnreadCountResponse>(`/api/v1/notifications/unread-count`)
}

/**
 * @description "Delete notification"
 */
export function deleteNotification(id: string) {
	return webapi.delete<components.DeleteNotificationResponse>(`/api/v1/notifications/${id}`)
}

/**
 * @description "Mark read"
 */
export function markRead(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.MarkReadResponse>(`/api/v1/notifications/${id}/read`, req)
}

/**
 * @description "List plugins"
 */
export function listPlugins() {
	return webapi.get<components.ListPluginsResponse>(`/api/v1/plugins`)
}

/**
 * @description "List all plugin events"
 */
export function listAllPluginEvents() {
	return webapi.get<components.ListAllPluginEventsResponse>(`/api/v1/plugins/events`)
}

/**
 * @description "Remove plugin"
 */
export function removePlugin(slug: string) {
	return webapi.delete<components.RemovePluginResponse>(`/api/v1/plugins/${slug}`)
}

/**
 * @description "Auth login"
 */
export function authLogin(slug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.AuthLoginResponse>(`/api/v1/plugins/${slug}/auth/login`, req)
}

/**
 * @description "Auth logout"
 */
export function authLogout(slug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.AuthLogoutResponse>(`/api/v1/plugins/${slug}/auth/logout`, req)
}

/**
 * @description "Auth status"
 */
export function authStatus(slug: string) {
	return webapi.get<components.AuthStatusResponse>(`/api/v1/plugins/${slug}/auth/status`)
}

/**
 * @description "List plugin events"
 */
export function listPluginEvents(slug: string) {
	return webapi.get<components.ListPluginEventsResponse>(`/api/v1/plugins/${slug}/events`)
}

/**
 * @description "List providers"
 */
export function listProviders() {
	return webapi.get<components.ListProvidersResponse>(`/api/v1/providers`)
}

/**
 * @description "Create provider"
 */
export function createProvider(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/providers`, req)
}

/**
 * @description "Get provider"
 */
export function getProvider(id: string) {
	return webapi.get<unknown>(`/api/v1/providers/${id}`)
}

/**
 * @description "Update provider"
 */
export function updateProvider(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/providers/${id}`, req)
}

/**
 * @description "Delete provider"
 */
export function deleteProvider(id: string) {
	return webapi.delete<components.DeleteProviderResponse>(`/api/v1/providers/${id}`)
}

/**
 * @description "Test provider"
 */
export function testProvider(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.TestProviderResponse>(`/api/v1/providers/${id}/test`, req)
}

/**
 * @description "Active runs handler"
 */
export function activeRunsHandler() {
	return webapi.get<unknown>(`/api/v1/runs/active`)
}

/**
 * @description "Create admin"
 */
export function createAdmin(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateAdminResponse>(`/api/v1/setup/admin`, req)
}

/**
 * @description "Complete"
 */
export function complete(req: Record<string, unknown> = {}) {
	return webapi.post<components.CompleteResponse>(`/api/v1/setup/complete`, req)
}

/**
 * @description "Get personality"
 */
export function getPersonality() {
	return webapi.get<unknown>(`/api/v1/setup/personality`)
}

/**
 * @description "Update personality"
 */
export function updatePersonality(req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/setup/personality`, req)
}

/**
 * @description "Status"
 */
export function status() {
	return webapi.get<components.StatusResponse>(`/api/v1/setup/status`)
}

/**
 * @description "Create skill"
 */
export function createSkill(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateSkillResponse>(`/api/v1/skills`, req)
}

/**
 * @description "Get skill"
 */
export function getSkill(name: string) {
	return webapi.get<components.GetSkillResponse>(`/api/v1/skills/${name}`)
}

/**
 * @description "Update skill"
 */
export function updateSkill(name: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateSkillResponse>(`/api/v1/skills/${name}`, req)
}

/**
 * @description "Delete skill"
 */
export function deleteSkill(name: string) {
	return webapi.delete<components.DeleteSkillResponse>(`/api/v1/skills/${name}`)
}

/**
 * @description "Get skill content"
 */
export function getSkillContent(name: string) {
	return webapi.get<unknown>(`/api/v1/skills/${name}/content`)
}

/**
 * @description "List skill secrets"
 */
export function listSkillSecrets(name: string) {
	return webapi.get<components.ListSkillSecretsResponse>(`/api/v1/skills/${name}/secrets`)
}

/**
 * @description "Set skill secret"
 */
export function setSkillSecret(name: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.SetSkillSecretResponse>(`/api/v1/skills/${name}/secrets`, req)
}

/**
 * @description "Delete skill secret"
 */
export function deleteSkillSecret(name: string, key: string) {
	return webapi.delete<components.DeleteSkillSecretResponse>(`/api/v1/skills/${name}/secrets/${key}`)
}

/**
 * @description "Toggle skill"
 */
export function toggleSkill(name: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ToggleSkillResponse>(`/api/v1/skills/${name}/toggle`, req)
}

/**
 * @description "List store categories"
 */
export function listStoreCategories() {
	return webapi.get<unknown>(`/api/v1/store/categories`)
}

/**
 * @description "List store collections"
 */
export function listStoreCollections() {
	return webapi.get<components.ListStoreCollectionsResponse>(`/api/v1/store/collections`)
}

/**
 * @description "Create store collection"
 */
export function createStoreCollection(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateStoreCollectionResponse>(`/api/v1/store/collections`, req)
}

/**
 * @description "Get store collection"
 */
export function getStoreCollection(id: string) {
	return webapi.get<components.GetStoreCollectionResponse>(`/api/v1/store/collections/${id}`)
}

/**
 * @description "Update store collection"
 */
export function updateStoreCollection(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateStoreCollectionResponse>(`/api/v1/store/collections/${id}`, req)
}

/**
 * @description "Delete store collection"
 */
export function deleteStoreCollection(id: string) {
	return webapi.delete<components.DeleteStoreCollectionResponse>(`/api/v1/store/collections/${id}`)
}

/**
 * @description "Add collection item"
 */
export function addCollectionItem(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.AddCollectionItemResponse>(`/api/v1/store/collections/${id}/items`, req)
}

/**
 * @description "Remove collection item"
 */
export function removeCollectionItem(id: string, itemId: string) {
	return webapi.delete<components.RemoveCollectionItemResponse>(`/api/v1/store/collections/${id}/items/${itemId}`)
}

/**
 * @description "List store featured"
 */
export function listStoreFeatured() {
	return webapi.get<unknown>(`/api/v1/store/featured`)
}

/**
 * @description "List store orgs"
 */
export function listStoreOrgs() {
	return webapi.get<components.ListStoreOrgsResponse>(`/api/v1/store/orgs`)
}

/**
 * @description "List store products"
 */
export function listStoreProducts() {
	return webapi.get<unknown>(`/api/v1/store/products`)
}

/**
 * @description "List store products top"
 */
export function listStoreProductsTop() {
	return webapi.get<unknown>(`/api/v1/store/products/top`)
}

/**
 * @description "Get store product"
 */
export function getStoreProduct(id: string) {
	return webapi.get<unknown>(`/api/v1/store/products/${id}`)
}

/**
 * @description "Get store product feedback"
 */
export function getStoreProductFeedback(id: string) {
	return webapi.get<components.GetStoreProductFeedbackResponse>(`/api/v1/store/products/${id}/feedback`)
}

/**
 * @description "Submit store product feedback"
 */
export function submitStoreProductFeedback(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/store/products/${id}/feedback`, req)
}

/**
 * @description "Install store product"
 */
export function installStoreProduct(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.InstallStoreProductResponse>(`/api/v1/store/products/${id}/install`, req)
}

/**
 * @description "Uninstall store product"
 */
export function uninstallStoreProduct(id: string) {
	return webapi.delete<components.UninstallStoreProductResponse>(`/api/v1/store/products/${id}/install`)
}

/**
 * @description "Get store product media"
 */
export function getStoreProductMedia(id: string) {
	return webapi.get<components.GetStoreProductMediaResponse>(`/api/v1/store/products/${id}/media`)
}

/**
 * @description "Get store product reviews"
 */
export function getStoreProductReviews(id: string) {
	return webapi.get<unknown>(`/api/v1/store/products/${id}/reviews`)
}

/**
 * @description "Submit store product review"
 */
export function submitStoreProductReview(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/store/products/${id}/reviews`, req)
}

/**
 * @description "Get store product similar"
 */
export function getStoreProductSimilar(id: string) {
	return webapi.get<unknown>(`/api/v1/store/products/${id}/similar`)
}

/**
 * @description "Get store screenshots"
 */
export function getStoreScreenshots(type: string) {
	return webapi.get<unknown>(`/api/v1/store/screenshots/${type}`)
}

/**
 * @description "List tasks"
 */
export function listTasks() {
	return webapi.get<components.ListTasksResponse>(`/api/v1/tasks`)
}

/**
 * @description "Create task"
 */
export function createTask(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/tasks`, req)
}

/**
 * @description "Get task"
 */
export function getTask(name: string) {
	return webapi.get<unknown>(`/api/v1/tasks/${name}`)
}

/**
 * @description "Update task"
 */
export function updateTask(name: string, req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/tasks/${name}`, req)
}

/**
 * @description "Delete task"
 */
export function deleteTask(name: string) {
	return webapi.delete<components.DeleteTaskResponse>(`/api/v1/tasks/${name}`)
}

/**
 * @description "List task history"
 */
export function listTaskHistory(name: string) {
	return webapi.get<components.ListTaskHistoryResponse>(`/api/v1/tasks/${name}/history`)
}

/**
 * @description "Run task"
 */
export function runTask(name: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.RunTaskResponse>(`/api/v1/tasks/${name}/run`, req)
}

/**
 * @description "Toggle task"
 */
export function toggleTask(name: string, req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/tasks/${name}/toggle`, req)
}

/**
 * @description "Update apply"
 */
export function updateApply(req: Record<string, unknown> = {}) {
	return webapi.post<components.UpdateApplyResponse>(`/api/v1/update/apply`, req)
}

/**
 * @description "Update check"
 */
export function updateCheck() {
	return webapi.get<unknown>(`/api/v1/update/check`)
}

/**
 * @description "Get current user"
 */
export function getCurrentUser() {
	return webapi.get<components.GetCurrentUserResponse>(`/api/v1/user/me`)
}

/**
 * @description "Update current user"
 */
export function updateCurrentUser(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateCurrentUserResponse>(`/api/v1/user/me`, req)
}

/**
 * @description "Delete account"
 */
export function deleteAccount() {
	return webapi.delete<components.DeleteAccountResponse>(`/api/v1/user/me`)
}

/**
 * @description "Accept terms"
 */
export function acceptTerms(req: Record<string, unknown> = {}) {
	return webapi.post<components.AcceptTermsResponse>(`/api/v1/user/me/accept-terms`, req)
}

/**
 * @description "Change password"
 */
export function changePassword(req: Record<string, unknown> = {}) {
	return webapi.post<components.ChangePasswordResponse>(`/api/v1/user/me/change-password`, req)
}

/**
 * @description "Get permissions"
 */
export function getPermissions() {
	return webapi.get<components.GetPermissionsResponse>(`/api/v1/user/me/permissions`)
}

/**
 * @description "Update permissions"
 */
export function updatePermissions(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdatePermissionsResponse>(`/api/v1/user/me/permissions`, req)
}

/**
 * @description "Get preferences"
 */
export function getPreferences() {
	return webapi.get<components.GetPreferencesResponse>(`/api/v1/user/me/preferences`)
}

/**
 * @description "Update preferences"
 */
export function updatePreferences(req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/user/me/preferences`, req)
}

/**
 * @description "List workflows"
 */
export function listWorkflows() {
	return webapi.get<components.ListWorkflowsResponse>(`/api/v1/workflows`)
}

/**
 * @description "Create workflow"
 */
export function createWorkflow(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateWorkflowResponse>(`/api/v1/workflows`, req)
}

/**
 * @description "Get workflow"
 */
export function getWorkflow(id: string) {
	return webapi.get<components.GetWorkflowResponse>(`/api/v1/workflows/${id}`)
}

/**
 * @description "Update workflow"
 */
export function updateWorkflow(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateWorkflowResponse>(`/api/v1/workflows/${id}`, req)
}

/**
 * @description "Delete workflow"
 */
export function deleteWorkflow(id: string) {
	return webapi.delete<components.DeleteWorkflowResponse>(`/api/v1/workflows/${id}`)
}

/**
 * @description "List bindings"
 */
export function listBindings(id: string) {
	return webapi.get<components.ListBindingsResponse>(`/api/v1/workflows/${id}/bindings`)
}

/**
 * @description "Update bindings"
 */
export function updateBindings(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateBindingsResponse>(`/api/v1/workflows/${id}/bindings`, req)
}

/**
 * @description "Run workflow"
 */
export function runWorkflow(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.RunWorkflowResponse>(`/api/v1/workflows/${id}/run`, req)
}

/**
 * @description "List runs"
 */
export function listRuns(id: string) {
	return webapi.get<components.ListRunsResponse>(`/api/v1/workflows/${id}/runs`)
}

/**
 * @description "Get run"
 */
export function getRun(id: string, runId: string) {
	return webapi.get<components.GetRunResponse>(`/api/v1/workflows/${id}/runs/${runId}`)
}

/**
 * @description "Cancel run"
 */
export function cancelRun(id: string, runId: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.CancelRunResponse>(`/api/v1/workflows/${id}/runs/${runId}/cancel`, req)
}

/**
 * @description "Toggle workflow"
 */
export function toggleWorkflow(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ToggleWorkflowResponse>(`/api/v1/workflows/${id}/toggle`, req)
}

