// Code generated by scripts/genapi.ts. DO NOT EDIT.
// To regenerate: pnpm run gen:api

import webapi from "./gocliRequest"
import * as components from "./neboComponents"
export * from "./neboComponents"

/**
 * @description "List advisors"
 */
export function listAdvisors() {
	return webapi.get<components.ListAdvisorsResponse>(`/api/v1/agent/advisors`)
}

/**
 * @description "Create advisor"
 */
export function createAdvisor(req: components.CreateAdvisorRequest) {
	return webapi.post<components.GetAdvisorResponse>(`/api/v1/agent/advisors`, req)
}

/**
 * @description "Get advisor"
 */
export function getAdvisor(name: string) {
	return webapi.get<components.GetAdvisorResponse>(`/api/v1/agent/advisors/${name}`)
}

/**
 * @description "Update advisor"
 */
export function updateAdvisor(req: components.UpdateAdvisorRequest, name: string) {
	return webapi.put<components.GetAdvisorResponse>(`/api/v1/agent/advisors/${name}`, req)
}

/**
 * @description "Delete advisor"
 */
export function deleteAdvisor(name: string) {
	return webapi.delete<components.DeleteAdvisorResponse>(`/api/v1/agent/advisors/${name}`)
}

/**
 * @description "Get channel messages"
 */
export function getChannelMessages(params: components.GetChannelMessagesRequestParams, channelId: string) {
	return webapi.get<components.GetChannelMessagesResponse>(`/api/v1/agent/channels/${channelId}/messages`, params)
}

/**
 * @description "Send channel message"
 */
export function sendChannelMessage(req: components.SendChannelMessageRequest, channelId: string) {
	return webapi.post<components.MessageResponse>(`/api/v1/agent/channels/${channelId}/send`, req)
}

/**
 * @description "Get heartbeat"
 */
export function getHeartbeat() {
	return webapi.get<components.GetHeartbeatResponse>(`/api/v1/agent/heartbeat`)
}

/**
 * @description "Update heartbeat"
 */
export function updateHeartbeat(req: components.UpdateHeartbeatRequest) {
	return webapi.put<components.UpdateHeartbeatResponse>(`/api/v1/agent/heartbeat`, req)
}

/**
 * @description "Get lanes"
 */
export function getLanes() {
	return webapi.get<components.GetLanesResponse>(`/api/v1/agent/lanes`)
}

/**
 * @description "List personality presets"
 */
export function listPersonalityPresets() {
	return webapi.get<components.ListPersonalityPresetsResponse>(`/api/v1/agent/personality-presets`)
}

/**
 * @description "Get agent profile"
 */
export function getAgentProfile() {
	return webapi.get<components.AgentProfileResponse>(`/api/v1/agent/profile`)
}

/**
 * @description "Update agent profile"
 */
export function updateAgentProfile(req: components.UpdateAgentProfileRequest) {
	return webapi.put<components.MessageResponse>(`/api/v1/agent/profile`, req)
}

/**
 * @description "List agent sessions"
 */
export function listAgentSessions() {
	return webapi.get<components.ListAgentSessionsResponse>(`/api/v1/agent/sessions`)
}

/**
 * @description "Delete agent session"
 */
export function deleteAgentSession(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/agent/sessions/${id}`)
}

/**
 * @description "Get agent session messages"
 */
export function getAgentSessionMessages(id: string, limit = 50, before?: string) {
	const params = new URLSearchParams({ limit: String(limit) });
	if (before) params.set('before', before);
	return webapi.get<components.GetAgentSessionMessagesResponse>(`/api/v1/agent/sessions/${id}/messages?${params}`)
}

/**
 * @description "Get agent settings"
 */
export function getAgentSettings() {
	return webapi.get<components.GetAgentSettingsResponse>(`/api/v1/agent/settings`)
}

/**
 * @description "Update agent settings"
 */
export function updateAgentSettings(req: components.UpdateAgentSettingsRequest) {
	return webapi.put<components.MessageResponse>(`/api/v1/agent/settings`, req)
}

/**
 * @description "Get simple agent status"
 */
export function getSimpleAgentStatus() {
	return webapi.get<components.SimpleAgentStatusResponse>(`/api/v1/agent/status`)
}

/**
 * @description "Get system info"
 */
export function getSystemInfo() {
	return webapi.get<components.SystemInfoResponse>(`/api/v1/agent/system-info`)
}

/**
 * @description "List all installed agents (active + inactive)"
 */
export function listAgents() {
	return webapi.get<components.ListAgentsResponse>(`/api/v1/agents`)
}

/**
 * @description "Create a blank agent instance and auto-activate it"
 */
export function createBlankAgent() {
	return webapi.post<{ agent: { id: string; name: string }; activated: boolean }>(`/api/v1/agents`, { blank: true })
}

/**
 * @description "Get full agent details"
 */
export function getAgent(agentId: string) {
	return webapi.get<components.AgentDetailResponse>(`/api/v1/agents/${agentId}`)
}

/**
 * @description "Update an agent's name, description, or agentMd"
 */
export function updateAgent(agentId: string, data: { name?: string; description?: string; agentMd?: string }) {
	return webapi.put<{ agent: { id: string; name: string; description: string; agentMd: string } }>(`/api/v1/agents/${agentId}`, data)
}

/**
 * @description "Delete an agent"
 */
export function deleteAgent(agentId: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/agents/${agentId}`)
}

/**
 * @description "Activate an agent — makes it appear in sidebar as its own bot"
 */
export function activateAgent(agentId: string) {
	return webapi.post<components.ActivateAgentResponse>(`/api/v1/agents/${agentId}/activate`, {})
}

/**
 * @description "Apply marketplace update to an agent"
 */
export function applyAgentUpdate(agentId: string) {
	return webapi.post<{ ok: boolean; agent?: components.AgentDetailResponse['agent'] }>(`/api/v1/agents/${agentId}/apply-update`, {})
}

/**
 * @description "Send a chat message to a specific agent"
 */
export function chatWithAgent(agentId: string, prompt: string) {
	return webapi.post<components.ChatWithAgentResponse>(`/api/v1/agents/${agentId}/chat`, { prompt })
}

/**
 * @description "List chats for an agent"
 */
export function listAgentChats(agentId: string) {
	return webapi.get<{ chats: components.Chat[]; activeChatId: string; total: number }>(`/api/v1/agents/${agentId}/chats`)
}

/**
 * @description "Create a new chat for an agent"
 */
export function createNewAgentChat(agentId: string) {
	return webapi.post<{ chat: components.Chat; messages: never[]; totalMessages: number; sessionKey: string }>(`/api/v1/agents/${agentId}/chats`, {})
}

/**
 * @description "Switch to an existing agent chat"
 */
export function activateAgentChat(agentId: string, chatId: string) {
	return webapi.post<{ chatId: string; messages: components.ChatMessage[]; totalMessages: number; sessionKey: string }>(`/api/v1/agents/${agentId}/chats/${chatId}/activate`, {})
}

/**
 * @description "Check if a marketplace agent has an update available"
 */
export function checkAgentUpdate(agentId: string) {
	return webapi.post<{ hasUpdate: boolean; localVersion?: string; remoteVersion?: string; error?: string }>(`/api/v1/agents/${agentId}/check-update`, {})
}

/**
 * @description "Deactivate an agent — removes it from sidebar"
 */
export function deactivateAgent(agentId: string) {
	return webapi.post<components.DeactivateAgentResponse>(`/api/v1/agents/${agentId}/deactivate`, {})
}

/**
 * @description "Duplicate an agent"
 */
export function duplicateAgent(agentId: string) {
	return webapi.post<{ agent: { id: string; name: string }; activated: boolean }>(`/api/v1/agents/${agentId}/duplicate`, {})
}

/**
 * @description "Update user-supplied input values for an agent"
 */
export function updateAgentInputs(agentId: string, values: Record<string, unknown>) {
	return webapi.put<{ ok: boolean }>(`/api/v1/agents/${agentId}/inputs`, values)
}

/**
 * @description "Install agent dependencies"
 */
export function installAgentDeps(agentId: string) {
	return webapi.post<components.MessageResponse>(`/api/v1/agents/${agentId}/install-deps`)
}

/**
 * @description "Get agent navigation config"
 */
export function getAgentNav(agentId: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/agents/${agentId}/nav`)
}

/**
 * @description "Reload agent from filesystem (AGENT.md + agent.json)"
 */
export function reloadAgent(agentId: string) {
	return webapi.post<{ ok: boolean; reloaded?: string[]; agent?: components.AgentDetailResponse['agent'] }>(`/api/v1/agents/${agentId}/reload`, {})
}

/**
 * @description "List workflow runs for an agent"
 */
export function listAgentRuns(agentId: string, limit = 20, offset = 0) {
	return webapi.get<components.ListAgentRunsResponse>(`/api/v1/agents/${agentId}/runs?limit=${limit}&offset=${offset}`)
}

/**
 * @description "Trigger agent setup wizard"
 */
export function triggerAgentSetup(agentId: string) {
	return webapi.post<{ ok: boolean }>(`/api/v1/agents/${agentId}/setup`, {})
}

/**
 * @description "Get workflow run stats for an agent"
 */
export function getAgentStats(agentId: string) {
	return webapi.get<components.AgentStatsResponse>(`/api/v1/agents/${agentId}/stats`)
}

/**
 * @description "Get active A2UI surface replay messages for an agent"
 */
export function getAgentSurfaces(agentId: string) {
	return webapi.get<{ messages: unknown[] }>(`/api/v1/agents/${agentId}/surfaces`)
}

/**
 * @description "Get agent theme CSS"
 */
export function getAgentTheme(agentId: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/agents/${agentId}/theme.css`)
}

/**
 * @description "Toggle agent enabled state"
 */
export function toggleAgent(agentId: string) {
	return webapi.post<components.MessageResponse>(`/api/v1/agents/${agentId}/toggle`)
}

/**
 * @description "Get workflows for an agent"
 */
export function getAgentWorkflows(agentId: string) {
	return webapi.get<components.GetAgentWorkflowsResponse>(`/api/v1/agents/${agentId}/workflows`)
}

/**
 * @description "Create a new workflow binding for an agent"
 */
export function createAgentWorkflow(req: components.CreateAgentWorkflowRequest, agentId: string) {
	return webapi.post<components.AgentWorkflowMutationResponse>(`/api/v1/agents/${agentId}/workflows`, req)
}

/**
 * @description "Update an existing workflow binding for an agent"
 */
export function updateAgentWorkflow(agentId: string, bindingName: string, data: components.UpdateAgentWorkflowRequest) {
	return webapi.put<components.AgentWorkflowMutationResponse>(`/api/v1/agents/${agentId}/workflows/${bindingName}`, data)
}

/**
 * @description "Delete a workflow binding"
 */
export function deleteAgentWorkflow(agentId: string, bindingName: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/agents/${agentId}/workflows/${bindingName}`)
}

/**
 * @description "Toggle a workflow binding on/off"
 */
export function toggleAgentWorkflow(agentId: string, bindingName: string) {
	return webapi.post<components.ToggleAgentWorkflowResponse>(`/api/v1/agents/${agentId}/workflows/${bindingName}/toggle`, {})
}

/**
 * @description "Get active agents — agents currently running as separate bots"
 */
export function getActiveAgents() {
	return webapi.get<components.GetActiveAgentsResponse>(`/api/v1/agents/active`)
}

/**
 * @description "List available event sources from active workflow emits"
 */
export function listEventSources() {
	return webapi.get<components.ListEventSourcesResponse>(`/api/v1/agents/event-sources`)
}

/**
 * @description "Get auth config"
 */
export function getAuthConfig() {
	return webapi.get<components.AuthConfigResponse>(`/api/v1/auth/config`)
}

/**
 * @description "Forgot password"
 */
export function forgotPassword(req: components.ForgotPasswordRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/auth/forgot`, req)
}

/**
 * @description "Login"
 */
export function login(req: components.LoginRequest) {
	return webapi.post<components.LoginResponse>(`/api/v1/auth/login`, req)
}

/**
 * @description "Refresh token"
 */
export function refreshToken(req: components.RefreshTokenRequest) {
	return webapi.post<components.RefreshTokenResponse>(`/api/v1/auth/refresh`, req)
}

/**
 * @description "Register"
 */
export function register(req: components.RegisterRequest) {
	return webapi.post<components.LoginResponse>(`/api/v1/auth/register`, req)
}

/**
 * @description "Resend verification"
 */
export function resendVerification(req: components.ResendVerificationRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/auth/resend`, req)
}

/**
 * @description "Reset password"
 */
export function resetPassword(req: components.ResetPasswordRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/auth/reset`, req)
}

/**
 * @description "Verify email"
 */
export function verifyEmail() {
	return webapi.post<components.MessageResponse>(`/api/v1/auth/verify`)
}

/**
 * @description "List chats"
 */
export function listChats(params: components.ListChatsRequestParams) {
	return webapi.get<components.ListChatsResponse>(`/api/v1/chats`, params)
}

/**
 * @description "Create chat"
 */
export function createChat(req: components.CreateChatRequest) {
	return webapi.post<components.CreateChatResponse>(`/api/v1/chats`, req)
}

/**
 * @description "Get chat"
 */
export function getChat(id: string) {
	return webapi.get<components.GetChatResponse>(`/api/v1/chats/${id}`)
}

/**
 * @description "Update chat"
 */
export function updateChat(req: components.UpdateChatRequest, id: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/chats/${id}`, req)
}

/**
 * @description "Delete chat"
 */
export function deleteChat(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/chats/${id}`)
}

/**
 * @description "Get chat messages by chat_id"
 */
export function getChatMessages(chatId: string, params?: { max_chars?: number; before?: string }) {
	const query = new URLSearchParams();
	if (params?.max_chars) query.set('max_chars', String(params.max_chars));
	if (params?.before) query.set('before', params.before);
	const qs = query.toString();
	return webapi.get<{ messages: components.ChatMessage[]; totalMessages: number }>(`/api/v1/chats/${chatId}/messages${qs ? `?${qs}` : ''}`)
}

/**
 * @description "Get tool output lazily by tool_call_id"
 */
export function getToolOutput(chatId: string, toolCallId: string) {
	return webapi.get<{ output: string; isError: boolean }>(`/api/v1/chats/${chatId}/tool-output/${toolCallId}`)
}

/**
 * @description "Get companion chat"
 */
export function getCompanionChat() {
	return webapi.get<components.GetChatResponse>(`/api/v1/chats/companion`)
}

/**
 * @description "Create a new companion chat session"
 */
export function createNewCompanionChat() {
	return webapi.post<components.GetChatResponse>(`/api/v1/chats/companion/new`, {})
}

/**
 * @description "List chat days"
 */
export function listChatDays(params: components.ListChatDaysRequestParams) {
	return webapi.get<components.ListChatDaysResponse>(`/api/v1/chats/days`, params)
}

/**
 * @description "Get history by day"
 */
export function getHistoryByDay(day: string) {
	return webapi.get<components.GetHistoryByDayResponse>(`/api/v1/chats/history/${day}`)
}

/**
 * @description "Send message"
 */
export function sendMessage(req: components.SendMessageRequest) {
	return webapi.post<components.SendMessageResponse>(`/api/v1/chats/message`, req)
}

/**
 * @description "Edit a chat message and truncate everything after it"
 */
export function editChatMessage(messageId: string, content: string) {
	return webapi.post<{ success: boolean; chatId: string }>(`/api/v1/chats/messages/${messageId}/edit`, { content })
}

/**
 * @description "Search chat messages"
 */
export function searchChatMessages(params: components.SearchChatMessagesRequestParams) {
	return webapi.get<components.SearchChatMessagesResponse>(`/api/v1/chats/search`, params)
}

/**
 * @description "Submit install code"
 */
export function submitCode() {
	return webapi.post<components.MessageResponse>(`/api/v1/codes`)
}

/**
 * @description "Create commander edge"
 */
export function createCommanderEdge() {
	return webapi.post<components.MessageResponse>(`/api/v1/commander/edges`)
}

/**
 * @description "Delete commander edge"
 */
export function deleteCommanderEdge(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/commander/edges/${id}`)
}

/**
 * @description "Get commander graph"
 */
export function getCommanderGraph() {
	return webapi.get<components.MessageResponse>(`/api/v1/commander/graph`)
}

/**
 * @description "Save commander layout"
 */
export function saveCommanderLayout() {
	return webapi.put<components.MessageResponse>(`/api/v1/commander/layout`)
}

/**
 * @description "Create commander team"
 */
export function createCommanderTeam() {
	return webapi.post<components.MessageResponse>(`/api/v1/commander/teams`)
}

/**
 * @description "Update commander team"
 */
export function updateCommanderTeam(id: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/commander/teams/${id}`)
}

/**
 * @description "Delete commander team"
 */
export function deleteCommanderTeam(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/commander/teams/${id}`)
}

/**
 * @description "Approve dependency cascade"
 */
export function approveDeps() {
	return webapi.post<components.MessageResponse>(`/api/v1/deps/approve`)
}

export interface ResolvedEntityConfig {
	entityType: string;
	entityId: string;
	heartbeatEnabled: boolean;
	heartbeatIntervalMinutes: number;
	heartbeatContent: string;
	heartbeatWindow: [string, string] | null;
	permissions: Record<string, boolean>;
	resourceGrants: Record<string, string>;
	modelPreference: string | null;
	personalitySnippet: string | null;
	overrides: Record<string, boolean>;
	allowedPaths: string[];
}

/**
 * @description "Get entity config"
 */
export function getEntityConfig(entityType: string, entityId: string) {
	return webapi.get<{ config: ResolvedEntityConfig }>(`/api/v1/entity-config/${entityType}/${entityId}`)
}

/**
 * @description "Update entity config"
 */
export function updateEntityConfig(entityType: string, entityId: string, patch: Record<string, unknown>) {
	return webapi.put<{ config: ResolvedEntityConfig }>(`/api/v1/entity-config/${entityType}/${entityId}`, patch)
}

/**
 * @description "Delete entity config"
 */
export function deleteEntityConfig(entityType: string, entityId: string) {
	return webapi.delete<{ message: string }>(`/api/v1/entity-config/${entityType}/${entityId}`)
}

/**
 * @description "List extensions"
 */
export function listExtensions() {
	return webapi.get<components.ListExtensionsResponse>(`/api/v1/extensions`)
}

/**
 * @description "Browse files"
 */
export function browseFiles() {
	return webapi.post<components.BrowseFilesResponse>(`/api/v1/files/browse`)
}

/**
 * @description "Pick files via native dialog"
 */
export function pickFiles() {
	return webapi.post<{ paths: string[] }>(`/api/v1/files/pick`)
}

/**
 * @description "Pick a folder via native dialog"
 */
export function pickFolder() {
	return webapi.post<{ path: string | null }>(`/api/v1/files/pick-folder`, {})
}

/**
 * @description "List MCP integrations"
 */
export function listMCPIntegrations() {
	return webapi.get<components.ListMCPIntegrationsResponse>(`/api/v1/integrations`)
}

/**
 * @description "Create MCP integration"
 */
export function createMCPIntegration(req: components.CreateMCPIntegrationRequest) {
	return webapi.post<components.CreateMCPIntegrationResponse>(`/api/v1/integrations`, req)
}

/**
 * @description "Get MCP integration"
 */
export function getMCPIntegration(id: string) {
	return webapi.get<components.GetMCPIntegrationResponse>(`/api/v1/integrations/${id}`)
}

/**
 * @description "Update MCP integration"
 */
export function updateMCPIntegration(req: components.UpdateMCPIntegrationRequest, id: string) {
	return webapi.put<components.UpdateMCPIntegrationResponse>(`/api/v1/integrations/${id}`, req)
}

/**
 * @description "Delete MCP integration"
 */
export function deleteMCPIntegration(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/integrations/${id}`)
}

/**
 * @description "Connect MCP integration — establish connection and register tools"
 */
export function connectMCPIntegration(id: string) {
	return webapi.post<{ success: boolean; message: string; toolCount?: number; tools?: string[] }>(`/api/v1/integrations/${id}/connect`)
}

/**
 * @description "Get MCP OAuth URL"
 */
export function getMCPOAuthURL(id: string) {
	return webapi.get<components.GetMCPOAuthURLResponse>(`/api/v1/integrations/${id}/oauth-url`)
}

/**
 * @description "Reauthenticate MCP integration — clear credentials and restart OAuth flow"
 */
export function reauthenticateMCPIntegration(id: string) {
	return webapi.post<{ authUrl: string }>(`/api/v1/integrations/${id}/reauthenticate`)
}

/**
 * @description "Test MCP integration"
 */
export function testMCPIntegration(id: string) {
	return webapi.post<components.TestMCPIntegrationResponse>(`/api/v1/integrations/${id}/test`)
}

/**
 * @description "List MCP server registry"
 */
export function listMCPServerRegistry() {
	return webapi.get<components.ListMCPServerRegistryResponse>(`/api/v1/integrations/registry`)
}

/**
 * @description "List MCP tools"
 */
export function listMCPTools() {
	return webapi.get<components.ListMCPToolsResponse>(`/api/v1/integrations/tools`)
}

/**
 * @description "Local models status"
 */
export function localModelsStatus() {
	return webapi.get<components.LocalModelsStatusResponse>(`/api/v1/local-models/status`)
}

/**
 * @description "List memories"
 */
export function listMemories(params: components.ListMemoriesRequestParams) {
	return webapi.get<components.ListMemoriesResponse>(`/api/v1/memories`, params)
}

/**
 * @description "Get memory"
 */
export function getMemory(id: string) {
	return webapi.get<components.GetMemoryResponse>(`/api/v1/memories/${id}`)
}

/**
 * @description "Update memory"
 */
export function updateMemory(req: components.UpdateMemoryRequest, id: string) {
	return webapi.put<components.GetMemoryResponse>(`/api/v1/memories/${id}`, req)
}

/**
 * @description "Delete memory"
 */
export function deleteMemory(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/memories/${id}`)
}

/**
 * @description "Search memories"
 */
export function searchMemories(params: components.SearchMemoriesRequestParams) {
	return webapi.get<components.SearchMemoriesResponse>(`/api/v1/memories/search`, params)
}

/**
 * @description "Get memory stats"
 */
export function getMemoryStats() {
	return webapi.get<components.MemoryStatsResponse>(`/api/v1/memories/stats`)
}

/**
 * @description "List models"
 */
export function listModels() {
	return webapi.get<components.ListModelsResponse>(`/api/v1/models`)
}

/**
 * @description "Update model"
 */
export function updateModel(req: components.UpdateModelRequest, provider: string, modelId: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/models/${provider}/${modelId}`, req)
}

/**
 * @description "Update CLI provider"
 */
export function updateCLIProvider(req: components.UpdateCLIProviderRequest, cliId: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/models/cli/${cliId}`, req)
}

/**
 * @description "Update model config"
 */
export function updateModelConfig(req: components.UpdateModelConfigRequest) {
	return webapi.put<components.UpdateModelConfigResponse>(`/api/v1/models/config`, req)
}

/**
 * @description "Update task routing"
 */
export function updateTaskRouting(req: components.UpdateTaskRoutingRequest) {
	return webapi.put<components.MessageResponse>(`/api/v1/models/task-routing`, req)
}

/**
 * @description "NeboLoop account status"
 */
export function neboLoopAccountStatus() {
	return webapi.get<components.NeboLoopAccountStatusResponse>(`/api/v1/neboloop/account`)
}

/**
 * @description "NeboLoop disconnect"
 */
export function neboLoopDisconnect() {
	return webapi.delete<components.NeboLoopDisconnectResponse>(`/api/v1/neboloop/account`)
}

/**
 * @description "Cancel subscription"
 */
export function neboLoopBillingCancel(subscriptionId: string) {
	return webapi.post<components.BillingCancelResponse>(`/api/v1/neboloop/billing/cancel`, { subscriptionId })
}

/**
 * @description "Create Stripe checkout session (hosted or embedded)"
 */
export function neboLoopBillingCheckout(priceIds: string[], uiMode?: 'hosted' | 'embedded') {
	return webapi.post<components.BillingCheckoutResponse>(`/api/v1/neboloop/billing/checkout`, { priceIds, uiMode })
}

/**
 * @description "List invoices"
 */
export function neboLoopBillingInvoices() {
	return webapi.get<components.BillingInvoicesResponse>(`/api/v1/neboloop/billing/invoices`)
}

/**
 * @description "List payment methods"
 */
export function neboLoopBillingPaymentMethods() {
	return webapi.get<components.BillingPaymentMethodsResponse>(`/api/v1/neboloop/billing/payment-methods`)
}

/**
 * @description "Open Stripe customer portal"
 */
export function neboLoopBillingPortal() {
	return webapi.post<components.BillingPortalResponse>(`/api/v1/neboloop/billing/portal`)
}

/**
 * @description "Get billing prices/plans"
 */
export function neboLoopBillingPrices() {
	return webapi.get<components.BillingPricesResponse>(`/api/v1/neboloop/billing/prices`)
}

/**
 * @description "Create Stripe SetupIntent for in-app payment method collection"
 */
export function neboLoopBillingSetupIntent() {
	return webapi.post<{ clientSecret: string; publishableKey: string }>(`/api/v1/neboloop/billing/setup-intent`)
}

/**
 * @description "Subscribe to a plan"
 */
export function neboLoopBillingSubscribe() {
	return webapi.post<components.MessageResponse>(`/api/v1/neboloop/billing/subscribe`)
}

/**
 * @description "Get current subscription"
 */
export function neboLoopBillingSubscription() {
	return webapi.get<components.BillingSubscriptionResponse>(`/api/v1/neboloop/billing/subscription`)
}

/**
 * @description "NeboLoop connect"
 */
export function neboLoopConnect(req: components.NeboLoopConnectRequest) {
	return webapi.post<components.NeboLoopConnectResponse>(`/api/v1/neboloop/connect`, req)
}

/**
 * @description "NeboLoop Janus usage"
 */
export function neboLoopJanusUsage() {
	return webapi.get<components.NeboLoopJanusUsageResponse>(`/api/v1/neboloop/janus/usage`)
}

/**
 * @description "Force-refresh Janus usage from Janus gateway"
 */
export function neboLoopJanusUsageRefresh() {
	return webapi.post<components.NeboLoopJanusUsageResponse>(`/api/v1/neboloop/janus/usage/refresh`)
}

/**
 * @description "NeboLoop OAuth start"
 */
export function neboLoopOAuthStart() {
	return webapi.get<components.NeboLoopOAuthStartResponse>(`/api/v1/neboloop/oauth/start`)
}

/**
 * @description "NeboLoop OAuth status"
 */
export function neboLoopOAuthStatus(params: components.NeboLoopOAuthStatusRequestParams) {
	return webapi.get<components.NeboLoopOAuthStatusResponse>(`/api/v1/neboloop/oauth/status`, params)
}

/**
 * @description "NeboLoop open"
 */
export function neboLoopOpen() {
	return webapi.get<components.MessageResponse>(`/api/v1/neboloop/open`)
}

/**
 * @description "Force reconnect to NeboLoop"
 */
export function neboLoopForceReconnect() {
	return webapi.post<components.MessageResponse>(`/api/v1/neboloop/reconnect`)
}

/**
 * @description "Get or create the user's referral/invite code"
 */
export function neboLoopReferralCode() {
	return webapi.get<components.NeboLoopReferralCodeResponse>(`/api/v1/neboloop/referral-code`)
}

/**
 * @description "NeboLoop status"
 */
export function neboLoopStatus() {
	return webapi.get<components.NeboLoopStatusResponse>(`/api/v1/neboloop/status`)
}

/**
 * @description "List notifications"
 */
export function listNotifications(params: components.ListNotificationsRequestParams) {
	return webapi.get<components.ListNotificationsResponse>(`/api/v1/notifications`, params)
}

/**
 * @description "Delete notification"
 */
export function deleteNotification(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/notifications/${id}`)
}

/**
 * @description "Mark notification read"
 */
export function markNotificationRead(id: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/notifications/${id}/read`)
}

/**
 * @description "Mark all notifications read"
 */
export function markAllNotificationsRead() {
	return webapi.put<components.MessageResponse>(`/api/v1/notifications/read-all`)
}

/**
 * @description "Get unread count"
 */
export function getUnreadCount() {
	return webapi.get<components.GetUnreadCountResponse>(`/api/v1/notifications/unread-count`)
}

/**
 * @description "List plugins"
 */
export function listPlugins() {
	return webapi.get<components.ListInstalledPluginsResponse>(`/api/v1/plugins`)
}

/**
 * @description "Remove plugin"
 */
export function removePlugin(slug: string) {
	return webapi.delete<{ message: string }>(`/api/v1/plugins/${slug}`)
}

/**
 * @description "Plugin auth login"
 */
export function pluginAuthLogin(slug: string) {
	return webapi.post<{ started: boolean }>(`/api/v1/plugins/${slug}/auth/login`)
}

/**
 * @description "Plugin auth logout"
 */
export function pluginAuthLogout(slug: string) {
	return webapi.post<{ success: boolean }>(`/api/v1/plugins/${slug}/auth/logout`)
}

/**
 * @description "Plugin auth status"
 */
export function pluginAuthStatus(slug: string) {
	return webapi.get<components.PluginAuthStatusResponse>(`/api/v1/plugins/${slug}/auth/status`)
}

/**
 * @description "List plugin events"
 */
export function listPluginEvents(slug: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/plugins/${slug}/events`)
}

/**
 * @description "List all plugin events"
 */
export function listAllPluginEvents() {
	return webapi.get<components.MessageResponse>(`/api/v1/plugins/events`)
}

/**
 * @description "List auth profiles"
 */
export function listAuthProfiles() {
	return webapi.get<components.ListAuthProfilesResponse>(`/api/v1/providers`)
}

/**
 * @description "Create auth profile"
 */
export function createAuthProfile(req: components.CreateAuthProfileRequest) {
	return webapi.post<components.CreateAuthProfileResponse>(`/api/v1/providers`, req)
}

/**
 * @description "Get auth profile"
 */
export function getAuthProfile(id: string) {
	return webapi.get<components.GetAuthProfileResponse>(`/api/v1/providers/${id}`)
}

/**
 * @description "Update auth profile"
 */
export function updateAuthProfile(req: components.UpdateAuthProfileRequest, id: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/providers/${id}`, req)
}

/**
 * @description "Delete auth profile"
 */
export function deleteAuthProfile(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/providers/${id}`)
}

/**
 * @description "Test auth profile"
 */
export function testAuthProfile(id: string) {
	return webapi.post<components.TestAuthProfileResponse>(`/api/v1/providers/${id}/test`)
}

/**
 * @description "List active agent runs"
 */
export function listActiveRuns() {
	return webapi.get<components.MessageResponse>(`/api/v1/runs/active`)
}

/**
 * @description "Create admin"
 */
export function createAdmin(req: components.CreateAdminRequest) {
	return webapi.post<components.CreateAdminResponse>(`/api/v1/setup/admin`, req)
}

/**
 * @description "Complete setup"
 */
export function completeSetup() {
	return webapi.post<components.CompleteSetupResponse>(`/api/v1/setup/complete`)
}

/**
 * @description "Get personality"
 */
export function getPersonality() {
	return webapi.get<components.GetPersonalityResponse>(`/api/v1/setup/personality`)
}

/**
 * @description "Update personality"
 */
export function updatePersonality(req: components.UpdatePersonalityRequest) {
	return webapi.put<components.UpdatePersonalityResponse>(`/api/v1/setup/personality`, req)
}

/**
 * @description "Setup status"
 */
export function setupStatus() {
	return webapi.get<components.SetupStatusResponse>(`/api/v1/setup/status`)
}

/**
 * @description "Create skill"
 */
export function createSkill(req: components.CreateSkillRequest) {
	return webapi.post<components.CreateSkillResponse>(`/api/v1/skills`, req)
}

/**
 * @description "Get skill"
 */
export function getSkill(name: string) {
	return webapi.get<components.GetSkillResponse>(`/api/v1/skills/${name}`)
}

/**
 * @description "Update skill"
 */
export function updateSkill(req: components.UpdateSkillRequest, name: string) {
	return webapi.put<components.UpdateSkillResponse>(`/api/v1/skills/${name}`, req)
}

/**
 * @description "Delete skill"
 */
export function deleteSkill(name: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/skills/${name}`)
}

/**
 * @description "Get skill content"
 */
export function getSkillContent(name: string) {
	return webapi.get<components.GetSkillContentResponse>(`/api/v1/skills/${name}/content`)
}

/**
 * @description "List skill secrets and their configuration status"
 */
export function listSkillSecrets(name: string) {
	return webapi.get<{ secrets: Array<{ key: string; label: string; hint: string; required: boolean; configured: boolean }> }>(`/api/v1/skills/${name}/secrets`)
}

/**
 * @description "Set a skill secret"
 */
export function setSkillSecret(name: string, key: string, value: string) {
	return webapi.put<{ success: boolean; key: string }>(`/api/v1/skills/${name}/secrets`, { key, value })
}

/**
 * @description "Delete a skill secret"
 */
export function deleteSkillSecret(name: string, key: string) {
	return webapi.delete<{ success: boolean }>(`/api/v1/skills/${name}/secrets/${key}`)
}

/**
 * @description "Toggle skill"
 */
export function toggleSkill(name: string) {
	return webapi.post<components.ToggleSkillResponse>(`/api/v1/skills/${name}/toggle`)
}

/**
 * @description "List store categories"
 */
export function listStoreCategories() {
	return webapi.get<components.MessageResponse>(`/api/v1/store/categories`)
}

/**
 * @description "List store collections"
 */
export function listStoreCollections() {
	return webapi.get<components.MessageResponse>(`/api/v1/store/collections`)
}

/**
 * @description "Create store collection"
 */
export function createStoreCollection() {
	return webapi.post<components.MessageResponse>(`/api/v1/store/collections`)
}

/**
 * @description "Get store collection"
 */
export function getStoreCollection(id: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/store/collections/${id}`)
}

/**
 * @description "Update store collection"
 */
export function updateStoreCollection(id: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/store/collections/${id}`)
}

/**
 * @description "Delete store collection"
 */
export function deleteStoreCollection(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/store/collections/${id}`)
}

/**
 * @description "Add collection item"
 */
export function addCollectionItem(id: string) {
	return webapi.post<components.MessageResponse>(`/api/v1/store/collections/${id}/items`)
}

/**
 * @description "Remove collection item"
 */
export function removeCollectionItem(id: string, itemId: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/store/collections/${id}/items/${itemId}`)
}

/**
 * @description "List store featured"
 */
export function listStoreFeatured() {
	return webapi.get<components.MessageResponse>(`/api/v1/store/featured`)
}

/**
 * @description "List store orgs"
 */
export function listStoreOrgs() {
	return webapi.get<components.MessageResponse>(`/api/v1/store/orgs`)
}

/**
 * @description "List store products"
 */
export function listStoreProducts() {
	return webapi.get<components.MessageResponse>(`/api/v1/store/products`)
}

/**
 * @description "Get store product"
 */
export function getStoreProduct(id: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/store/products/${id}`)
}

/**
 * @description "Get store product feedback"
 */
export function getStoreProductFeedback(id: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/store/products/${id}/feedback`)
}

/**
 * @description "Submit store product feedback"
 */
export function submitStoreProductFeedback(id: string) {
	return webapi.post<components.MessageResponse>(`/api/v1/store/products/${id}/feedback`)
}

/**
 * @description "Install store product"
 */
export function installStoreProduct(id: string) {
	return webapi.post<components.MessageResponse>(`/api/v1/store/products/${id}/install`)
}

/**
 * @description "Uninstall store product"
 */
export function uninstallStoreProduct(id: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/store/products/${id}/install`)
}

/**
 * @description "Get store product media"
 */
export function getStoreProductMedia(id: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/store/products/${id}/media`)
}

/**
 * @description "Get store product reviews"
 */
export function getStoreProductReviews(id: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/store/products/${id}/reviews`)
}

/**
 * @description "Submit store product review"
 */
export function submitStoreProductReview(id: string) {
	return webapi.post<components.MessageResponse>(`/api/v1/store/products/${id}/reviews`)
}

/**
 * @description "Get similar store products"
 */
export function getStoreProductSimilar(id: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/store/products/${id}/similar`)
}

/**
 * @description "List top store products"
 */
export function listStoreProductsTop() {
	return webapi.get<components.MessageResponse>(`/api/v1/store/products/top`)
}

/**
 * @description "Get store screenshots"
 */
export function getStoreScreenshots(type: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/store/screenshots/${type}`)
}

/**
 * @description "List tasks"
 */
export function listTasks(params: components.ListTasksRequestParams) {
	return webapi.get<components.ListTasksResponse>(`/api/v1/tasks`, params)
}

/**
 * @description "Create task"
 */
export function createTask(req: components.CreateTaskRequest) {
	return webapi.post<components.CreateTaskResponse>(`/api/v1/tasks`, req)
}

/**
 * @description "Get task"
 */
export function getTask(name: string) {
	return webapi.get<components.GetTaskResponse>(`/api/v1/tasks/${name}`)
}

/**
 * @description "Update task"
 */
export function updateTask(req: components.UpdateTaskRequest, name: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/tasks/${name}`, req)
}

/**
 * @description "Delete task"
 */
export function deleteTask(name: string) {
	return webapi.delete<components.MessageResponse>(`/api/v1/tasks/${name}`)
}

/**
 * @description "List task history"
 */
export function listTaskHistory(params: components.ListTaskHistoryRequestParams, name: string) {
	return webapi.get<components.ListTaskHistoryResponse>(`/api/v1/tasks/${name}/history`, params)
}

/**
 * @description "Run task"
 */
export function runTask(name: string) {
	return webapi.post<components.RunTaskResponse>(`/api/v1/tasks/${name}/run`)
}

/**
 * @description "Toggle task"
 */
export function toggleTask(name: string) {
	return webapi.post<components.ToggleTaskResponse>(`/api/v1/tasks/${name}/toggle`)
}

/**
 * @description "Update apply"
 */
export function updateApply() {
	return webapi.post<components.UpdateApplyResponse>(`/api/v1/update/apply`)
}

/**
 * @description "Update check"
 */
export function updateCheck() {
	return webapi.get<components.UpdateCheckResponse>(`/api/v1/update/check`)
}

/**
 * @description "Get current user"
 */
export function getCurrentUser() {
	return webapi.get<components.GetUserResponse>(`/api/v1/user/me`)
}

/**
 * @description "Update current user"
 */
export function updateCurrentUser(req: components.UpdateUserRequest) {
	return webapi.put<components.GetUserResponse>(`/api/v1/user/me`, req)
}

/**
 * @description "Delete account"
 */
export function deleteAccount(req: components.DeleteAccountRequest) {
	return webapi.delete<components.MessageResponse>(`/api/v1/user/me`)
}

/**
 * @description "Accept terms"
 */
export function acceptTerms() {
	return webapi.post<components.AcceptTermsResponse>(`/api/v1/user/me/accept-terms`)
}

/**
 * @description "Change password"
 */
export function changePassword(req: components.ChangePasswordRequest) {
	return webapi.post<components.MessageResponse>(`/api/v1/user/me/change-password`, req)
}

/**
 * @description "Get tool permissions"
 */
export function getToolPermissions() {
	return webapi.get<components.GetToolPermissionsResponse>(`/api/v1/user/me/permissions`)
}

/**
 * @description "Update tool permissions"
 */
export function updateToolPermissions(req: components.UpdateToolPermissionsRequest) {
	return webapi.put<components.UpdateToolPermissionsResponse>(`/api/v1/user/me/permissions`, req)
}

/**
 * @description "Get preferences"
 */
export function getPreferences() {
	return webapi.get<components.GetPreferencesResponse>(`/api/v1/user/me/preferences`)
}

/**
 * @description "Update preferences"
 */
export function updatePreferences(req: components.UpdatePreferencesRequest) {
	return webapi.put<components.MessageResponse>(`/api/v1/user/me/preferences`, req)
}

/**
 * @description "Get user profile"
 */
export function getUserProfile() {
	return webapi.get<components.GetUserProfileResponse>(`/api/v1/user/me/profile`)
}

/**
 * @description "Update user profile"
 */
export function updateUserProfile(req: components.UpdateUserProfileRequest) {
	return webapi.put<components.UpdateUserProfileResponse>(`/api/v1/user/me/profile`, req)
}

export interface WorkflowItem {
	id: string;
	code: string | null;
	name: string;
	version: string;
	definition: string;
	skill_md: string | null;
	installed_at: string;
	enabled: boolean;
}

export interface WorkflowRunEntry {
	id: string;
	workflow_id: string;
	trigger_type: string;
	trigger_detail: string | null;
	status: 'running' | 'completed' | 'failed' | 'aborted';
	inputs: string | null;
	current_activity: string | null;
	total_tokens_used: number;
	total_cost_estimate: string | null;
	error: string | null;
	error_activity: string | null;
	session_key: string | null;
	started_at: string;
	completed_at: string | null;
}

export interface ActivityResult {
	id: number;
	run_id: string;
	activity_id: string;
	status: 'completed' | 'skipped' | 'failed';
	tokens_used: number;
	attempts: number;
	error: string | null;
	started_at: string;
	completed_at: string;
}

/**
 * @description "List workflows"
 */
export function listWorkflows() {
	return webapi.get<{ workflows: WorkflowItem[]; total: number }>(`/api/v1/workflows`)
}

/**
 * @description "Create workflow"
 */
export function createWorkflow() {
	return webapi.post<components.MessageResponse>(`/api/v1/workflows`)
}

/**
 * @description "Get workflow"
 */
export function getWorkflow(id: string) {
	return webapi.get<{ workflow: WorkflowItem }>(`/api/v1/workflows/${id}`)
}

/**
 * @description "Update workflow"
 */
export function updateWorkflow(id: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/workflows/${id}`)
}

/**
 * @description "Delete workflow"
 */
export function deleteWorkflow(id: string) {
	return webapi.delete<{ message: string }>(`/api/v1/workflows/${id}`)
}

/**
 * @description "List workflow bindings"
 */
export function listWorkflowBindings(id: string) {
	return webapi.get<components.MessageResponse>(`/api/v1/workflows/${id}/bindings`)
}

/**
 * @description "Update workflow bindings"
 */
export function updateWorkflowBindings(id: string) {
	return webapi.put<components.MessageResponse>(`/api/v1/workflows/${id}/bindings`)
}

/**
 * @description "Run workflow"
 */
export function runWorkflow(id: string, inputs?: Record<string, unknown>) {
	return webapi.post<{ run: WorkflowRunEntry }>(`/api/v1/workflows/${id}/run`, { inputs: inputs || {} })
}

/**
 * @description "List workflow runs"
 */
export function listWorkflowRuns(id: string) {
	return webapi.get<{ runs: WorkflowRunEntry[]; total: number }>(`/api/v1/workflows/${id}/runs`)
}

/**
 * @description "Get workflow run detail with activities and task items"
 */
export function getWorkflowRun(workflowId: string, runId: string) {
	return webapi.get<{ run: components.WorkflowRun; activities: components.WorkflowActivityResult[]; taskItems: Record<string, components.PendingTask[]> }>(`/api/v1/workflows/${workflowId}/runs/${runId}`)
}

/**
 * @description "Cancel workflow run"
 */
export function cancelWorkflowRun(workflowId: string, runId: string) {
	return webapi.post<{ cancelled: boolean; runId: string }>(
		`/api/v1/workflows/${workflowId}/runs/${runId}/cancel`, {}
	)
}

/**
 * @description "Toggle workflow"
 */
export function toggleWorkflow(id: string) {
	return webapi.post<{ workflow: WorkflowItem }>(`/api/v1/workflows/${id}/toggle`, {})
}

/**
 * @description "Health check"
 */
export function healthCheck() {
	return webapi.get<components.MessageResponse>(`/health`)
}
