// Code generated by scripts/genapi. DO NOT EDIT.
// To regenerate: make gen

import webapi from "./gocliRequest"
import * as components from "./neboComponents"
export * from "./neboComponents"

/**
 * @description "List advisors"
 */
export function listAdvisors() {
	return webapi.get<components.ListAdvisorsResponse>(`/api/v1/agent/advisors`)
}

/**
 * @description "Create advisor"
 */
export function createAdvisor(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/agent/advisors`, req)
}

/**
 * @description "Get advisor"
 */
export function getAdvisor(name: string) {
	return webapi.get<unknown>(`/api/v1/agent/advisors/${name}`)
}

/**
 * @description "Update advisor"
 */
export function updateAdvisor(name: string, req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/agent/advisors/${name}`, req)
}

/**
 * @description "Delete advisor"
 */
export function deleteAdvisor(name: string) {
	return webapi.delete<components.DeleteAdvisorResponse>(`/api/v1/agent/advisors/${name}`)
}

/**
 * @description "Get channel messages"
 */
export function getChannelMessages(channelId: string) {
	return webapi.get<components.GetChannelMessagesResponse>(`/api/v1/agent/channels/${channelId}/messages`)
}

/**
 * @description "Send channel message"
 */
export function sendChannelMessage(channelId: string, req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/agent/channels/${channelId}/send`, req)
}

/**
 * @description "Handle available"
 */
export function handleAvailable(handle: string) {
	return webapi.get<components.HandleAvailableResponse>(`/api/v1/agent/handle-available`, { handle })
}

/**
 * @description "Get heartbeat"
 */
export function getHeartbeat() {
	return webapi.get<components.GetHeartbeatResponse>(`/api/v1/agent/heartbeat`)
}

/**
 * @description "Update heartbeat"
 */
export function updateHeartbeat(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateHeartbeatResponse>(`/api/v1/agent/heartbeat`, req)
}

/**
 * @description "Get lanes"
 */
export function getLanes() {
	return webapi.get<components.GetLanesResponse>(`/api/v1/agent/lanes`)
}

/**
 * @description "List personality presets"
 */
export function listPersonalityPresets() {
	return webapi.get<components.ListPersonalityPresetsResponse>(`/api/v1/agent/personality-presets`)
}

/**
 * @description "Get profile"
 */
export function getProfile() {
	return webapi.get<unknown>(`/api/v1/agent/profile`)
}

/**
 * @description "Update profile"
 */
export function updateProfile(req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/agent/profile`, req)
}

/**
 * @description "List sessions"
 */
export function listSessions(limit?: number, offset?: number) {
	return webapi.get<components.ListSessionsResponse>(`/api/v1/agent/sessions`, { limit, offset })
}

/**
 * @description "Delete session"
 */
export function deleteSession(id: string) {
	return webapi.delete<components.DeleteSessionResponse>(`/api/v1/agent/sessions/${id}`)
}

/**
 * @description "Get session messages"
 */
export function getSessionMessages(id: string, limit?: number, before?: string) {
	return webapi.get<components.GetSessionMessagesResponse>(`/api/v1/agent/sessions/${id}/messages`, { limit, before })
}

/**
 * @description "Get settings"
 */
export function getSettings() {
	return webapi.get<components.GetSettingsResponse>(`/api/v1/agent/settings`)
}

/**
 * @description "Update settings"
 */
export function updateSettings(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateSettingsResponse>(`/api/v1/agent/settings`, req)
}

/**
 * @description "Get status"
 */
export function getStatus() {
	return webapi.get<components.GetStatusResponse>(`/api/v1/agent/status`)
}

/**
 * @description "Get system info"
 */
export function getSystemInfo() {
	return webapi.get<components.GetSystemInfoResponse>(`/api/v1/agent/system-info`)
}

/**
 * @description "Agent ws handler"
 */
export function agentWsHandler() {
	return webapi.get<unknown>(`/api/v1/agent/ws`)
}

/**
 * @description "List agents"
 */
export function listAgents(limit?: number, offset?: number) {
	return webapi.get<components.ListAgentsResponse>(`/api/v1/agents`, { limit, offset })
}

/**
 * @description "Create agent"
 */
export function createAgent(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateAgentResponse>(`/api/v1/agents`, req)
}

/**
 * @description "List active agents"
 */
export function listActiveAgents() {
	return webapi.get<components.ListActiveAgentsResponse>(`/api/v1/agents/active`)
}

/**
 * @description "List event sources"
 */
export function listEventSources() {
	return webapi.get<components.ListEventSourcesResponse>(`/api/v1/agents/event-sources`)
}

/**
 * @description "Get agent"
 */
export function getAgent(id: string) {
	return webapi.get<components.GetAgentResponse>(`/api/v1/agents/${id}`)
}

/**
 * @description "Update agent"
 */
export function updateAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateAgentResponse>(`/api/v1/agents/${id}`, req)
}

/**
 * @description "Delete agent"
 */
export function deleteAgent(id: string) {
	return webapi.delete<components.DeleteAgentResponse>(`/api/v1/agents/${id}`)
}

/**
 * @description "Activate agent"
 */
export function activateAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ActivateAgentResponse>(`/api/v1/agents/${id}/activate`, req)
}

/**
 * @description "Apply agent update"
 */
export function applyAgentUpdate(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ApplyAgentUpdateResponse>(`/api/v1/agents/${id}/apply-update`, req)
}

/**
 * @description "List agent channels"
 */
export function listAgentChannels(id: string) {
	return webapi.get<components.ListAgentChannelsResponse>(`/api/v1/agents/${id}/channels`)
}

/**
 * @description "Set agent channel config"
 */
export function setAgentChannelConfig(id: string, pluginSlug: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.SetAgentChannelConfigResponse>(`/api/v1/agents/${id}/channels/${pluginSlug}/config`, req)
}

/**
 * @description "Disable agent channel"
 */
export function disableAgentChannel(id: string, pluginSlug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.DisableAgentChannelResponse>(`/api/v1/agents/${id}/channels/${pluginSlug}/disable`, req)
}

/**
 * @description "Enable agent channel"
 */
export function enableAgentChannel(id: string, pluginSlug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.EnableAgentChannelResponse>(`/api/v1/agents/${id}/channels/${pluginSlug}/enable`, req)
}

/**
 * @description "Chat with agent"
 */
export function chatWithAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ChatWithAgentResponse>(`/api/v1/agents/${id}/chat`, req)
}

/**
 * @description "List agent chats"
 */
export function listAgentChats(id: string) {
	return webapi.get<components.ListAgentChatsResponse>(`/api/v1/agents/${id}/chats`)
}

/**
 * @description "Create new agent chat"
 */
export function createNewAgentChat(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateNewAgentChatResponse>(`/api/v1/agents/${id}/chats`, req)
}

/**
 * @description "Activate agent chat"
 */
export function activateAgentChat(id: string, chatId: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ActivateAgentChatResponse>(`/api/v1/agents/${id}/chats/${chatId}/activate`, req)
}

/**
 * @description "Check agent update"
 */
export function checkAgentUpdate(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.CheckAgentUpdateResponse>(`/api/v1/agents/${id}/check-update`, req)
}

/**
 * @description "Deactivate agent"
 */
export function deactivateAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.DeactivateAgentResponse>(`/api/v1/agents/${id}/deactivate`, req)
}

/**
 * @description "Duplicate agent"
 */
export function duplicateAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.DuplicateAgentResponse>(`/api/v1/agents/${id}/duplicate`, req)
}

/**
 * @description "Update agent inputs"
 */
export function updateAgentInputs(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateAgentInputsResponse>(`/api/v1/agents/${id}/inputs`, req)
}

/**
 * @description "Reload agent"
 */
export function reloadAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ReloadAgentResponse>(`/api/v1/agents/${id}/reload`, req)
}

/**
 * @description "List agent runs"
 */
export function listAgentRuns(id: string, limit?: number, offset?: number) {
	return webapi.get<components.ListAgentRunsResponse>(`/api/v1/agents/${id}/runs`, { limit, offset })
}

/**
 * @description "Trigger agent setup"
 */
export function triggerAgentSetup(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.TriggerAgentSetupResponse>(`/api/v1/agents/${id}/setup`, req)
}

/**
 * @description "Agent stats"
 */
export function agentStats(id: string) {
	return webapi.get<components.AgentStatsResponse>(`/api/v1/agents/${id}/stats`)
}

/**
 * @description "Get agent surfaces"
 */
export function getAgentSurfaces(id: string) {
	return webapi.get<components.GetAgentSurfacesResponse>(`/api/v1/agents/${id}/surfaces`)
}

/**
 * @description "Get agent theme"
 */
export function getAgentTheme(id: string) {
	return webapi.get<unknown>(`/api/v1/agents/${id}/theme.css`)
}

/**
 * @description "Toggle agent"
 */
export function toggleAgent(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ToggleAgentResponse>(`/api/v1/agents/${id}/toggle`, req)
}

/**
 * @description "Start workflow chat"
 */
export function startWorkflowChat(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.StartWorkflowChatResponse>(`/api/v1/agents/${id}/workflow/chat`, req)
}

/**
 * @description "List agent workflows"
 */
export function listAgentWorkflows(id: string) {
	return webapi.get<components.ListAgentWorkflowsResponse>(`/api/v1/agents/${id}/workflows`)
}

/**
 * @description "Create agent workflow"
 */
export function createAgentWorkflow(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateAgentWorkflowResponse>(`/api/v1/agents/${id}/workflows`, req)
}

/**
 * @description "Update agent workflow"
 */
export function updateAgentWorkflow(id: string, bindingName: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateAgentWorkflowResponse>(`/api/v1/agents/${id}/workflows/${bindingName}`, req)
}

/**
 * @description "Delete agent workflow"
 */
export function deleteAgentWorkflow(id: string, bindingName: string) {
	return webapi.delete<components.DeleteAgentWorkflowResponse>(`/api/v1/agents/${id}/workflows/${bindingName}`)
}

/**
 * @description "Toggle agent workflow"
 */
export function toggleAgentWorkflow(id: string, bindingName: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ToggleAgentWorkflowResponse>(`/api/v1/agents/${id}/workflows/${bindingName}/toggle`, req)
}

/**
 * @description "Run agent workflow"
 */
export function runAgentWorkflow(id: string, name: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.RunAgentWorkflowResponse>(`/api/v1/agents/${id}/workflows/${name}/run`, req)
}

/**
 * @description "Check updates"
 */
export function checkUpdates(req: Record<string, unknown> = {}) {
	return webapi.post<components.CheckUpdatesResponse>(`/api/v1/artifacts/check-updates`, req)
}

/**
 * @description "List update history"
 */
export function listUpdateHistory() {
	return webapi.get<components.ListUpdateHistoryResponse>(`/api/v1/artifacts/update-history`)
}

/**
 * @description "Get update settings"
 */
export function getUpdateSettings() {
	return webapi.get<unknown>(`/api/v1/artifacts/update-settings`)
}

/**
 * @description "Set update settings"
 */
export function setUpdateSettings(req: Record<string, unknown> = {}) {
	return webapi.put<components.SetUpdateSettingsResponse>(`/api/v1/artifacts/update-settings`, req)
}

/**
 * @description "List updates"
 */
export function listUpdates() {
	return webapi.get<components.ListUpdatesResponse>(`/api/v1/artifacts/updates`)
}

/**
 * @description "Apply update"
 */
export function applyUpdate(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ApplyUpdateResponse>(`/api/v1/artifacts/${id}/apply-update`, req)
}

/**
 * @description "Set artifact auto update"
 */
export function setArtifactAutoUpdate(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.SetArtifactAutoUpdateResponse>(`/api/v1/artifacts/${id}/auto-update`, req)
}

/**
 * @description "Config"
 */
export function config() {
	return webapi.get<components.ConfigResponse>(`/api/v1/auth/config`)
}

/**
 * @description "Forgot password"
 */
export function forgotPassword(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/forgot`, req)
}

/**
 * @description "Login"
 */
export function login(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/login`, req)
}

/**
 * @description "Refresh"
 */
export function refresh(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/refresh`, req)
}

/**
 * @description "Register"
 */
export function register(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/register`, req)
}

/**
 * @description "Resend verification"
 */
export function resendVerification(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/resend`, req)
}

/**
 * @description "Reset password"
 */
export function resetPassword(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/reset`, req)
}

/**
 * @description "Verify email"
 */
export function verifyEmail(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/auth/verify`, req)
}

/**
 * @description "Browser status"
 */
export function browserStatus() {
	return webapi.get<components.BrowserStatusResponse>(`/api/v1/browser/status`)
}

/**
 * @description "List chats"
 */
export function listChats(limit?: number, offset?: number) {
	return webapi.get<components.ListChatsResponse>(`/api/v1/chats`, { limit, offset })
}

/**
 * @description "Create chat"
 */
export function createChat(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/chats`, req)
}

/**
 * @description "Get companion chat"
 */
export function getCompanionChat(max_chars?: number) {
	return webapi.get<components.GetCompanionChatResponse>(`/api/v1/chats/companion`, { max_chars })
}

/**
 * @description "Create companion chat"
 */
export function createCompanionChat(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateCompanionChatResponse>(`/api/v1/chats/companion/new`, req)
}

/**
 * @description "List chat days"
 */
export function listChatDays(limit?: number, offset?: number) {
	return webapi.get<components.ListChatDaysResponse>(`/api/v1/chats/days`, { limit, offset })
}

/**
 * @description "Get chat history by day"
 */
export function getChatHistoryByDay(day: string) {
	return webapi.get<components.GetChatHistoryByDayResponse>(`/api/v1/chats/history/${day}`)
}

/**
 * @description "Send message"
 */
export function sendMessage(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/chats/message`, req)
}

/**
 * @description "Edit message"
 */
export function editMessage(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.EditMessageResponse>(`/api/v1/chats/messages/${id}/edit`, req)
}

/**
 * @description "Search messages"
 */
export function searchMessages(q?: string, limit?: number, offset?: number, chat_id?: string) {
	return webapi.get<components.SearchMessagesResponse>(`/api/v1/chats/search`, { q, limit, offset, chat_id })
}

/**
 * @description "Get tool output"
 */
export function getToolOutput(chatId: string, toolCallId: string) {
	return webapi.get<components.GetToolOutputResponse>(`/api/v1/chats/${chatId}/tool-output/${toolCallId}`)
}

/**
 * @description "Get chat"
 */
export function getChat(id: string) {
	return webapi.get<unknown>(`/api/v1/chats/${id}`)
}

/**
 * @description "Update chat"
 */
export function updateChat(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateChatResponse>(`/api/v1/chats/${id}`, req)
}

/**
 * @description "Delete chat"
 */
export function deleteChat(id: string) {
	return webapi.delete<components.DeleteChatResponse>(`/api/v1/chats/${id}`)
}

/**
 * @description "Get chat messages"
 */
export function getChatMessages(id: string, max_chars?: number, before?: string) {
	return webapi.get<components.GetChatMessagesResponse>(`/api/v1/chats/${id}/messages`, { max_chars, before })
}

/**
 * @description "Submit code"
 */
export function submitCode(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/codes`, req)
}

/**
 * @description "Create edge"
 */
export function createEdge(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateEdgeResponse>(`/api/v1/commander/edges`, req)
}

/**
 * @description "Delete edge"
 */
export function deleteEdge(id: string) {
	return webapi.delete<components.DeleteEdgeResponse>(`/api/v1/commander/edges/${id}`)
}

/**
 * @description "Get graph"
 */
export function getGraph() {
	return webapi.get<components.GetGraphResponse>(`/api/v1/commander/graph`)
}

/**
 * @description "Save layout"
 */
export function saveLayout(req: Record<string, unknown> = {}) {
	return webapi.put<components.SaveLayoutResponse>(`/api/v1/commander/layout`, req)
}

/**
 * @description "Create team"
 */
export function createTeam(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateTeamResponse>(`/api/v1/commander/teams`, req)
}

/**
 * @description "Update team"
 */
export function updateTeam(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateTeamResponse>(`/api/v1/commander/teams/${id}`, req)
}

/**
 * @description "Delete team"
 */
export function deleteTeam(id: string) {
	return webapi.delete<components.DeleteTeamResponse>(`/api/v1/commander/teams/${id}`)
}

/**
 * @description "Approve deps"
 */
export function approveDeps(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/deps/approve`, req)
}

/**
 * @description "Get entity config"
 */
export function getEntityConfig(entityType: string, entityId: string) {
	return webapi.get<components.GetEntityConfigResponse>(`/api/v1/entity-config/${entityType}/${entityId}`)
}

/**
 * @description "Update entity config"
 */
export function updateEntityConfig(entityType: string, entityId: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateEntityConfigResponse>(`/api/v1/entity-config/${entityType}/${entityId}`, req)
}

/**
 * @description "Delete entity config"
 */
export function deleteEntityConfig(entityType: string, entityId: string) {
	return webapi.delete<components.DeleteEntityConfigResponse>(`/api/v1/entity-config/${entityType}/${entityId}`)
}

/**
 * @description "List extensions"
 */
export function listExtensions() {
	return webapi.get<components.ListExtensionsResponse>(`/api/v1/extensions`)
}

/**
 * @description "Browse"
 */
export function browse(req: Record<string, unknown> = {}) {
	return webapi.post<components.BrowseResponse>(`/api/v1/files/browse`, req)
}

/**
 * @description "Pick files"
 */
export function pickFiles(req: Record<string, unknown> = {}) {
	return webapi.post<components.PickFilesResponse>(`/api/v1/files/pick`, req)
}

/**
 * @description "Pick folder"
 */
export function pickFolder(req: Record<string, unknown> = {}) {
	return webapi.post<components.PickFolderResponse>(`/api/v1/files/pick-folder`, req)
}

/**
 * @description "Upload file"
 */
export function uploadFile(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/files/upload`, req)
}

/**
 * @description "Serve file"
 */
export function serveFile(path: string) {
	return webapi.get<unknown>(`/api/v1/files/${path}`)
}

/**
 * @description "List integrations"
 */
export function listIntegrations() {
	return webapi.get<components.ListIntegrationsResponse>(`/api/v1/integrations`)
}

/**
 * @description "Create integration"
 */
export function createIntegration(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateIntegrationResponse>(`/api/v1/integrations`, req)
}

/**
 * @description "Oauth callback"
 */
export function oauthCallback() {
	return webapi.get<unknown>(`/api/v1/integrations/oauth/callback`)
}

/**
 * @description "List registry"
 */
export function listRegistry() {
	return webapi.get<components.ListRegistryResponse>(`/api/v1/integrations/registry`)
}

/**
 * @description "List tools"
 */
export function listTools() {
	return webapi.get<components.ListToolsResponse>(`/api/v1/integrations/tools`)
}

/**
 * @description "Get integration"
 */
export function getIntegration(id: string) {
	return webapi.get<unknown>(`/api/v1/integrations/${id}`)
}

/**
 * @description "Update integration"
 */
export function updateIntegration(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/integrations/${id}`, req)
}

/**
 * @description "Delete integration"
 */
export function deleteIntegration(id: string) {
	return webapi.delete<components.DeleteIntegrationResponse>(`/api/v1/integrations/${id}`)
}

/**
 * @description "Connect integration"
 */
export function connectIntegration(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ConnectIntegrationResponse>(`/api/v1/integrations/${id}/connect`, req)
}

/**
 * @description "Get oauth url"
 */
export function getOauthUrl(id: string) {
	return webapi.get<components.GetOauthUrlResponse>(`/api/v1/integrations/${id}/oauth-url`)
}

/**
 * @description "Reauthenticate integration"
 */
export function reauthenticateIntegration(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ReauthenticateIntegrationResponse>(`/api/v1/integrations/${id}/reauthenticate`, req)
}

/**
 * @description "Test integration"
 */
export function testIntegration(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.TestIntegrationResponse>(`/api/v1/integrations/${id}/test`, req)
}

/**
 * @description "Local models status"
 */
export function localModelsStatus() {
	return webapi.get<components.LocalModelsStatusResponse>(`/api/v1/local-models/status`)
}

/**
 * @description "List memories"
 */
export function listMemories(limit?: number, offset?: number, namespace?: string, agent_id?: string) {
	return webapi.get<components.ListMemoriesResponse>(`/api/v1/memories`, { limit, offset, namespace, agent_id })
}

/**
 * @description "Search memories"
 */
export function searchMemories(q?: string, limit?: number, offset?: number) {
	return webapi.get<components.SearchMemoriesResponse>(`/api/v1/memories/search`, { q, limit, offset })
}

/**
 * @description "Get stats"
 */
export function getStats() {
	return webapi.get<components.GetStatsResponse>(`/api/v1/memories/stats`)
}

/**
 * @description "Get memory"
 */
export function getMemory(id: string) {
	return webapi.get<components.GetMemoryResponse>(`/api/v1/memories/${id}`)
}

/**
 * @description "Update memory"
 */
export function updateMemory(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateMemoryResponse>(`/api/v1/memories/${id}`, req)
}

/**
 * @description "Delete memory"
 */
export function deleteMemory(id: string) {
	return webapi.delete<components.DeleteMemoryResponse>(`/api/v1/memories/${id}`)
}

/**
 * @description "List models"
 */
export function listModels() {
	return webapi.get<components.ListModelsResponse>(`/api/v1/models`)
}

/**
 * @description "Update cli provider"
 */
export function updateCliProvider(cliId: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateCliProviderResponse>(`/api/v1/models/cli/${cliId}`, req)
}

/**
 * @description "Update model config"
 */
export function updateModelConfig(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateModelConfigResponse>(`/api/v1/models/config`, req)
}

/**
 * @description "Update task routing"
 */
export function updateTaskRouting(req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateTaskRoutingResponse>(`/api/v1/models/task-routing`, req)
}

/**
 * @description "Update model"
 */
export function updateModel(provider: string, modelId: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateModelResponse>(`/api/v1/models/${provider}/${modelId}`, req)
}

/**
 * @description "Nebo a i account status"
 */
export function neboAIAccountStatus() {
	return webapi.get<components.AccountStatusResponse>(`/api/v1/neboai/account`)
}

/**
 * @description "Nebo a i account disconnect"
 */
export function neboAIAccountDisconnect() {
	return webapi.delete<components.DisconnectResponse>(`/api/v1/neboai/account`)
}

/**
 * @description "Nebo a i billing cancel"
 */
export function neboAIBillingCancel(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboai/billing/cancel`, req)
}

/**
 * @description "Nebo a i billing checkout"
 */
export function neboAIBillingCheckout(req: Record<string, unknown> = {}) {
	return webapi.post<components.NeboAIBillingCheckoutResponse>(`/api/v1/neboai/billing/checkout`, req)
}

/**
 * @description "Nebo a i billing invoices"
 */
export function neboAIBillingInvoices() {
	return webapi.get<components.NeboAIBillingInvoicesResponse>(`/api/v1/neboai/billing/invoices`)
}

/**
 * @description "Nebo a i billing payment methods"
 */
export function neboAIBillingPaymentMethods() {
	return webapi.get<components.NeboAIBillingPaymentMethodsResponse>(`/api/v1/neboai/billing/payment-methods`)
}

/**
 * @description "Nebo a i billing portal"
 */
export function neboAIBillingPortal(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboai/billing/portal`, req)
}

/**
 * @description "Nebo a i billing prices"
 */
export function neboAIBillingPrices() {
	return webapi.get<components.NeboAIBillingPricesResponse>(`/api/v1/neboai/billing/prices`)
}

/**
 * @description "Nebo a i billing setup intent"
 */
export function neboAIBillingSetupIntent(req: Record<string, unknown> = {}) {
	return webapi.post<components.NeboAIBillingSetupIntentResponse>(`/api/v1/neboai/billing/setup-intent`, req)
}

/**
 * @description "Nebo a i billing subscribe"
 */
export function neboAIBillingSubscribe(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboai/billing/subscribe`, req)
}

/**
 * @description "Nebo a i billing subscription"
 */
export function neboAIBillingSubscription() {
	return webapi.get<components.NeboAIBillingSubscriptionResponse>(`/api/v1/neboai/billing/subscription`)
}

/**
 * @description "Nebo a i connect handler"
 */
export function neboAIConnectHandler(req: Record<string, unknown> = {}) {
	return webapi.post<components.NeboAIConnectHandlerResponse>(`/api/v1/neboai/connect`, req)
}

/**
 * @description "Nebo a i janus usage"
 */
export function neboAIJanusUsage() {
	return webapi.get<components.NeboAIJanusUsageResponse>(`/api/v1/neboai/janus/usage`)
}

/**
 * @description "Nebo a i janus usage refresh"
 */
export function neboAIJanusUsageRefresh(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboai/janus/usage/refresh`, req)
}

/**
 * @description "Nebo a i marketplace list subscriptions"
 */
export function neboAIMarketplaceListSubscriptions() {
	return webapi.get<unknown>(`/api/v1/neboai/marketplace/subscriptions`)
}

/**
 * @description "Nebo a i marketplace create subscription"
 */
export function neboAIMarketplaceCreateSubscription(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboai/marketplace/subscriptions`, req)
}

/**
 * @description "Nebo a i marketplace cancel subscription"
 */
export function neboAIMarketplaceCancelSubscription(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/neboai/marketplace/subscriptions/${id}/cancel`, req)
}

/**
 * @description "Nebo a i oauth start"
 */
export function neboAIOauthStart(janus?: string) {
	return webapi.get<components.OAuthStartResponse>(`/api/v1/neboai/oauth/start`, { janus })
}

/**
 * @description "Nebo a i oauth status"
 */
export function neboAIOauthStatus(state?: string) {
	return webapi.get<components.OAuthStatusResponse>(`/api/v1/neboai/oauth/status`, { state })
}

/**
 * @description "Nebo a i open neboai"
 */
export function neboAIOpenNeboai() {
	return webapi.get<components.NeboAIOpenNeboaiResponse>(`/api/v1/neboai/open`)
}

/**
 * @description "Nebo a i force reconnect"
 */
export function neboAIForceReconnect(req: Record<string, unknown> = {}) {
	return webapi.post<components.NeboAIForceReconnectResponse>(`/api/v1/neboai/reconnect`, req)
}

/**
 * @description "Nebo a i referral code"
 */
export function neboAIReferralCode() {
	return webapi.get<unknown>(`/api/v1/neboai/referral-code`)
}

/**
 * @description "Nebo a i bot status"
 */
export function neboAIBotStatus() {
	return webapi.get<components.NeboAIBotStatusResponse>(`/api/v1/neboai/status`)
}

/**
 * @description "List notifications"
 */
export function listNotifications() {
	return webapi.get<components.ListNotificationsResponse>(`/api/v1/notifications`)
}

/**
 * @description "Mark all read"
 */
export function markAllRead(req: Record<string, unknown> = {}) {
	return webapi.put<components.MarkAllReadResponse>(`/api/v1/notifications/read-all`, req)
}

/**
 * @description "Unread count"
 */
export function unreadCount() {
	return webapi.get<components.UnreadCountResponse>(`/api/v1/notifications/unread-count`)
}

/**
 * @description "Delete notification"
 */
export function deleteNotification(id: string) {
	return webapi.delete<components.DeleteNotificationResponse>(`/api/v1/notifications/${id}`)
}

/**
 * @description "Mark read"
 */
export function markRead(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.MarkReadResponse>(`/api/v1/notifications/${id}/read`, req)
}

/**
 * @description "List plugins"
 */
export function listPlugins() {
	return webapi.get<components.ListPluginsResponse>(`/api/v1/plugins`)
}

/**
 * @description "List all plugin events"
 */
export function listAllPluginEvents() {
	return webapi.get<components.ListAllPluginEventsResponse>(`/api/v1/plugins/events`)
}

/**
 * @description "Remove plugin"
 */
export function removePlugin(slug: string) {
	return webapi.delete<components.RemovePluginResponse>(`/api/v1/plugins/${slug}`)
}

/**
 * @description "List plugin accounts"
 */
export function listPluginAccounts(slug: string, agentId: string) {
	return webapi.get<components.ListPluginAccountsResponse>(`/api/v1/plugins/${slug}/accounts`, { agentId })
}

/**
 * @description "Auth login account"
 */
export function authLoginAccount(slug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.AuthLoginAccountResponse>(`/api/v1/plugins/${slug}/accounts/login`, req)
}

/**
 * @description "Auth login"
 */
export function authLogin(slug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.AuthLoginResponse>(`/api/v1/plugins/${slug}/auth/login`, req)
}

/**
 * @description "Auth logout"
 */
export function authLogout(slug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.AuthLogoutResponse>(`/api/v1/plugins/${slug}/auth/logout`, req)
}

/**
 * @description "Auth status"
 */
export function authStatus(slug: string) {
	return webapi.get<components.AuthStatusResponse>(`/api/v1/plugins/${slug}/auth/status`)
}

/**
 * @description "Get plugin config"
 */
export function getPluginConfig(slug: string) {
	return webapi.get<components.GetPluginConfigResponse>(`/api/v1/plugins/${slug}/config`)
}

/**
 * @description "Set plugin config"
 */
export function setPluginConfig(slug: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.SetPluginConfigResponse>(`/api/v1/plugins/${slug}/config`, req)
}

/**
 * @description "List dependents"
 */
export function listDependents(slug: string) {
	return webapi.get<components.ListDependentsResponse>(`/api/v1/plugins/${slug}/dependents`)
}

/**
 * @description "Get diagnostics"
 */
export function getDiagnostics(slug: string) {
	return webapi.get<components.GetDiagnosticsResponse>(`/api/v1/plugins/${slug}/diagnostics`)
}

/**
 * @description "List plugin events"
 */
export function listPluginEvents(slug: string) {
	return webapi.get<components.ListPluginEventsResponse>(`/api/v1/plugins/${slug}/events`)
}

/**
 * @description "Get plugin help"
 */
export function getPluginHelp(slug: string) {
	return webapi.get<components.GetPluginHelpResponse>(`/api/v1/plugins/${slug}/help`)
}

/**
 * @description "Start help chat"
 */
export function startHelpChat(slug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.StartHelpChatResponse>(`/api/v1/plugins/${slug}/help/chat`, req)
}

/**
 * @description "Plugin setup run"
 */
export function pluginSetupRun(slug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.PluginSetupRunResponse>(`/api/v1/plugins/${slug}/setup`, req)
}

/**
 * @description "Toggle plugin"
 */
export function togglePlugin(slug: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.TogglePluginResponse>(`/api/v1/plugins/${slug}/toggle`, req)
}

/**
 * @description "List providers"
 */
export function listProviders() {
	return webapi.get<components.ListProvidersResponse>(`/api/v1/providers`)
}

/**
 * @description "Create provider"
 */
export function createProvider(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/providers`, req)
}

/**
 * @description "Get provider"
 */
export function getProvider(id: string) {
	return webapi.get<unknown>(`/api/v1/providers/${id}`)
}

/**
 * @description "Update provider"
 */
export function updateProvider(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/providers/${id}`, req)
}

/**
 * @description "Delete provider"
 */
export function deleteProvider(id: string) {
	return webapi.delete<components.DeleteProviderResponse>(`/api/v1/providers/${id}`)
}

/**
 * @description "Test provider"
 */
export function testProvider(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.TestProviderResponse>(`/api/v1/providers/${id}/test`, req)
}

/**
 * @description "Active runs handler"
 */
export function activeRunsHandler() {
	return webapi.get<unknown>(`/api/v1/runs/active`)
}

/**
 * @description "Create admin"
 */
export function createAdmin(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateAdminResponse>(`/api/v1/setup/admin`, req)
}

/**
 * @description "Complete"
 */
export function complete(req: Record<string, unknown> = {}) {
	return webapi.post<components.CompleteResponse>(`/api/v1/setup/complete`, req)
}

/**
 * @description "Get personality"
 */
export function getPersonality() {
	return webapi.get<unknown>(`/api/v1/setup/personality`)
}

/**
 * @description "Update personality"
 */
export function updatePersonality(req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/setup/personality`, req)
}

/**
 * @description "Status"
 */
export function status() {
	return webapi.get<components.StatusResponse>(`/api/v1/setup/status`)
}

/**
 * @description "Create skill"
 */
export function createSkill(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateSkillResponse>(`/api/v1/skills`, req)
}

/**
 * @description "Get skill"
 */
export function getSkill(name: string) {
	return webapi.get<components.GetSkillResponse>(`/api/v1/skills/${name}`)
}

/**
 * @description "Update skill"
 */
export function updateSkill(name: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateSkillResponse>(`/api/v1/skills/${name}`, req)
}

/**
 * @description "Delete skill"
 */
export function deleteSkill(name: string) {
	return webapi.delete<components.DeleteSkillResponse>(`/api/v1/skills/${name}`)
}

/**
 * @description "Get skill content"
 */
export function getSkillContent(name: string) {
	return webapi.get<unknown>(`/api/v1/skills/${name}/content`)
}

/**
 * @description "List skill secrets"
 */
export function listSkillSecrets(name: string) {
	return webapi.get<components.ListSkillSecretsResponse>(`/api/v1/skills/${name}/secrets`)
}

/**
 * @description "Set skill secret"
 */
export function setSkillSecret(name: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.SetSkillSecretResponse>(`/api/v1/skills/${name}/secrets`, req)
}

/**
 * @description "Delete skill secret"
 */
export function deleteSkillSecret(name: string, key: string) {
	return webapi.delete<components.DeleteSkillSecretResponse>(`/api/v1/skills/${name}/secrets/${key}`)
}

/**
 * @description "Toggle skill"
 */
export function toggleSkill(name: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ToggleSkillResponse>(`/api/v1/skills/${name}/toggle`, req)
}

/**
 * @description "List store categories"
 */
export function listStoreCategories() {
	return webapi.get<unknown>(`/api/v1/store/categories`)
}

/**
 * @description "List store collections"
 */
export function listStoreCollections() {
	return webapi.get<unknown>(`/api/v1/store/collections`)
}

/**
 * @description "Create store collection"
 */
export function createStoreCollection(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateStoreCollectionResponse>(`/api/v1/store/collections`, req)
}

/**
 * @description "Get store collection"
 */
export function getStoreCollection(id: string) {
	return webapi.get<unknown>(`/api/v1/store/collections/${id}`)
}

/**
 * @description "Update store collection"
 */
export function updateStoreCollection(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateStoreCollectionResponse>(`/api/v1/store/collections/${id}`, req)
}

/**
 * @description "Delete store collection"
 */
export function deleteStoreCollection(id: string) {
	return webapi.delete<components.DeleteStoreCollectionResponse>(`/api/v1/store/collections/${id}`)
}

/**
 * @description "Add collection item"
 */
export function addCollectionItem(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.AddCollectionItemResponse>(`/api/v1/store/collections/${id}/items`, req)
}

/**
 * @description "Remove collection item"
 */
export function removeCollectionItem(id: string, itemId: string) {
	return webapi.delete<components.RemoveCollectionItemResponse>(`/api/v1/store/collections/${id}/items/${itemId}`)
}

/**
 * @description "List store featured"
 */
export function listStoreFeatured(q?: string, category?: string, page?: number, pageSize?: number, type?: string) {
	return webapi.get<unknown>(`/api/v1/store/featured`, { q, category, page, pageSize, type })
}

/**
 * @description "List store orgs"
 */
export function listStoreOrgs() {
	return webapi.get<components.ListStoreOrgsResponse>(`/api/v1/store/orgs`)
}

/**
 * @description "List store products"
 */
export function listStoreProducts(q?: string, category?: string, page?: number, pageSize?: number, type?: string) {
	return webapi.get<unknown>(`/api/v1/store/products`, { q, category, page, pageSize, type })
}

/**
 * @description "List store products top"
 */
export function listStoreProductsTop(q?: string, category?: string, page?: number, pageSize?: number, type?: string) {
	return webapi.get<unknown>(`/api/v1/store/products/top`, { q, category, page, pageSize, type })
}

/**
 * @description "Get store product"
 */
export function getStoreProduct(id: string) {
	return webapi.get<unknown>(`/api/v1/store/products/${id}`)
}

/**
 * @description "Get store product feedback"
 */
export function getStoreProductFeedback(id: string, q?: string, category?: string, page?: number, pageSize?: number, type?: string) {
	return webapi.get<components.GetStoreProductFeedbackResponse>(`/api/v1/store/products/${id}/feedback`, { q, category, page, pageSize, type })
}

/**
 * @description "Submit store product feedback"
 */
export function submitStoreProductFeedback(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/store/products/${id}/feedback`, req)
}

/**
 * @description "Install store product"
 */
export function installStoreProduct(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.InstallStoreProductResponse>(`/api/v1/store/products/${id}/install`, req)
}

/**
 * @description "Uninstall store product"
 */
export function uninstallStoreProduct(id: string) {
	return webapi.delete<components.UninstallStoreProductResponse>(`/api/v1/store/products/${id}/install`)
}

/**
 * @description "Get store product media"
 */
export function getStoreProductMedia(id: string) {
	return webapi.get<components.GetStoreProductMediaResponse>(`/api/v1/store/products/${id}/media`)
}

/**
 * @description "Get store product reviews"
 */
export function getStoreProductReviews(id: string, q?: string, category?: string, page?: number, pageSize?: number, type?: string) {
	return webapi.get<unknown>(`/api/v1/store/products/${id}/reviews`, { q, category, page, pageSize, type })
}

/**
 * @description "Submit store product review"
 */
export function submitStoreProductReview(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/store/products/${id}/reviews`, req)
}

/**
 * @description "Get store product similar"
 */
export function getStoreProductSimilar(id: string) {
	return webapi.get<unknown>(`/api/v1/store/products/${id}/similar`)
}

/**
 * @description "Get store screenshots"
 */
export function getStoreScreenshots(type: string) {
	return webapi.get<unknown>(`/api/v1/store/screenshots/${type}`)
}

/**
 * @description "List tasks"
 */
export function listTasks(limit?: number, offset?: number) {
	return webapi.get<components.ListTasksResponse>(`/api/v1/tasks`, { limit, offset })
}

/**
 * @description "Create task"
 */
export function createTask(req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/tasks`, req)
}

/**
 * @description "Get task"
 */
export function getTask(name: string) {
	return webapi.get<unknown>(`/api/v1/tasks/${name}`)
}

/**
 * @description "Update task"
 */
export function updateTask(name: string, req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/tasks/${name}`, req)
}

/**
 * @description "Delete task"
 */
export function deleteTask(name: string) {
	return webapi.delete<components.DeleteTaskResponse>(`/api/v1/tasks/${name}`)
}

/**
 * @description "List task history"
 */
export function listTaskHistory(name: string, limit?: number, offset?: number) {
	return webapi.get<components.ListTaskHistoryResponse>(`/api/v1/tasks/${name}/history`, { limit, offset })
}

/**
 * @description "Run task"
 */
export function runTask(name: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.RunTaskResponse>(`/api/v1/tasks/${name}/run`, req)
}

/**
 * @description "Toggle task"
 */
export function toggleTask(name: string, req: Record<string, unknown> = {}) {
	return webapi.post<unknown>(`/api/v1/tasks/${name}/toggle`, req)
}

/**
 * @description "Update apply"
 */
export function updateApply(req: Record<string, unknown> = {}) {
	return webapi.post<components.UpdateApplyResponse>(`/api/v1/update/apply`, req)
}

/**
 * @description "Update check"
 */
export function updateCheck() {
	return webapi.get<unknown>(`/api/v1/update/check`)
}

/**
 * @description "User get current user"
 */
export function userGetCurrentUser() {
	return webapi.get<components.UserGetCurrentUserResponse>(`/api/v1/user/me`)
}

/**
 * @description "User update current user"
 */
export function userUpdateCurrentUser(req: Record<string, unknown> = {}) {
	return webapi.put<components.UserUpdateCurrentUserResponse>(`/api/v1/user/me`, req)
}

/**
 * @description "User delete account"
 */
export function userDeleteAccount() {
	return webapi.delete<components.UserDeleteAccountResponse>(`/api/v1/user/me`)
}

/**
 * @description "User accept terms"
 */
export function userAcceptTerms(req: Record<string, unknown> = {}) {
	return webapi.post<components.UserAcceptTermsResponse>(`/api/v1/user/me/accept-terms`, req)
}

/**
 * @description "User update approved commands"
 */
export function userUpdateApprovedCommands(req: Record<string, unknown> = {}) {
	return webapi.put<components.UserUpdateApprovedCommandsResponse>(`/api/v1/user/me/approved-commands`, req)
}

/**
 * @description "User change password"
 */
export function userChangePassword(req: Record<string, unknown> = {}) {
	return webapi.post<components.UserChangePasswordResponse>(`/api/v1/user/me/change-password`, req)
}

/**
 * @description "User get permissions"
 */
export function userGetPermissions() {
	return webapi.get<components.UserGetPermissionsResponse>(`/api/v1/user/me/permissions`)
}

/**
 * @description "User update permissions"
 */
export function userUpdatePermissions(req: Record<string, unknown> = {}) {
	return webapi.put<components.UserUpdatePermissionsResponse>(`/api/v1/user/me/permissions`, req)
}

/**
 * @description "User get preferences"
 */
export function userGetPreferences() {
	return webapi.get<components.UserGetPreferencesResponse>(`/api/v1/user/me/preferences`)
}

/**
 * @description "User update preferences"
 */
export function userUpdatePreferences(req: Record<string, unknown> = {}) {
	return webapi.put<unknown>(`/api/v1/user/me/preferences`, req)
}

/**
 * @description "User get profile"
 */
export function userGetProfile() {
	return webapi.get<components.UserGetProfileResponse>(`/api/v1/user/me/profile`)
}

/**
 * @description "User update profile"
 */
export function userUpdateProfile(req: Record<string, unknown> = {}) {
	return webapi.put<components.UserUpdateProfileResponse>(`/api/v1/user/me/profile`, req)
}

/**
 * @description "Transcribe"
 */
export function transcribe(req: Record<string, unknown> = {}) {
	return webapi.post<components.TranscribeResponse>(`/api/v1/voice/transcribe`, req)
}

/**
 * @description "Tts"
 */
export function tts(req: Record<string, unknown> = {}) {
	return webapi.post<components.TtsResponse>(`/api/v1/voice/tts`, req)
}

/**
 * @description "List workflows"
 */
export function listWorkflows(limit?: number, offset?: number) {
	return webapi.get<components.ListWorkflowsResponse>(`/api/v1/workflows`, { limit, offset })
}

/**
 * @description "Create workflow"
 */
export function createWorkflow(req: Record<string, unknown> = {}) {
	return webapi.post<components.CreateWorkflowResponse>(`/api/v1/workflows`, req)
}

/**
 * @description "Get workflow"
 */
export function getWorkflow(id: string) {
	return webapi.get<components.GetWorkflowResponse>(`/api/v1/workflows/${id}`)
}

/**
 * @description "Update workflow"
 */
export function updateWorkflow(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateWorkflowResponse>(`/api/v1/workflows/${id}`, req)
}

/**
 * @description "Delete workflow"
 */
export function deleteWorkflow(id: string) {
	return webapi.delete<components.DeleteWorkflowResponse>(`/api/v1/workflows/${id}`)
}

/**
 * @description "List bindings"
 */
export function listBindings(id: string) {
	return webapi.get<components.ListBindingsResponse>(`/api/v1/workflows/${id}/bindings`)
}

/**
 * @description "Update bindings"
 */
export function updateBindings(id: string, req: Record<string, unknown> = {}) {
	return webapi.put<components.UpdateBindingsResponse>(`/api/v1/workflows/${id}/bindings`, req)
}

/**
 * @description "Run workflow"
 */
export function runWorkflow(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.RunWorkflowResponse>(`/api/v1/workflows/${id}/run`, req)
}

/**
 * @description "List runs"
 */
export function listRuns(id: string, limit?: number, offset?: number) {
	return webapi.get<components.ListRunsResponse>(`/api/v1/workflows/${id}/runs`, { limit, offset })
}

/**
 * @description "Get run"
 */
export function getRun(id: string, runId: string) {
	return webapi.get<components.GetRunResponse>(`/api/v1/workflows/${id}/runs/${runId}`)
}

/**
 * @description "Cancel run"
 */
export function cancelRun(id: string, runId: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.CancelRunResponse>(`/api/v1/workflows/${id}/runs/${runId}/cancel`, req)
}

/**
 * @description "Toggle workflow"
 */
export function toggleWorkflow(id: string, req: Record<string, unknown> = {}) {
	return webapi.post<components.ToggleWorkflowResponse>(`/api/v1/workflows/${id}/toggle`, req)
}

