// Code generated by cmd/genapi. DO NOT EDIT.

export interface AcceptTermsResponse {
	acceptedAt: string
}

export interface AdvisorItem {
	id: number
	name: string
	role: string
	description: string
	priority: number
	enabled: boolean
	memoryAccess: boolean
	persona: string
	timeoutSeconds: number
}

export interface AgentConnectRequest {
	agentId: string
}

export interface AgentConnectResponse {
	connected: boolean
	agentId: string
}

export interface AgentInfo {
	agentId: string
	connected: boolean
	createdAt: string
}

export interface AgentProfileResponse {
	name: string
	personalityPreset: string
	customPersonality?: string
	voiceStyle: string
	responseLength: string
	emojiUsage: string
	formality: string
	proactivity: string
	emoji?: string
	creature?: string
	vibe?: string
	avatar?: string
	agentRules?: string
	toolNotes?: string
	createdAt: string
	updatedAt: string
}

export interface AgentSession {
	id: string
	name?: string
	summary?: string
	messageCount: number
	createdAt: string
	updatedAt: string
}

export interface AgentSettings {
	autonomousMode: boolean
	autoApproveRead: boolean
	autoApproveWrite: boolean
	autoApproveBash: boolean
	heartbeatIntervalMinutes: number
	commEnabled: boolean
	commPlugin?: string
	developerMode: boolean
}

export interface AgentStatusRequest {
}

export interface AgentStatusResponse {
	agentId: string
	connected: boolean
	uptime: number
}

export interface AuthConfigResponse {
	googleEnabled: boolean
	githubEnabled: boolean
}

export interface AuthProfile {
	id: string
	name: string
	provider: string // anthropic, openai, google, ollama
	model?: string
	baseUrl?: string
	priority: number
	isActive: boolean
	createdAt: string
	updatedAt: string
}

export interface BrowseDirectoryResponse {
	path: string
}

export interface CLIAvailability {
	claude: boolean
	codex: boolean
	gemini: boolean
}

export interface CLIStatus {
	installed: boolean
	authenticated: boolean
	version?: string
}

export interface CLIStatusMap {
	claude: CLIStatus
	codex: CLIStatus
	gemini: CLIStatus
}

export interface ChangePasswordRequest {
	currentPassword: string
	newPassword: string
}

export interface Chat {
	id: string
	title: string
	createdAt: string
	updatedAt: string
}

export interface ChatMessage {
	id: string
	chatId: string
	role: string
	content: string
	metadata?: string
	createdAt: string
}

export interface CompleteSetupResponse {
	success: boolean
}

export interface CreateAdminRequest {
	email: string
	password: string
	name: string
}

export interface CreateAdminResponse {
	token: string
	refreshToken: string
	expiresAt: number
	user: User
}

export interface CreateAdvisorRequest {
	name: string
	role: string
	description: string
	priority: number
	memoryAccess: boolean
	persona: string
	timeoutSeconds: number
}

export interface CreateAuthProfileRequest {
	name: string
	provider: string
	apiKey: string
	model?: string
	baseUrl?: string
	priority?: number
}

export interface CreateAuthProfileResponse {
	profile: AuthProfile
}

export interface CreateChatRequest {
	title?: string
}

export interface CreateChatResponse {
	chat: Chat
}

export interface CreateMCPIntegrationRequest {
	name?: string
	serverType?: string
	serverUrl: string
	authType: string
	apiKey?: string
}

export interface CreateMCPIntegrationResponse {
	integration: MCPIntegration
}

export interface CreateTaskRequest {
	name: string
	schedule: string
	command?: string
	taskType: string
	message?: string
	deliver?: string
	enabled: boolean
}

export interface CreateTaskResponse {
	task: TaskItem
}

export interface DayInfo {
	day: string
	messageCount: number
}

export interface DeleteAccountRequest {
	password: string
}

export interface DeleteAdvisorRequest {
}

export interface DeleteAdvisorResponse {
	success: boolean
}

export interface DeleteAgentSessionRequest {
}

export interface DeleteAuthProfileRequest {
}

export interface DeleteChatRequest {
}

export interface DeleteMCPIntegrationRequest {
}

export interface DeleteMemoryRequest {
}

export interface DeleteNotificationRequest {
}

export interface DeleteTaskRequest {
}

export interface DevAppItem {
	appId: string
	name: string
	version: string
	path: string
	running: boolean
	loadedAt: number
}

export interface DisconnectMCPIntegrationRequest {
}

export interface DisconnectMCPIntegrationResponse {
	success: boolean
	message: string
}

export interface DisconnectOAuthRequest {
}

export interface EmailVerificationRequest {
	token: string
}

export interface Empty {
}

export interface ExtensionChannel {
	id: string
	path: string
}

export interface ExtensionSkill {
	name: string
	description: string
	version: string
	tags: Array<string>
	dependencies: Array<string>
	tools: Array<string>
	priority: number
	enabled: boolean
	filePath: string
}

export interface ExtensionTool {
	name: string
	description: string
	schema?: string
	requiresApproval: boolean
	isPlugin: boolean
	path?: string
}

export interface ForgotPasswordRequest {
	email: string
}

export interface GetAdvisorRequest {
}

export interface GetAdvisorResponse {
	advisor: AdvisorItem
}

export interface GetAgentSessionMessagesResponse {
	messages: Array<SessionMessage>
	total: number
}

export interface GetAgentSessionRequest {
}

export interface GetAgentSettingsResponse {
	settings: AgentSettings
}

export interface GetAuthProfileRequest {
}

export interface GetAuthProfileResponse {
	profile: AuthProfile
}

export interface GetChatRequest {
}

export interface GetChatResponse {
	chat: Chat
	messages: Array<ChatMessage>
	totalMessages: number // Total messages in chat (may be more than returned)
}

export interface GetHeartbeatResponse {
	content: string
}

export interface GetHistoryByDayRequest {
}

export interface GetHistoryByDayResponse {
	day: string
	messages: Array<ChatMessage>
}

export interface GetMCPIntegrationRequest {
}

export interface GetMCPIntegrationResponse {
	integration: MCPIntegration
}

export interface GetMCPOAuthURLRequest {
}

export interface GetMCPOAuthURLResponse {
	authUrl: string
}

export interface GetMemoryRequest {
}

export interface GetMemoryResponse {
	memory: MemoryItem
}

export interface GetOAuthUrlRequest {
}

export interface GetOAuthUrlRequestParams {
	redirectUrl?: string
}

export interface GetOAuthUrlResponse {
	url: string
	state: string
}

export interface GetPersonalityResponse {
	content: string
}

export interface GetPluginRequest {
}

export interface GetPluginResponse {
	plugin: PluginItem
}

export interface GetPreferencesResponse {
	preferences: UserPreferences
}

export interface GetSkillRequest {
}

export interface GetSkillResponse {
	skill: ExtensionSkill
}

export interface GetStoreAppResponse {
	app: StoreAppDetail
}

export interface GetStoreAppReviewsResponse {
	reviews: Array<StoreReview>
	totalCount: number
	average: number
	distribution: Array<number>
}

export interface GetTaskRequest {
}

export interface GetTaskResponse {
	task: TaskItem
}

export interface GetToolPermissionsResponse {
	permissions: { [key: string]: boolean }
}

export interface GetUnreadCountResponse {
	count: number
}

export interface GetUserProfileResponse {
	profile: UserProfile
}

export interface GetUserResponse {
	user: User
}

export interface HealthResponse {
	status: string
	version: string
	timestamp: string
}

export interface InstallStoreAppResponse {
	pluginId: string
	message: string
}

export interface InstallStoreSkillResponse {
	pluginId: string
	message: string
}

export interface ListAdvisorsResponse {
	advisors: Array<AdvisorItem>
}

export interface ListAgentSessionsResponse {
	sessions: Array<AgentSession>
	total: number
}

export interface ListAgentsRequest {
}

export interface ListAgentsResponse {
	agents: Array<AgentInfo>
	total: number
}

export interface ListAuthProfilesResponse {
	profiles: Array<AuthProfile>
}

export interface ListChatDaysRequest {
}

export interface ListChatDaysRequestParams {
	page?: number
	pageSize?: number
}

export interface ListChatDaysResponse {
	days: Array<DayInfo>
}

export interface ListChatsRequest {
}

export interface ListChatsRequestParams {
	page?: number
	pageSize?: number
}

export interface ListChatsResponse {
	chats: Array<Chat>
	total: number
}

export interface ListDevAppsResponse {
	apps: Array<DevAppItem>
}

export interface ListExtensionsResponse {
	tools: Array<ExtensionTool>
	skills: Array<ExtensionSkill>
	channels: Array<ExtensionChannel>
}

export interface ListMCPIntegrationsResponse {
	integrations: Array<MCPIntegration>
}

export interface ListMCPServerRegistryResponse {
	servers: Array<MCPServerInfo>
}

export interface ListMCPToolsResponse {
	tools: Array<MCPToolInfo>
}

export interface ListMemoriesRequest {
}

export interface ListMemoriesRequestParams {
	namespace?: string
	page?: number
	pageSize?: number
}

export interface ListMemoriesResponse {
	memories: Array<MemoryItem>
	total: number
}

export interface ListModelsResponse {
	models: { [key: string]: Array<ModelInfo> }
	taskRouting?: TaskRouting
	aliases?: Array<ModelAlias>
	availableCLIs?: CLIAvailability
	cliStatuses?: CLIStatusMap
}

export interface ListNotificationsRequest {
}

export interface ListNotificationsRequestParams {
	page?: number
	pageSize?: number
	unread?: boolean
}

export interface ListNotificationsResponse {
	notifications: Array<Notification>
	unreadCount: number
	totalCount: number
}

export interface ListOAuthProvidersResponse {
	providers: Array<OAuthProvider>
}

export interface ListPersonalityPresetsResponse {
	presets: Array<PersonalityPreset>
}

export interface ListPluginsResponse {
	plugins: Array<PluginItem>
}

export interface ListStoreAppsResponse {
	apps: Array<StoreApp>
	totalCount: number
	page: number
	pageSize: number
}

export interface ListStoreSkillsResponse {
	skills: Array<StoreSkill>
	totalCount: number
	page: number
	pageSize: number
}

export interface ListTaskHistoryRequest {
}

export interface ListTaskHistoryRequestParams {
	page?: number
	pageSize?: number
}

export interface ListTaskHistoryResponse {
	history: Array<TaskHistoryItem>
	total: number
}

export interface ListTasksRequest {
}

export interface ListTasksRequestParams {
	page?: number
	pageSize?: number
}

export interface ListTasksResponse {
	tasks: Array<TaskItem>
	total: number
}

export interface ListToolsResponse {
	tools: Array<ToolDefinitionItem>
}

export interface ListUIAppsResponse {
	apps: Array<UIAppInfo>
}

export interface LoginRequest {
	email: string
	password: string
}

export interface LoginResponse {
	token: string
	refreshToken: string
	expiresAt: number
}

export interface MCPIntegration {
	id: string
	name: string
	serverType: string
	serverUrl?: string
	authType: string
	isEnabled: boolean
	connectionStatus: string
	toolCount: number
	lastConnectedAt?: string
	lastError?: string
	createdAt: string
	updatedAt: string
}

export interface MCPServerInfo {
	id: string
	name: string
	description?: string
	icon?: string
	authType: string
	apiKeyUrl?: string
	apiKeyPlaceholder?: string
	isBuiltin: boolean
	displayOrder: number
}

export interface MCPToolInfo {
	name: string
	description?: string
	serverType: string
}

export interface MarkNotificationReadRequest {
}

export interface MemoryItem {
	id: number
	namespace: string
	key: string
	value: string
	tags?: Array<string>
	accessCount: number
	createdAt: string
	updatedAt: string
	accessedAt?: string
}

export interface MemoryStatsResponse {
	totalCount: number
	layerCounts: { [key: string]: number }
	namespaces: Array<string>
}

export interface MessageResponse {
	message: string
}

export interface ModelAlias {
	alias: string
	modelId: string
}

export interface ModelInfo {
	id: string
	displayName: string
	contextWindow?: number
	pricing?: ModelPricing
	capabilities?: Array<string>
	kind?: Array<string>
	preferred?: boolean
	isActive: boolean
}

export interface ModelPricing {
	input?: number
	output?: number
	cachedInput?: number
}

export interface NeboLoopAccountStatusResponse {
	connected: boolean
	ownerId?: string
	email?: string
	displayName?: string
}

export interface NeboLoopConnectRequest {
	code: string
	name: string
	purpose?: string
}

export interface NeboLoopConnectResponse {
	botId: string
	botName: string
	botSlug: string
	message: string
}

export interface NeboLoopDisconnectResponse {
	disconnected: boolean
}

export interface NeboLoopLoginRequest {
	email: string
	password: string
}

export interface NeboLoopLoginResponse {
	id: string
	email: string
	displayName: string
	token: string
}

export interface NeboLoopRegisterRequest {
	email: string
	displayName: string
	password: string
}

export interface NeboLoopRegisterResponse {
	id: string
	email: string
	displayName: string
	token: string
}

export interface NeboLoopStatusResponse {
	connected: boolean
	botId?: string
	botName?: string
	apiServer?: string
}

export interface Notification {
	id: string
	type: string
	title: string
	body?: string
	actionUrl?: string
	icon?: string
	readAt?: string
	createdAt: string
}

export interface OAuthLoginRequest {
	code: string
	state?: string
}

export interface OAuthLoginResponse {
	token: string
	refreshToken: string
	expiresAt: number
	isNewUser: boolean
}

export interface OAuthProvider {
	name: string
	connected: boolean
	email?: string
}

export interface OpenDevWindowResponse {
	opened: boolean
}

export interface PersonalityPreset {
	id: string
	name: string
	description?: string
	systemPrompt: string
	icon?: string
	displayOrder: number
}

export interface PluginItem {
	id: string
	name: string
	pluginType: string
	displayName: string
	description: string
	icon: string
	version: string
	isEnabled: boolean
	isInstalled: boolean
	settingsManifest: any
	connectionStatus: string
	lastConnectedAt?: string
	lastError?: string
	settings?: { [key: string]: string }
	capabilities?: Array<string>
	permissions?: Array<string>
	createdAt: string
	updatedAt: string
}

// ProjectContext provides full project state for the Dev Assistant system prompt.
export interface ProjectContext {
	path: string
	appId?: string
	name?: string
	version?: string
	files: Array<string>
	manifestRaw?: string
	hasMakefile: boolean
	binaryPath?: string
	running: boolean
	recentLogs?: string
}

export interface RefreshTokenRequest {
	refreshToken: string
}

export interface RefreshTokenResponse {
	token: string
	refreshToken: string
	expiresAt: number
}

export interface RegisterRequest {
	email: string
	password: string
	name: string
}

export interface ResendVerificationRequest {
	email: string
}

export interface ResetPasswordRequest {
	token: string
	newPassword: string
}

export interface RunTaskRequest {
}

export interface RunTaskResponse {
	success: boolean
	output?: string
	error?: string
}

export interface SearchChatMessagesRequest {
}

export interface SearchChatMessagesRequestParams {
	query: string
	page?: number
	pageSize?: number
}

export interface SearchChatMessagesResponse {
	messages: Array<ChatMessage>
	total: number
}

export interface SearchMemoriesRequest {
}

export interface SearchMemoriesRequestParams {
	query: string
	page?: number
	pageSize?: number
}

export interface SearchMemoriesResponse {
	memories: Array<MemoryItem>
	total: number
}

export interface SendMessageRequest {
	chatId: string
	content: string
	role?: string
}

export interface SendMessageResponse {
	message: ChatMessage
	chatId: string
}

export interface SendUIEventRequest {
	view_id: string
	block_id: string
	action: string
	value: string
}

export interface SendUIEventResponse {
	view?: UIView
	error?: string
	toast?: string
}

export interface SessionMessage {
	id: number
	role: string
	content?: string
	createdAt: string
}

export interface SetupStatusResponse {
	setupRequired: boolean
	hasAdmin: boolean
	setupComplete: boolean
}

export interface SideloadRequest {
	path: string
}

export interface SideloadResponse {
	appId: string
	name: string
	version: string
	path: string
}

export interface SimpleAgentStatusResponse {
	connected: boolean
	agentId?: string
	uptime?: number
}

export interface StoreApp {
	id: string
	name: string
	slug: string
	description: string
	icon: string
	category: string
	version: string
	author: StoreAuthor
	installCount: number
	rating: number
	reviewCount: number
	isInstalled: boolean
	status: string
}

export interface StoreAppDetail extends StoreApp {
	ageRating?: string
	platforms?: Array<string>
	size?: { [key: string]: number }
	language?: string
	screenshots?: Array<string>
	changelog?: Array<StoreChangelog>
	websiteUrl?: string
	privacyUrl?: string
	supportUrl?: string
}

export interface StoreAuthor {
	id: string
	name: string
	verified: boolean
}

export interface StoreChangelog {
	version: string
	date: string
	notes: string
}

export interface StoreReview {
	id: string
	userName: string
	rating: number
	title: string
	body: string
	createdAt: string
	helpful: number
}

export interface StoreSkill {
	id: string
	name: string
	slug: string
	description: string
	icon: string
	category: string
	version: string
	author: StoreAuthor
	installCount: number
	rating: number
	reviewCount: number
	isInstalled: boolean
	status: string
}

export interface SystemInfoResponse {
	os: string
	arch: string
	hostname: string
	homeDir: string
	username: string
}

export interface TaskHistoryItem {
	id: number
	jobId: number
	startedAt: string
	finishedAt?: string
	success: boolean
	output?: string
	error?: string
}

export interface TaskItem {
	id: number
	name: string
	schedule: string
	command?: string
	taskType: string
	message?: string
	deliver?: string
	enabled: boolean
	lastRun?: string
	runCount: number
	lastError?: string
	createdAt: string
}

export interface TaskRouting {
	vision?: string
	audio?: string
	reasoning?: string
	code?: string
	general?: string
	fallbacks?: { [key: string]: Array<string> }
}

export interface TestAuthProfileRequest {
}

export interface TestAuthProfileResponse {
	success: boolean
	message: string
	model?: string
}

export interface TestMCPIntegrationRequest {
}

export interface TestMCPIntegrationResponse {
	success: boolean
	message: string
	tool_count?: number
}

export interface TogglePluginRequest {
	isEnabled: boolean
}

export interface ToggleSkillRequest {
}

export interface ToggleSkillResponse {
	name: string
	enabled: boolean
}

export interface ToggleTaskRequest {
}

export interface ToggleTaskResponse {
	enabled: boolean
}

export interface ToolDefinitionItem {
	name: string
	description: string
	schema: any
}

export interface ToolExecuteRequest {
	tool: string
	input: any
}

export interface ToolExecuteResponse {
	content: string
	isError: boolean
}

export interface ToolPermissions {
	permissions: { [key: string]: boolean }
}

export interface UIAppInfo {
	id: string
	name: string
	version: string
}

export interface UIBlock {
	block_id: string
	type: string
	text?: string
	value?: string
	placeholder?: string
	hint?: string
	variant?: string
	src?: string
	alt?: string
	disabled?: boolean
	options?: Array<UISelectOption>
	style?: string
}

export interface UISelectOption {
	label: string
	value: string
}

export interface UIView {
	view_id: string
	title: string
	blocks: Array<UIBlock>
}

export interface UpdateAdvisorRequest {
	role?: string
	description?: string
	priority?: number
	enabled?: boolean
	memoryAccess?: boolean
	persona?: string
	timeoutSeconds?: number
}

export interface UpdateAgentProfileRequest {
	name?: string
	personalityPreset?: string
	customPersonality?: string
	voiceStyle?: string
	responseLength?: string
	emojiUsage?: string
	formality?: string
	proactivity?: string
	emoji?: string
	creature?: string
	vibe?: string
	avatar?: string
	agentRules?: string
	toolNotes?: string
}

export interface UpdateAgentSettingsRequest {
	autonomousMode: boolean
	autoApproveRead: boolean
	autoApproveWrite: boolean
	autoApproveBash: boolean
	heartbeatIntervalMinutes: number
	commEnabled: boolean
	commPlugin?: string
	developerMode: boolean
}

export interface UpdateAuthProfileRequest {
	name?: string
	apiKey?: string
	model?: string
	baseUrl?: string
	priority?: number
	isActive?: boolean
}

export interface UpdateChatRequest {
	title: string
}

export interface UpdateHeartbeatRequest {
	content: string
}

export interface UpdateHeartbeatResponse {
	success: boolean
}

export interface UpdateMCPIntegrationRequest {
	name?: string
	serverUrl?: string
	isEnabled?: boolean
	apiKey?: string
}

export interface UpdateMCPIntegrationResponse {
	integration: MCPIntegration
}

export interface UpdateMemoryRequest {
	value?: string
	tags?: Array<string>
}

export interface UpdateModelConfigRequest {
	primary?: string
	fallbacks?: Array<string>
}

export interface UpdateModelConfigResponse {
	success: boolean
	primary: string
}

export interface UpdateModelRequest {
	active?: boolean
	kind?: Array<string>
	preferred?: boolean
}

export interface UpdatePersonalityRequest {
	content: string
}

export interface UpdatePersonalityResponse {
	success: boolean
}

export interface UpdatePluginSettingsRequest {
	settings: { [key: string]: string }
	secrets?: { [key: string]: boolean }
}

export interface UpdatePluginSettingsResponse {
	plugin: PluginItem
}

export interface UpdatePreferencesRequest {
	emailNotifications?: boolean
	marketingEmails?: boolean
	timezone?: string
	language?: string
	theme?: string
}

export interface UpdateTaskRequest {
	name?: string
	schedule?: string
	command?: string
	taskType?: string
	message?: string
	deliver?: string
}

export interface UpdateTaskRoutingRequest {
	vision?: string
	audio?: string
	reasoning?: string
	code?: string
	general?: string
	fallbacks?: { [key: string]: Array<string> }
	aliases?: Array<ModelAlias>
}

export interface UpdateToolPermissionsRequest {
	permissions: { [key: string]: boolean }
}

export interface UpdateToolPermissionsResponse {
	permissions: { [key: string]: boolean }
}

export interface UpdateUserProfileRequest {
	displayName?: string
	bio?: string
	location?: string
	timezone?: string
	occupation?: string
	interests?: Array<string>
	communicationStyle?: string
	goals?: string
	context?: string
	onboardingCompleted?: boolean
}

export interface UpdateUserProfileResponse {
	profile: UserProfile
}

export interface UpdateUserRequest {
	name?: string
	avatarUrl?: string
}

export interface User {
	id: string
	email: string
	name: string
	avatarUrl?: string
	emailVerified: boolean
	createdAt: string
	updatedAt: string
}

export interface UserPreferences {
	emailNotifications: boolean
	marketingEmails: boolean
	timezone: string
	language: string
	theme: string
}

export interface UserProfile {
	userId: string
	displayName?: string
	bio?: string
	location?: string
	timezone?: string
	occupation?: string
	interests?: Array<string>
	communicationStyle?: string
	goals?: string
	context?: string
	onboardingCompleted: boolean
	onboardingStep?: string
	toolPermissions?: { [key: string]: boolean }
	termsAcceptedAt?: string
	createdAt: string
	updatedAt: string
}

