// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type AgentConnectRequest struct {
	AgentId string `json:"agentId"`
}

type AgentConnectResponse struct {
	Connected bool   `json:"connected"`
	AgentId   string `json:"agentId"`
}

type AgentInfo struct {
	AgentId   string `json:"agentId"`
	Connected bool   `json:"connected"`
	CreatedAt string `json:"createdAt"`
}

type AgentSession struct {
	Id           string `json:"id"`
	Name         string `json:"name,omitempty"`
	Summary      string `json:"summary,omitempty"`
	MessageCount int    `json:"messageCount"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type AgentSettings struct {
	AutonomousMode   bool `json:"autonomousMode"`
	AutoApproveRead  bool `json:"autoApproveRead"`
	AutoApproveWrite bool `json:"autoApproveWrite"`
	AutoApproveBash  bool `json:"autoApproveBash"`
}

type AgentStatusRequest struct {
	AgentId string `path:"agentId"`
}

type AgentStatusResponse struct {
	AgentId   string `json:"agentId"`
	Connected bool   `json:"connected"`
	Uptime    int64  `json:"uptime"`
}

type AuthConfigResponse struct {
	GoogleEnabled bool `json:"googleEnabled"`
	GitHubEnabled bool `json:"githubEnabled"`
}

type AuthProfile struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"` // anthropic, openai, google, ollama
	Model     string `json:"model,omitempty"`
	BaseUrl   string `json:"baseUrl,omitempty"`
	Priority  int    `json:"priority"`
	IsActive  bool   `json:"isActive"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type CLIAvailability struct {
	Claude bool `json:"claude"`
	Codex  bool `json:"codex"`
	Gemini bool `json:"gemini"`
}

type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type Chat struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type ChatMessage struct {
	Id        string `json:"id"`
	ChatId    string `json:"chatId"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	Metadata  string `json:"metadata,omitempty"`
	CreatedAt string `json:"createdAt"`
}

type CompleteSetupResponse struct {
	Success bool `json:"success"`
}

type CreateAdminRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type CreateAdminResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
	User         User   `json:"user"`
}

type CreateAuthProfileRequest struct {
	Name     string `json:"name"`
	Provider string `json:"provider"`
	ApiKey   string `json:"apiKey"`
	Model    string `json:"model,optional"`
	BaseUrl  string `json:"baseUrl,optional"`
	Priority int    `json:"priority,optional"`
}

type CreateAuthProfileResponse struct {
	Profile AuthProfile `json:"profile"`
}

type CreateChatRequest struct {
	Title string `json:"title,optional"`
}

type CreateChatResponse struct {
	Chat Chat `json:"chat"`
}

type DayInfo struct {
	Day          string `json:"day"`
	MessageCount int    `json:"messageCount"`
}

type DeleteAccountRequest struct {
	Password string `json:"password"`
}

type DeleteAgentSessionRequest struct {
	Id string `path:"id"`
}

type DeleteAuthProfileRequest struct {
	Id string `path:"id"`
}

type DeleteChatRequest struct {
	Id string `path:"id"`
}

type DeleteNotificationRequest struct {
	Id string `path:"id"`
}

type DisconnectOAuthRequest struct {
	Provider string `path:"provider"`
}

type EmailVerificationRequest struct {
	Token string `json:"token"`
}

type Empty struct {
}

type ExtensionChannel struct {
	Id   string `json:"id"`
	Path string `json:"path"`
}

type ExtensionSkill struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Version     string   `json:"version"`
	Triggers    []string `json:"triggers"`
	Tools       []string `json:"tools"`
	Priority    int      `json:"priority"`
	Enabled     bool     `json:"enabled"`
	FilePath    string   `json:"filePath"`
}

type ExtensionTool struct {
	Name             string `json:"name"`
	Description      string `json:"description"`
	Schema           string `json:"schema,omitempty"`
	RequiresApproval bool   `json:"requiresApproval"`
	IsPlugin         bool   `json:"isPlugin"`
	Path             string `json:"path,omitempty"`
}

type ForgotPasswordRequest struct {
	Email string `json:"email"`
}

type GetAgentSessionMessagesResponse struct {
	Messages []SessionMessage `json:"messages"`
	Total    int              `json:"total"`
}

type GetAgentSessionRequest struct {
	Id string `path:"id"`
}

type GetAgentSettingsResponse struct {
	Settings AgentSettings `json:"settings"`
}

type GetAuthProfileRequest struct {
	Id string `path:"id"`
}

type GetAuthProfileResponse struct {
	Profile AuthProfile `json:"profile"`
}

type GetChatRequest struct {
	Id string `path:"id"`
}

type GetChatResponse struct {
	Chat          Chat          `json:"chat"`
	Messages      []ChatMessage `json:"messages"`
	TotalMessages int           `json:"totalMessages"` // Total messages in chat (may be more than returned)
}

type GetHistoryByDayRequest struct {
	Day string `path:"day"`
}

type GetHistoryByDayResponse struct {
	Day      string        `json:"day"`
	Messages []ChatMessage `json:"messages"`
}

type GetOAuthUrlRequest struct {
	Provider    string `path:"provider"`
	RedirectUrl string `form:"redirectUrl,optional"`
}

type GetOAuthUrlResponse struct {
	Url   string `json:"url"`
	State string `json:"state"`
}

type GetPersonalityResponse struct {
	Content string `json:"content"`
}

type GetPreferencesResponse struct {
	Preferences UserPreferences `json:"preferences"`
}

type GetSkillRequest struct {
	Name string `path:"name"`
}

type GetSkillResponse struct {
	Skill ExtensionSkill `json:"skill"`
}

type GetUnreadCountResponse struct {
	Count int `json:"count"`
}

type GetUserResponse struct {
	User User `json:"user"`
}

type HealthResponse struct {
	Status    string `json:"status"`
	Version   string `json:"version"`
	Timestamp string `json:"timestamp"`
}

type ListAgentSessionsResponse struct {
	Sessions []AgentSession `json:"sessions"`
	Total    int            `json:"total"`
}

type ListAgentsRequest struct {
}

type ListAgentsResponse struct {
	Agents []AgentInfo `json:"agents"`
	Total  int         `json:"total"`
}

type ListAuthProfilesResponse struct {
	Profiles []AuthProfile `json:"profiles"`
}

type ListChatDaysRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type ListChatDaysResponse struct {
	Days []DayInfo `json:"days"`
}

type ListChatsRequest struct {
	Page     int `form:"page,optional"`
	PageSize int `form:"pageSize,optional"`
}

type ListChatsResponse struct {
	Chats []Chat `json:"chats"`
	Total int    `json:"total"`
}

type ListExtensionsResponse struct {
	Tools    []ExtensionTool    `json:"tools"`
	Skills   []ExtensionSkill   `json:"skills"`
	Channels []ExtensionChannel `json:"channels"`
}

type ListModelsResponse struct {
	Models        map[string][]ModelInfo `json:"models"`
	TaskRouting   *TaskRouting           `json:"taskRouting,omitempty"`
	Aliases       []ModelAlias           `json:"aliases,omitempty"`
	AvailableCLIs *CLIAvailability       `json:"availableCLIs,omitempty"`
}

type ListNotificationsRequest struct {
	Page     int  `form:"page,optional"`
	PageSize int  `form:"pageSize,optional"`
	Unread   bool `form:"unread,optional"`
}

type ListNotificationsResponse struct {
	Notifications []Notification `json:"notifications"`
	UnreadCount   int            `json:"unreadCount"`
	TotalCount    int            `json:"totalCount"`
}

type ListOAuthProvidersResponse struct {
	Providers []OAuthProvider `json:"providers"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
}

type MarkNotificationReadRequest struct {
	Id string `path:"id"`
}

type MessageResponse struct {
	Message string `json:"message"`
}

type ModelAlias struct {
	Alias   string `json:"alias"`
	ModelId string `json:"modelId"`
}

type ModelInfo struct {
	Id            string        `json:"id"`
	DisplayName   string        `json:"displayName"`
	ContextWindow int           `json:"contextWindow,omitempty"`
	Pricing       *ModelPricing `json:"pricing,omitempty"`
	Capabilities  []string      `json:"capabilities,omitempty"`
	Kind          []string      `json:"kind,omitempty"`
	Preferred     bool          `json:"preferred,omitempty"`
	IsActive      bool          `json:"isActive"`
}

type ModelPricing struct {
	Input       float64 `json:"input,omitempty"`
	Output      float64 `json:"output,omitempty"`
	CachedInput float64 `json:"cachedInput,omitempty"`
}

type Notification struct {
	Id        string `json:"id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Body      string `json:"body,omitempty"`
	ActionUrl string `json:"actionUrl,omitempty"`
	Icon      string `json:"icon,omitempty"`
	ReadAt    string `json:"readAt,omitempty"`
	CreatedAt string `json:"createdAt"`
}

type OAuthLoginRequest struct {
	Provider string `path:"provider"`
	Code     string `json:"code"`
	State    string `json:"state,optional"`
}

type OAuthLoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
	IsNewUser    bool   `json:"isNewUser"`
}

type OAuthProvider struct {
	Name      string `json:"name"`
	Connected bool   `json:"connected"`
	Email     string `json:"email,omitempty"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type ResendVerificationRequest struct {
	Email string `json:"email"`
}

type ResetPasswordRequest struct {
	Token       string `json:"token"`
	NewPassword string `json:"newPassword"`
}

type SearchChatMessagesRequest struct {
	Query    string `form:"query"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"pageSize,optional"`
}

type SearchChatMessagesResponse struct {
	Messages []ChatMessage `json:"messages"`
	Total    int           `json:"total"`
}

type SendMessageRequest struct {
	ChatId  string `json:"chatId"`
	Content string `json:"content"`
	Role    string `json:"role,optional"`
}

type SendMessageResponse struct {
	Message ChatMessage `json:"message"`
	ChatId  string      `json:"chatId"`
}

type SessionMessage struct {
	Id        int    `json:"id"`
	Role      string `json:"role"`
	Content   string `json:"content,omitempty"`
	CreatedAt string `json:"createdAt"`
}

type SetupStatusResponse struct {
	SetupRequired bool `json:"setupRequired"`
	HasAdmin      bool `json:"hasAdmin"`
	SetupComplete bool `json:"setupComplete"`
}

type SimpleAgentStatusResponse struct {
	Connected bool   `json:"connected"`
	AgentId   string `json:"agentId,omitempty"`
	Uptime    int64  `json:"uptime,omitempty"`
}

type TaskRouting struct {
	Vision    string              `json:"vision,omitempty"`
	Audio     string              `json:"audio,omitempty"`
	Reasoning string              `json:"reasoning,omitempty"`
	Code      string              `json:"code,omitempty"`
	General   string              `json:"general,omitempty"`
	Fallbacks map[string][]string `json:"fallbacks,omitempty"`
}

type TestAuthProfileRequest struct {
	Id string `path:"id"`
}

type TestAuthProfileResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Model   string `json:"model,omitempty"`
}

type ToggleSkillRequest struct {
	Name string `path:"name"`
}

type ToggleSkillResponse struct {
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
}

type UpdateAgentSettingsRequest struct {
	AutonomousMode   bool `json:"autonomousMode"`
	AutoApproveRead  bool `json:"autoApproveRead"`
	AutoApproveWrite bool `json:"autoApproveWrite"`
	AutoApproveBash  bool `json:"autoApproveBash"`
}

type UpdateAuthProfileRequest struct {
	Id       string `path:"id"`
	Name     string `json:"name,optional"`
	ApiKey   string `json:"apiKey,optional"`
	Model    string `json:"model,optional"`
	BaseUrl  string `json:"baseUrl,optional"`
	Priority int    `json:"priority,optional"`
	IsActive bool   `json:"isActive,optional"`
}

type UpdateChatRequest struct {
	Id    string `path:"id"`
	Title string `json:"title"`
}

type UpdateModelRequest struct {
	Provider  string   `path:"provider"`
	ModelId   string   `path:"modelId"`
	Active    *bool    `json:"active,optional"`
	Kind      []string `json:"kind,optional"`
	Preferred *bool    `json:"preferred,optional"`
}

type UpdatePersonalityRequest struct {
	Content string `json:"content"`
}

type UpdatePersonalityResponse struct {
	Success bool `json:"success"`
}

type UpdatePreferencesRequest struct {
	EmailNotifications bool   `json:"emailNotifications,optional"`
	MarketingEmails    bool   `json:"marketingEmails,optional"`
	Timezone           string `json:"timezone,optional"`
	Language           string `json:"language,optional"`
	Theme              string `json:"theme,optional"`
}

type UpdateTaskRoutingRequest struct {
	Vision    string              `json:"vision,omitempty"`
	Audio     string              `json:"audio,omitempty"`
	Reasoning string              `json:"reasoning,omitempty"`
	Code      string              `json:"code,omitempty"`
	General   string              `json:"general,omitempty"`
	Fallbacks map[string][]string `json:"fallbacks,omitempty"`
	Aliases   []ModelAlias        `json:"aliases,omitempty"`
}

type UpdateUserRequest struct {
	Name      string `json:"name,optional"`
	AvatarUrl string `json:"avatarUrl,optional"`
}

type User struct {
	Id            string `json:"id"`
	Email         string `json:"email"`
	Name          string `json:"name"`
	AvatarUrl     string `json:"avatarUrl,omitempty"`
	EmailVerified bool   `json:"emailVerified"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type UserPreferences struct {
	EmailNotifications bool   `json:"emailNotifications"`
	MarketingEmails    bool   `json:"marketingEmails"`
	Timezone           string `json:"timezone"`
	Language           string `json:"language"`
	Theme              string `json:"theme"`
}
