package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// ── neboComponents.ts Generation ────────────────────────────────────────

func generateComponents(path string, structs map[string]*RustStruct, handlers map[string]*HandlerInfo, wsEvents []WSEvent) {
	var b strings.Builder

	b.WriteString("// Code generated by scripts/genapi. DO NOT EDIT.\n")
	b.WriteString("// To regenerate: make gen\n\n")

	// ── Section 1: Interfaces from Rust structs ─────────────────────
	b.WriteString("// ── Rust Struct Models ──────────────────────────────────────────────\n\n")

	// Determine which structs to emit. Skip internal-only structs.
	skipStructs := map[string]bool{
		"ErrorResponse": true, // emitted separately
	}

	for _, name := range sortedKeys(structs) {
		if skipStructs[name] {
			continue
		}
		s := structs[name]
		emitStruct(&b, s, structs)
	}

	// ── Section 2: Handler response types ───────────────────────────
	b.WriteString("// ── API Response Types (inferred from handlers) ────────────────────\n\n")

	// Collect all unique response types from handlers.
	type respType struct {
		name string
		keys []ResponseKey
	}
	var responseTypes []respType
	seen := make(map[string]bool)

	for _, qname := range sortedKeys(handlers) {
		h := handlers[qname]
		if len(h.ResponseKeys) == 0 {
			continue
		}
		typeName := handlerToResponseTypeName(h.FuncName)
		if seen[typeName] {
			continue
		}
		seen[typeName] = true
		responseTypes = append(responseTypes, respType{name: typeName, keys: h.ResponseKeys})
	}

	sort.Slice(responseTypes, func(i, j int) bool {
		return responseTypes[i].name < responseTypes[j].name
	})

	for _, rt := range responseTypes {
		emitResponseType(&b, rt.name, rt.keys)
	}

	// ── Section 3: Common types ─────────────────────────────────────
	b.WriteString("// ── Common Types ───────────────────────────────────────────────────\n\n")
	b.WriteString("export interface ErrorResponse {\n\terror: string\n}\n\n")
	b.WriteString("export interface MessageResponse {\n\tmessage: string\n}\n\n")
	b.WriteString("export interface SuccessResponse {\n\tsuccess: boolean\n}\n\n")

	// ── Section 4: Extra interfaces from type overrides ─────────────
	if len(extraInterfaces) > 0 {
		b.WriteString("// ── Override Types (see scripts/genapi/overrides.go) ───────────────\n\n")
		for _, name := range sortedKeys(extraInterfaces) {
			b.WriteString(extraInterfaces[name])
			b.WriteString("\n\n")
		}
	}

	// ── Section 5: WebSocket event types ─────────────────────────────
	if len(wsEvents) > 0 {
		b.WriteString("// ── WebSocket Event Types ──────────────────────────────────────────\n\n")
		emitWSEvents(&b, wsEvents)
	}

	if err := os.WriteFile(path, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", path, err)
		os.Exit(1)
	}
}

func emitStruct(b *strings.Builder, s *RustStruct, allStructs map[string]*RustStruct) {
	// Count non-skipped fields.
	visibleFields := 0
	for _, f := range s.Fields {
		if !f.Skip {
			visibleFields++
		}
	}
	if visibleFields == 0 {
		return
	}

	fmt.Fprintf(b, "export interface %s {\n", s.Name)
	for _, f := range s.Fields {
		if f.Skip {
			continue
		}

		tsName := toTSFieldName(f, s.RenameAll)

		// Determine TS type.
		var tsType string
		if sw := resolveSerializeWith(f.SerializeWith); sw != "" {
			tsType = sw
		} else {
			tsType = rustTypeToTS(f.RustType, allStructs)
		}

		optional := ""
		if f.Optional {
			optional = "?"
		}

		fmt.Fprintf(b, "\t%s%s: %s\n", tsName, optional, tsType)
	}
	b.WriteString("}\n\n")
}

func emitResponseType(b *strings.Builder, name string, keys []ResponseKey) {
	fmt.Fprintf(b, "export interface %s {\n", name)
	for _, k := range keys {
		fmt.Fprintf(b, "\t%s: %s\n", k.Key, k.InferredTS)
	}
	b.WriteString("}\n\n")
}

func emitWSEvents(b *strings.Builder, events []WSEvent) {
	// Group by direction.
	var serverEvents, clientEvents []WSEvent
	for _, e := range events {
		if e.Direction == "server" {
			serverEvents = append(serverEvents, e)
		} else {
			clientEvents = append(clientEvents, e)
		}
	}

	if len(serverEvents) > 0 {
		b.WriteString("/** Server → Client WebSocket events */\n")
		b.WriteString("export type WSServerEventType =\n")
		for _, e := range serverEvents {
			fmt.Fprintf(b, "\t| \"%s\"\n", e.EventType)
		}
		b.WriteString("\n")

		// Generate payload interfaces for events with known keys.
		for _, e := range serverEvents {
			if len(e.Keys) > 0 {
				typeName := snakeToPascal(e.EventType) + "Event"
				emitResponseType(b, typeName, e.Keys)
			}
		}
	}

	if len(clientEvents) > 0 {
		b.WriteString("/** Client → Server WebSocket message types */\n")
		b.WriteString("export type WSClientMessageType =\n")
		for _, e := range clientEvents {
			fmt.Fprintf(b, "\t| \"%s\"\n", e.EventType)
		}
		b.WriteString("\n")
	}
}

// ── nebo.ts Generation ──────────────────────────────────────────────────

func generateAPI(path string, routes []Route, handlers map[string]*HandlerInfo) {
	var b strings.Builder

	b.WriteString("// Code generated by scripts/genapi. DO NOT EDIT.\n")
	b.WriteString("// To regenerate: make gen\n\n")
	b.WriteString("import webapi from \"./gocliRequest\"\n")
	b.WriteString("import * as components from \"./neboComponents\"\n")
	b.WriteString("export * from \"./neboComponents\"\n\n")

	// Sort routes for stable output.
	sort.Slice(routes, func(i, j int) bool {
		pi := strings.ReplaceAll(routes[i].Path, "{", "~")
		pj := strings.ReplaceAll(routes[j].Path, "{", "~")
		if pi != pj {
			return pi < pj
		}
		methodOrder := map[string]int{"GET": 0, "POST": 1, "PUT": 2, "DELETE": 3, "PATCH": 4}
		return methodOrder[routes[i].Method] < methodOrder[routes[j].Method]
	})

	// Track generated functions to avoid duplicates.
	generated := make(map[string]bool)

	// Skip list: WS handlers, file wildcards, etc.
	skipHandlers := map[string]bool{
		"ws_handler": true,
	}

	for _, route := range routes {
		handlerParts := strings.Split(route.Handler, "::")
		handlerFn := handlerParts[len(handlerParts)-1]

		if skipHandlers[handlerFn] {
			continue
		}

		funcName := handlerToFuncName(route.Handler)
		if generated[funcName] {
			continue
		}
		generated[funcName] = true

		emitAPIFunction(&b, route, funcName, handlers)
	}

	if err := os.WriteFile(path, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", path, err)
		os.Exit(1)
	}
}

func emitAPIFunction(b *strings.Builder, route Route, funcName string, handlers map[string]*HandlerInfo) {
	method := strings.ToLower(route.Method)
	apiPath := "/api/v1" + route.Path

	// Determine response type.
	responseType := "unknown"
	h := handlers[route.Handler]
	if h != nil && len(h.ResponseKeys) > 0 {
		responseType = "components." + handlerToResponseTypeName(h.FuncName)
	}

	// Build path params.
	pathParams := extractPathParams(route.Path)

	// Build function params: path params first, then optional body.
	var params []string

	// Path params (required, come first).
	for _, p := range pathParams {
		tsName := pathParamToTSName(p)
		params = append(params, tsName+": string")
	}

	// For POST/PUT/PATCH, add request body param (optional, comes last).
	hasBody := method == "post" || method == "put" || method == "patch"
	if hasBody {
		params = append(params, "req: Record<string, unknown> = {}")
	}

	// Build URL template.
	urlTemplate := apiPath
	for _, p := range pathParams {
		tsName := pathParamToTSName(p)
		urlTemplate = strings.Replace(urlTemplate, "{"+p+"}", "${"+tsName+"}", 1)
		urlTemplate = strings.Replace(urlTemplate, "{*"+p+"}", "${"+tsName+"}", 1)
	}

	// Description.
	desc := deriveDescription(funcName)
	fmt.Fprintf(b, "/**\n * @description \"%s\"\n */\n", desc)

	// Function signature.
	fmt.Fprintf(b, "export function %s(%s) {\n", funcName, strings.Join(params, ", "))

	// Function body.
	switch method {
	case "get":
		fmt.Fprintf(b, "\treturn webapi.get<%s>(`%s`)\n", responseType, urlTemplate)
	case "delete":
		fmt.Fprintf(b, "\treturn webapi.delete<%s>(`%s`)\n", responseType, urlTemplate)
	case "post":
		if hasBody {
			fmt.Fprintf(b, "\treturn webapi.post<%s>(`%s`, req)\n", responseType, urlTemplate)
		} else {
			fmt.Fprintf(b, "\treturn webapi.post<%s>(`%s`)\n", responseType, urlTemplate)
		}
	case "put":
		if hasBody {
			fmt.Fprintf(b, "\treturn webapi.put<%s>(`%s`, req)\n", responseType, urlTemplate)
		} else {
			fmt.Fprintf(b, "\treturn webapi.put<%s>(`%s`)\n", responseType, urlTemplate)
		}
	case "patch":
		if hasBody {
			fmt.Fprintf(b, "\treturn webapi.patch<%s>(`%s`, req)\n", responseType, urlTemplate)
		} else {
			fmt.Fprintf(b, "\treturn webapi.patch<%s>(`%s`)\n", responseType, urlTemplate)
		}
	}

	b.WriteString("}\n\n")
}
