//! How a workflow is designed: the one rule set every surface that authors
//! workflows teaches (create_workflow, create_employee's duties, the
//! builder's Architect). Scored by the authoring eval
//! (`make eval-authoring`); change it there, not per surface.

/// The design rules, decomposition first.
pub const AUTHORING_RULES: &str = "Design rules (decompose first):\n\
1. Split code from judgment. Reading or writing a system in bulk (a sheet or file in a drive, a mailbox, a ledger, a CRM) is code, never an AI action with the plugin's tool. Code steps: `operation` ({\"type\": \"operation\", \"params\": {\"operation\": \"ledger.invoice.search\", \"input\": {...}}} reads every page; with `\"rows\": \"nodes.<id>.<list>\"` it makes one call per row) when a connected plugin binds the interface; otherwise `command` calling the plugin's program, `${plugin.<SLUG>_BIN} <command>` with `params.skill` naming its skill (`params.stdin` hands it a list such as `nodes.fetch.items`); `http`. AI judges. Bulk work: FETCH everything once, paged → MATCH by rules, skipping records already done → JUDGE only the leftovers → APPLY in one bulk write → VERIFY by reading back. Never a loop of AI actions calling a system per record: per-record writing (emails, replies) is drafted for all records in one `tools: []` action, then one action sends them all. Every number the owner gets (totals, counts, sums) comes from a code step; AI never adds up.\n\
2. An action (activity) is one unit: one executor (code or AI), one tool set, one context, one output, one retry boundary. Its `steps` are ordered instructions on the same data and tools (read → analyze → draft is one action). Start a new action when the executor or tools change, at each side effect (write, send, pay), at an approval, per item (loop), at a branch or an output several actions use, or on different data. Over 6 steps, judgment mixed with a write, or code mixed with AI means split.\n\
3. Every AI action declares `tools`: exactly what it calls (`plugin__<slug>`, tool names). It runs with only those plus exit, emit_event and message_owner; a tool it doesn't list is refused, and an unattended run stalls. A judgment action has `\"tools\": []` and answers JSON.\n\
4. Name the data each action needs as `{{nodes.<id>.<field>}}` or `{{item.<field>}}` (never `${nodes...}`); don't count on earlier output reaching it unnamed. Code steps print JSON with a short `summary` and the fields others read.\n\
5. `connections` wire every action from `__trigger__`: nothing unreachable, no missing edge. A `condition` is one comparison, `{\"expression\": \"nodes.fetch.count > 0\"}` (==, !=, >, <, >=, <=); chain conditions for more. It routes by labeled edges: {\"from\": \"<condition id>\", \"to\": \"<id>\", \"label\": \"True\"} (and \"False\").\n\
6. Fan out independent parts; keep dependent parts in sequence. Fixed: one action → parallel branches (different systems or experts) → one join action that combines their summaries and reports a failed branch, carrying on. Per item: a `loop` (params.source, \"Each item\"/\"Done\" edges; when each item names its own expert, one expert action in the body with `\"expert\": \"{{item.<field>}}\"`) with `params.concurrency` (after it, read every item's result as `{{nodes.<loop id>.results}}`): 1 per shared external system; higher only when the body has `tools: []` or each item goes to a different expert or system.\n\
7. Heartbeats and watches start with a code check, then a condition before any AI (`{\"id\": \"any\", \"type\": \"condition\", \"params\": {\"expression\": \"nodes.fetch.count > 0\"}}`, edge labeled \"True\" to the AI); AI runs only when there is work.\n\
8. No waiting, retrying or scheduling instructions: plugins pace and retry themselves, and an unattended run cannot create schedules.\n\
9. Never remove an approval. Only an operation in the employee's `ceiling` (or one the catalog gates, such as payments and sending invoices) waits for the owner; \"ask first\" in prose or ask_owner holds nothing. Put every other money-moving or outward-facing operation (send to customers, post, publish) in the ceiling: create_employee's `ceiling`, in the same call as its automations; for an existing employee, ask the owner to add it. Make that write an AI action with the plugin's tool declared so its call can wait (a `command` step cannot).\n\
10. Files are per run: a code step makes a fresh temp file and passes its path on in its JSON; never a fixed path parallel runs overwrite.\n\
11. Experts: check your coworkers (list_employees) and hand an action to one when it has access you lack, owns that judgment, or already runs that work; never trivial work or work your own tools do. One `expert` action per handoff, wired in `connections`: {\"id\": \"price\", \"type\": \"expert\", \"params\": {\"expert\": \"<coworker name>\", \"task\": \"Price the order for {{inputs.customer}}\", \"input\": {\"order\": \"{{nodes.fetch}}\"}, \"output\": {\"total\": \"number\"}, \"timeout\": \"4h\"}, \"on_error\": {\"retry\": 1, \"fallback\": \"abort\"}}. `timeout` is required; each `input` value is one reference; without `\"fallback\": \"abort\"` a failed expert completes as {failed, reason, summary} and the run continues. Store employees not yet hired and experts on another owner's bot are never put in a workflow: propose them to the owner in your reply (hiring, or their one-time OK for another owner's expert).\n\
12. Give every action the access it needs. List each one's data: outside (a plugin, a connected MCP server's tools `mcp__<server>__<tool>`) and inside (memory: recall; files: a command step lists them, read_file reads them; past chats: read_session; app_data; skills: use_skill). Declare the tools that reach it, from what this bot has (find_tools, find_plugins), never a guess. When nothing here reaches it, tell the owner what to connect or hand that action to an expert who has it; never leave a step to fail.\n\
Before you call, check: a job that reads a system starts with a code step reading it, and no AI action holds a plugin's tool just to read; a heartbeat, watch or frequent schedule has a condition between its code check and the first AI action; no activity does a whole job across systems; every activity that is not command, operation, http, condition, loop or expert has `tools`; every activity after a code step names the data it uses as {{nodes.<id>.<field>}} in its intent or steps; several activities are wired in `connections`; every plugin, MCP tool and expert you name is one this bot has (installed, connected, a coworker), never a store employee or another owner's expert, which you only propose in your reply; outward or money-moving writes are in the ceiling (on an existing employee, ask the owner to add the operation to its approval list; a yes in chat holds nothing).";

/// One request decomposed by the rules: two systems read in parallel, a
/// rule match joining them, one judgment call on the leftovers, a payment
/// that waits for the owner, and a read-back.
pub const WORKED_EXAMPLE: &str = r#"Example. "Each weekday at 7, pay supplier invoices in my inbox that match a purchase order; tell me about the rest." Actions: invoices and pos (code, two systems, in parallel) → match (code, joins them) → judge (AI, tools: [], three steps of one judgment) → pay (AI with the ledger's tool; the catalog gates ledger.billpayment.create, so each payment waits for the owner) → verify (code: the totals the owner reads). Had a coworker held the ledger instead of you, pay would be an expert action.
{"trigger": {"type": "schedule", "cron": "0 7 * * MON-FRI"}, "activities": [{"id": "invoices", "type": "command", "params": {"skill": "mail", "command": "${plugin.MAIL_BIN} messages search --label invoices --since 1d --all --json"}}, {"id": "pos", "type": "operation", "params": {"operation": "ledger.bill.search", "input": {"status": "open"}}}, {"id": "match", "type": "command", "params": {"command": "<rules script reading {{nodes.invoices.items}} and {{nodes.pos.items}}: pair by PO number and amount, skip invoices already paid; prints {summary, matched, leftovers}>"}}, {"id": "judge", "tools": [], "intent": "Decide the invoices in {{nodes.match.leftovers}}", "steps": ["Read each leftover against its closest PO", "Pick pay, hold or ask", "Answer only JSON: {\"summary\": \"…\", \"decisions\": [{\"id\": \"…\", \"choice\": \"…\"}]}"]}, {"id": "pay", "tools": ["plugin__ledger"], "intent": "Pay {{nodes.match.matched}} and the invoices marked pay in {{nodes.judge.decisions}} in one batch; answer JSON {summary, ids}"}, {"id": "verify", "type": "command", "params": {"skill": "ledger", "command": "${plugin.LEDGER_BIN} payments get --ids {{nodes.pay.ids}} --json"}}], "connections": [{"from": "__trigger__", "to": "invoices"}, {"from": "__trigger__", "to": "pos"}, {"from": "invoices", "to": "match"}, {"from": "pos", "to": "match"}, {"from": "match", "to": "judge"}, {"from": "judge", "to": "pay"}, {"from": "pay", "to": "verify"}]}"#;
