// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: proto/apps/v0/hooks.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HookRequest carries data to the app for a specific hook point.
type HookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          string                 `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`                                   // Hook name, e.g. "tool.pre_execute"
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                             // JSON-encoded hook-specific data
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // When the hook fired (Unix ms)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	mi := &file_proto_apps_v0_hooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_hooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_hooks_proto_rawDescGZIP(), []int{0}
}

func (x *HookRequest) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *HookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HookRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// HookResponse carries the app's modified data back to Nebo.
type HookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`  // JSON-encoded modified data (for filters)
	Handled       bool                   `protobuf:"varint,2,opt,name=handled,proto3" json:"handled,omitempty"` // If true, Nebo skips the built-in implementation
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // Non-empty = hook failed, use original data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_proto_apps_v0_hooks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_hooks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_hooks_proto_rawDescGZIP(), []int{1}
}

func (x *HookResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HookResponse) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *HookResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HookList contains all hook registrations for an app.
type HookList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hooks         []*HookRegistration    `protobuf:"bytes,1,rep,name=hooks,proto3" json:"hooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookList) Reset() {
	*x = HookList{}
	mi := &file_proto_apps_v0_hooks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookList) ProtoMessage() {}

func (x *HookList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_hooks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookList.ProtoReflect.Descriptor instead.
func (*HookList) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_hooks_proto_rawDescGZIP(), []int{2}
}

func (x *HookList) GetHooks() []*HookRegistration {
	if x != nil {
		return x.Hooks
	}
	return nil
}

// HookRegistration declares a single hook subscription.
type HookRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          string                 `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`          // Hook name, e.g. "tool.pre_execute"
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`          // "action" or "filter"
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"` // Lower = runs first (default 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRegistration) Reset() {
	*x = HookRegistration{}
	mi := &file_proto_apps_v0_hooks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRegistration) ProtoMessage() {}

func (x *HookRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_apps_v0_hooks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRegistration.ProtoReflect.Descriptor instead.
func (*HookRegistration) Descriptor() ([]byte, []int) {
	return file_proto_apps_v0_hooks_proto_rawDescGZIP(), []int{3}
}

func (x *HookRegistration) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *HookRegistration) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HookRegistration) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_proto_apps_v0_hooks_proto protoreflect.FileDescriptor

const file_proto_apps_v0_hooks_proto_rawDesc = "" +
	"\n" +
	"\x19proto/apps/v0/hooks.proto\x12\aapps.v0\x1a\x1aproto/apps/v0/common.proto\"^\n" +
	"\vHookRequest\x12\x12\n" +
	"\x04hook\x18\x01 \x01(\tR\x04hook\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"X\n" +
	"\fHookResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x18\n" +
	"\ahandled\x18\x02 \x01(\bR\ahandled\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\";\n" +
	"\bHookList\x12/\n" +
	"\x05hooks\x18\x01 \x03(\v2\x19.apps.v0.HookRegistrationR\x05hooks\"V\n" +
	"\x10HookRegistration\x12\x12\n" +
	"\x04hook\x18\x01 \x01(\tR\x04hook\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority2\xf5\x01\n" +
	"\vHookService\x12:\n" +
	"\vApplyFilter\x12\x14.apps.v0.HookRequest\x1a\x15.apps.v0.HookResponse\x120\n" +
	"\bDoAction\x12\x14.apps.v0.HookRequest\x1a\x0e.apps.v0.Empty\x12.\n" +
	"\tListHooks\x12\x0e.apps.v0.Empty\x1a\x11.apps.v0.HookList\x12H\n" +
	"\vHealthCheck\x12\x1b.apps.v0.HealthCheckRequest\x1a\x1c.apps.v0.HealthCheckResponseB+Z)github.com/NeboLoop/nebo/internal/apps/pbb\x06proto3"

var (
	file_proto_apps_v0_hooks_proto_rawDescOnce sync.Once
	file_proto_apps_v0_hooks_proto_rawDescData []byte
)

func file_proto_apps_v0_hooks_proto_rawDescGZIP() []byte {
	file_proto_apps_v0_hooks_proto_rawDescOnce.Do(func() {
		file_proto_apps_v0_hooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_apps_v0_hooks_proto_rawDesc), len(file_proto_apps_v0_hooks_proto_rawDesc)))
	})
	return file_proto_apps_v0_hooks_proto_rawDescData
}

var file_proto_apps_v0_hooks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_apps_v0_hooks_proto_goTypes = []any{
	(*HookRequest)(nil),         // 0: apps.v0.HookRequest
	(*HookResponse)(nil),        // 1: apps.v0.HookResponse
	(*HookList)(nil),            // 2: apps.v0.HookList
	(*HookRegistration)(nil),    // 3: apps.v0.HookRegistration
	(*Empty)(nil),               // 4: apps.v0.Empty
	(*HealthCheckRequest)(nil),  // 5: apps.v0.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 6: apps.v0.HealthCheckResponse
}
var file_proto_apps_v0_hooks_proto_depIdxs = []int32{
	3, // 0: apps.v0.HookList.hooks:type_name -> apps.v0.HookRegistration
	0, // 1: apps.v0.HookService.ApplyFilter:input_type -> apps.v0.HookRequest
	0, // 2: apps.v0.HookService.DoAction:input_type -> apps.v0.HookRequest
	4, // 3: apps.v0.HookService.ListHooks:input_type -> apps.v0.Empty
	5, // 4: apps.v0.HookService.HealthCheck:input_type -> apps.v0.HealthCheckRequest
	1, // 5: apps.v0.HookService.ApplyFilter:output_type -> apps.v0.HookResponse
	4, // 6: apps.v0.HookService.DoAction:output_type -> apps.v0.Empty
	2, // 7: apps.v0.HookService.ListHooks:output_type -> apps.v0.HookList
	6, // 8: apps.v0.HookService.HealthCheck:output_type -> apps.v0.HealthCheckResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_apps_v0_hooks_proto_init() }
func file_proto_apps_v0_hooks_proto_init() {
	if File_proto_apps_v0_hooks_proto != nil {
		return
	}
	file_proto_apps_v0_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_apps_v0_hooks_proto_rawDesc), len(file_proto_apps_v0_hooks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_apps_v0_hooks_proto_goTypes,
		DependencyIndexes: file_proto_apps_v0_hooks_proto_depIdxs,
		MessageInfos:      file_proto_apps_v0_hooks_proto_msgTypes,
	}.Build()
	File_proto_apps_v0_hooks_proto = out.File
	file_proto_apps_v0_hooks_proto_goTypes = nil
	file_proto_apps_v0_hooks_proto_depIdxs = nil
}
