// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: advisors.sql

package db

import (
	"context"
)

const createAdvisor = `-- name: CreateAdvisor :one
INSERT INTO advisors (name, role, description, priority, enabled, memory_access, persona, timeout_seconds)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, role, description, priority, enabled, memory_access, persona, timeout_seconds, created_at, updated_at
`

type CreateAdvisorParams struct {
	Name           string `json:"name"`
	Role           string `json:"role"`
	Description    string `json:"description"`
	Priority       int64  `json:"priority"`
	Enabled        int64  `json:"enabled"`
	MemoryAccess   int64  `json:"memory_access"`
	Persona        string `json:"persona"`
	TimeoutSeconds int64  `json:"timeout_seconds"`
}

func (q *Queries) CreateAdvisor(ctx context.Context, arg CreateAdvisorParams) (Advisor, error) {
	row := q.db.QueryRowContext(ctx, createAdvisor,
		arg.Name,
		arg.Role,
		arg.Description,
		arg.Priority,
		arg.Enabled,
		arg.MemoryAccess,
		arg.Persona,
		arg.TimeoutSeconds,
	)
	var i Advisor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.Priority,
		&i.Enabled,
		&i.MemoryAccess,
		&i.Persona,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdvisor = `-- name: DeleteAdvisor :exec
DELETE FROM advisors WHERE name = ?
`

func (q *Queries) DeleteAdvisor(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteAdvisor, name)
	return err
}

const getAdvisor = `-- name: GetAdvisor :one
SELECT id, name, role, description, priority, enabled, memory_access, persona, timeout_seconds, created_at, updated_at FROM advisors WHERE name = ?
`

func (q *Queries) GetAdvisor(ctx context.Context, name string) (Advisor, error) {
	row := q.db.QueryRowContext(ctx, getAdvisor, name)
	var i Advisor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.Priority,
		&i.Enabled,
		&i.MemoryAccess,
		&i.Persona,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdvisorByID = `-- name: GetAdvisorByID :one
SELECT id, name, role, description, priority, enabled, memory_access, persona, timeout_seconds, created_at, updated_at FROM advisors WHERE id = ?
`

func (q *Queries) GetAdvisorByID(ctx context.Context, id int64) (Advisor, error) {
	row := q.db.QueryRowContext(ctx, getAdvisorByID, id)
	var i Advisor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Description,
		&i.Priority,
		&i.Enabled,
		&i.MemoryAccess,
		&i.Persona,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdvisors = `-- name: ListAdvisors :many
SELECT id, name, role, description, priority, enabled, memory_access, persona, timeout_seconds, created_at, updated_at FROM advisors ORDER BY priority DESC
`

func (q *Queries) ListAdvisors(ctx context.Context) ([]Advisor, error) {
	rows, err := q.db.QueryContext(ctx, listAdvisors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advisor
	for rows.Next() {
		var i Advisor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.Priority,
			&i.Enabled,
			&i.MemoryAccess,
			&i.Persona,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAdvisors = `-- name: ListEnabledAdvisors :many
SELECT id, name, role, description, priority, enabled, memory_access, persona, timeout_seconds, created_at, updated_at FROM advisors WHERE enabled = 1 ORDER BY priority DESC
`

func (q *Queries) ListEnabledAdvisors(ctx context.Context) ([]Advisor, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledAdvisors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advisor
	for rows.Next() {
		var i Advisor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Description,
			&i.Priority,
			&i.Enabled,
			&i.MemoryAccess,
			&i.Persona,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdvisor = `-- name: UpdateAdvisor :exec
UPDATE advisors SET
    role = ?,
    description = ?,
    priority = ?,
    enabled = ?,
    memory_access = ?,
    persona = ?,
    timeout_seconds = ?,
    updated_at = strftime('%s', 'now')
WHERE name = ?
`

type UpdateAdvisorParams struct {
	Role           string `json:"role"`
	Description    string `json:"description"`
	Priority       int64  `json:"priority"`
	Enabled        int64  `json:"enabled"`
	MemoryAccess   int64  `json:"memory_access"`
	Persona        string `json:"persona"`
	TimeoutSeconds int64  `json:"timeout_seconds"`
	Name           string `json:"name"`
}

func (q *Queries) UpdateAdvisor(ctx context.Context, arg UpdateAdvisorParams) error {
	_, err := q.db.ExecContext(ctx, updateAdvisor,
		arg.Role,
		arg.Description,
		arg.Priority,
		arg.Enabled,
		arg.MemoryAccess,
		arg.Persona,
		arg.TimeoutSeconds,
		arg.Name,
	)
	return err
}
