// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_skills.sql

package db

import (
	"context"
)

const createChannelSkill = `-- name: CreateChannelSkill :exec
INSERT INTO channel_skills (channel_id, skill_name)
VALUES (?, ?)
ON CONFLICT (channel_id, skill_name) DO NOTHING
`

type CreateChannelSkillParams struct {
	ChannelID string `json:"channel_id"`
	SkillName string `json:"skill_name"`
}

func (q *Queries) CreateChannelSkill(ctx context.Context, arg CreateChannelSkillParams) error {
	_, err := q.db.ExecContext(ctx, createChannelSkill, arg.ChannelID, arg.SkillName)
	return err
}

const deleteChannelSkill = `-- name: DeleteChannelSkill :exec
DELETE FROM channel_skills WHERE channel_id = ? AND skill_name = ?
`

type DeleteChannelSkillParams struct {
	ChannelID string `json:"channel_id"`
	SkillName string `json:"skill_name"`
}

func (q *Queries) DeleteChannelSkill(ctx context.Context, arg DeleteChannelSkillParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannelSkill, arg.ChannelID, arg.SkillName)
	return err
}

const deleteChannelSkills = `-- name: DeleteChannelSkills :exec
DELETE FROM channel_skills WHERE channel_id = ?
`

func (q *Queries) DeleteChannelSkills(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteChannelSkills, channelID)
	return err
}

const getChannelSkill = `-- name: GetChannelSkill :one
SELECT channel_id, skill_name, created_at FROM channel_skills WHERE channel_id = ? AND skill_name = ?
`

type GetChannelSkillParams struct {
	ChannelID string `json:"channel_id"`
	SkillName string `json:"skill_name"`
}

func (q *Queries) GetChannelSkill(ctx context.Context, arg GetChannelSkillParams) (ChannelSkill, error) {
	row := q.db.QueryRowContext(ctx, getChannelSkill, arg.ChannelID, arg.SkillName)
	var i ChannelSkill
	err := row.Scan(&i.ChannelID, &i.SkillName, &i.CreatedAt)
	return i, err
}

const listAllChannelSkills = `-- name: ListAllChannelSkills :many
SELECT channel_id, skill_name, created_at FROM channel_skills ORDER BY created_at ASC
`

func (q *Queries) ListAllChannelSkills(ctx context.Context) ([]ChannelSkill, error) {
	rows, err := q.db.QueryContext(ctx, listAllChannelSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelSkill
	for rows.Next() {
		var i ChannelSkill
		if err := rows.Scan(&i.ChannelID, &i.SkillName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelSkills = `-- name: ListChannelSkills :many
SELECT channel_id, skill_name, created_at FROM channel_skills WHERE channel_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListChannelSkills(ctx context.Context, channelID string) ([]ChannelSkill, error) {
	rows, err := q.db.QueryContext(ctx, listChannelSkills, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelSkill
	for rows.Next() {
		var i ChannelSkill
		if err := rows.Scan(&i.ChannelID, &i.SkillName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
