// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package db

import (
	"context"
	"database/sql"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, name, channel_type, is_enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, unixepoch(), unixepoch())
RETURNING id, name, channel_type, is_enabled, connection_status, last_connected_at, last_error, message_count, created_at, updated_at
`

type CreateChannelParams struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	ChannelType string        `json:"channel_type"`
	IsEnabled   sql.NullInt64 `json:"is_enabled"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.ID,
		arg.Name,
		arg.ChannelType,
		arg.IsEnabled,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.IsEnabled,
		&i.ConnectionStatus,
		&i.LastConnectedAt,
		&i.LastError,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = ?
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, id)
	return err
}

const deleteChannelConfig = `-- name: DeleteChannelConfig :exec
DELETE FROM channel_config WHERE channel_id = ? AND config_key = ?
`

type DeleteChannelConfigParams struct {
	ChannelID string `json:"channel_id"`
	ConfigKey string `json:"config_key"`
}

func (q *Queries) DeleteChannelConfig(ctx context.Context, arg DeleteChannelConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannelConfig, arg.ChannelID, arg.ConfigKey)
	return err
}

const deleteChannelCredential = `-- name: DeleteChannelCredential :exec
DELETE FROM channel_credentials WHERE channel_id = ? AND credential_key = ?
`

type DeleteChannelCredentialParams struct {
	ChannelID     string `json:"channel_id"`
	CredentialKey string `json:"credential_key"`
}

func (q *Queries) DeleteChannelCredential(ctx context.Context, arg DeleteChannelCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannelCredential, arg.ChannelID, arg.CredentialKey)
	return err
}

const deleteChannelCredentials = `-- name: DeleteChannelCredentials :exec
DELETE FROM channel_credentials WHERE channel_id = ?
`

func (q *Queries) DeleteChannelCredentials(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteChannelCredentials, channelID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, channel_type, is_enabled, connection_status, last_connected_at, last_error, message_count, created_at, updated_at FROM channels WHERE id = ?
`

func (q *Queries) GetChannel(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.IsEnabled,
		&i.ConnectionStatus,
		&i.LastConnectedAt,
		&i.LastError,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByType = `-- name: GetChannelByType :one
SELECT id, name, channel_type, is_enabled, connection_status, last_connected_at, last_error, message_count, created_at, updated_at FROM channels WHERE channel_type = ? AND is_enabled = 1 LIMIT 1
`

func (q *Queries) GetChannelByType(ctx context.Context, channelType string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByType, channelType)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.IsEnabled,
		&i.ConnectionStatus,
		&i.LastConnectedAt,
		&i.LastError,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelConfig = `-- name: GetChannelConfig :one
SELECT id, channel_id, config_key, config_value, created_at, updated_at FROM channel_config WHERE channel_id = ? AND config_key = ?
`

type GetChannelConfigParams struct {
	ChannelID string `json:"channel_id"`
	ConfigKey string `json:"config_key"`
}

func (q *Queries) GetChannelConfig(ctx context.Context, arg GetChannelConfigParams) (ChannelConfig, error) {
	row := q.db.QueryRowContext(ctx, getChannelConfig, arg.ChannelID, arg.ConfigKey)
	var i ChannelConfig
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelCredential = `-- name: GetChannelCredential :one
SELECT id, channel_id, credential_key, credential_value, created_at, updated_at FROM channel_credentials WHERE channel_id = ? AND credential_key = ?
`

type GetChannelCredentialParams struct {
	ChannelID     string `json:"channel_id"`
	CredentialKey string `json:"credential_key"`
}

func (q *Queries) GetChannelCredential(ctx context.Context, arg GetChannelCredentialParams) (ChannelCredential, error) {
	row := q.db.QueryRowContext(ctx, getChannelCredential, arg.ChannelID, arg.CredentialKey)
	var i ChannelCredential
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.CredentialKey,
		&i.CredentialValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelRegistry = `-- name: GetChannelRegistry :one
SELECT id, name, description, icon, setup_instructions, required_credentials, optional_credentials, display_order, created_at FROM channel_registry WHERE id = ?
`

func (q *Queries) GetChannelRegistry(ctx context.Context, id string) (ChannelRegistry, error) {
	row := q.db.QueryRowContext(ctx, getChannelRegistry, id)
	var i ChannelRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SetupInstructions,
		&i.RequiredCredentials,
		&i.OptionalCredentials,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const incrementChannelMessageCount = `-- name: IncrementChannelMessageCount :exec
UPDATE channels SET message_count = message_count + 1, updated_at = unixepoch() WHERE id = ?
`

func (q *Queries) IncrementChannelMessageCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementChannelMessageCount, id)
	return err
}

const listChannelConfig = `-- name: ListChannelConfig :many
SELECT id, channel_id, config_key, config_value, created_at, updated_at FROM channel_config WHERE channel_id = ?
`

func (q *Queries) ListChannelConfig(ctx context.Context, channelID string) ([]ChannelConfig, error) {
	rows, err := q.db.QueryContext(ctx, listChannelConfig, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelConfig
	for rows.Next() {
		var i ChannelConfig
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelCredentials = `-- name: ListChannelCredentials :many
SELECT id, channel_id, credential_key, credential_value, created_at, updated_at FROM channel_credentials WHERE channel_id = ?
`

func (q *Queries) ListChannelCredentials(ctx context.Context, channelID string) ([]ChannelCredential, error) {
	rows, err := q.db.QueryContext(ctx, listChannelCredentials, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelCredential
	for rows.Next() {
		var i ChannelCredential
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.CredentialKey,
			&i.CredentialValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelRegistry = `-- name: ListChannelRegistry :many
SELECT id, name, description, icon, setup_instructions, required_credentials, optional_credentials, display_order, created_at FROM channel_registry ORDER BY display_order ASC
`

func (q *Queries) ListChannelRegistry(ctx context.Context) ([]ChannelRegistry, error) {
	rows, err := q.db.QueryContext(ctx, listChannelRegistry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelRegistry
	for rows.Next() {
		var i ChannelRegistry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SetupInstructions,
			&i.RequiredCredentials,
			&i.OptionalCredentials,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, channel_type, is_enabled, connection_status, last_connected_at, last_error, message_count, created_at, updated_at FROM channels ORDER BY created_at DESC
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ChannelType,
			&i.IsEnabled,
			&i.ConnectionStatus,
			&i.LastConnectedAt,
			&i.LastError,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChannels = `-- name: ListEnabledChannels :many
SELECT id, name, channel_type, is_enabled, connection_status, last_connected_at, last_error, message_count, created_at, updated_at FROM channels WHERE is_enabled = 1 ORDER BY created_at DESC
`

func (q *Queries) ListEnabledChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ChannelType,
			&i.IsEnabled,
			&i.ConnectionStatus,
			&i.LastConnectedAt,
			&i.LastError,
			&i.MessageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = ?, is_enabled = ?, updated_at = unixepoch()
WHERE id = ?
RETURNING id, name, channel_type, is_enabled, connection_status, last_connected_at, last_error, message_count, created_at, updated_at
`

type UpdateChannelParams struct {
	Name      string        `json:"name"`
	IsEnabled sql.NullInt64 `json:"is_enabled"`
	ID        string        `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateChannel, arg.Name, arg.IsEnabled, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.IsEnabled,
		&i.ConnectionStatus,
		&i.LastConnectedAt,
		&i.LastError,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChannelStatus = `-- name: UpdateChannelStatus :exec
UPDATE channels
SET connection_status = ?, last_connected_at = ?, last_error = ?, updated_at = unixepoch()
WHERE id = ?
`

type UpdateChannelStatusParams struct {
	ConnectionStatus sql.NullString `json:"connection_status"`
	LastConnectedAt  sql.NullInt64  `json:"last_connected_at"`
	LastError        sql.NullString `json:"last_error"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateChannelStatus(ctx context.Context, arg UpdateChannelStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateChannelStatus,
		arg.ConnectionStatus,
		arg.LastConnectedAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const upsertChannelConfig = `-- name: UpsertChannelConfig :one
INSERT INTO channel_config (id, channel_id, config_key, config_value, created_at, updated_at)
VALUES (?, ?, ?, ?, unixepoch(), unixepoch())
ON CONFLICT(channel_id, config_key) DO UPDATE SET
    config_value = excluded.config_value,
    updated_at = unixepoch()
RETURNING id, channel_id, config_key, config_value, created_at, updated_at
`

type UpsertChannelConfigParams struct {
	ID          string `json:"id"`
	ChannelID   string `json:"channel_id"`
	ConfigKey   string `json:"config_key"`
	ConfigValue string `json:"config_value"`
}

func (q *Queries) UpsertChannelConfig(ctx context.Context, arg UpsertChannelConfigParams) (ChannelConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertChannelConfig,
		arg.ID,
		arg.ChannelID,
		arg.ConfigKey,
		arg.ConfigValue,
	)
	var i ChannelConfig
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChannelCredential = `-- name: UpsertChannelCredential :one
INSERT INTO channel_credentials (id, channel_id, credential_key, credential_value, created_at, updated_at)
VALUES (?, ?, ?, ?, unixepoch(), unixepoch())
ON CONFLICT(channel_id, credential_key) DO UPDATE SET
    credential_value = excluded.credential_value,
    updated_at = unixepoch()
RETURNING id, channel_id, credential_key, credential_value, created_at, updated_at
`

type UpsertChannelCredentialParams struct {
	ID              string `json:"id"`
	ChannelID       string `json:"channel_id"`
	CredentialKey   string `json:"credential_key"`
	CredentialValue string `json:"credential_value"`
}

func (q *Queries) UpsertChannelCredential(ctx context.Context, arg UpsertChannelCredentialParams) (ChannelCredential, error) {
	row := q.db.QueryRowContext(ctx, upsertChannelCredential,
		arg.ID,
		arg.ChannelID,
		arg.CredentialKey,
		arg.CredentialValue,
	)
	var i ChannelCredential
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.CredentialKey,
		&i.CredentialValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
