// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cron_jobs.sql

package db

import (
	"context"
	"database/sql"
)

const countCronHistory = `-- name: CountCronHistory :one
SELECT COUNT(*) as total FROM cron_history WHERE job_id = ?
`

func (q *Queries) CountCronHistory(ctx context.Context, jobID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCronHistory, jobID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countCronJobs = `-- name: CountCronJobs :one
SELECT COUNT(*) as total FROM cron_jobs
`

func (q *Queries) CountCronJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCronJobs)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCronHistory = `-- name: CreateCronHistory :one

INSERT INTO cron_history (job_id, started_at)
VALUES (?, CURRENT_TIMESTAMP)
RETURNING id, job_id, started_at, finished_at, success, output, error
`

// Cron history queries
func (q *Queries) CreateCronHistory(ctx context.Context, jobID int64) (CronHistory, error) {
	row := q.db.QueryRowContext(ctx, createCronHistory, jobID)
	var i CronHistory
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Success,
		&i.Output,
		&i.Error,
	)
	return i, err
}

const createCronJob = `-- name: CreateCronJob :one
INSERT INTO cron_jobs (name, schedule, command, task_type, message, deliver, instructions, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, schedule, command, task_type, message, deliver, instructions, enabled, last_run, run_count, last_error, created_at
`

type CreateCronJobParams struct {
	Name         string         `json:"name"`
	Schedule     string         `json:"schedule"`
	Command      string         `json:"command"`
	TaskType     string         `json:"task_type"`
	Message      sql.NullString `json:"message"`
	Deliver      sql.NullString `json:"deliver"`
	Instructions sql.NullString `json:"instructions"`
	Enabled      sql.NullInt64  `json:"enabled"`
}

type CreateCronJobRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Schedule     string         `json:"schedule"`
	Command      string         `json:"command"`
	TaskType     string         `json:"task_type"`
	Message      sql.NullString `json:"message"`
	Deliver      sql.NullString `json:"deliver"`
	Instructions sql.NullString `json:"instructions"`
	Enabled      sql.NullInt64  `json:"enabled"`
	LastRun      sql.NullTime   `json:"last_run"`
	RunCount     sql.NullInt64  `json:"run_count"`
	LastError    sql.NullString `json:"last_error"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateCronJob(ctx context.Context, arg CreateCronJobParams) (CreateCronJobRow, error) {
	row := q.db.QueryRowContext(ctx, createCronJob,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.TaskType,
		arg.Message,
		arg.Deliver,
		arg.Instructions,
		arg.Enabled,
	)
	var i CreateCronJobRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.TaskType,
		&i.Message,
		&i.Deliver,
		&i.Instructions,
		&i.Enabled,
		&i.LastRun,
		&i.RunCount,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCronJob = `-- name: DeleteCronJob :exec
DELETE FROM cron_jobs WHERE id = ?
`

func (q *Queries) DeleteCronJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCronJob, id)
	return err
}

const deleteCronJobByName = `-- name: DeleteCronJobByName :execresult

DELETE FROM cron_jobs WHERE name = ?
`

// Agent tool queries (operations by name for CLI/tool use)
func (q *Queries) DeleteCronJobByName(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCronJobByName, name)
}

const disableCronJobByName = `-- name: DisableCronJobByName :execresult
UPDATE cron_jobs SET enabled = 0 WHERE name = ?
`

func (q *Queries) DisableCronJobByName(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableCronJobByName, name)
}

const enableCronJobByName = `-- name: EnableCronJobByName :exec
UPDATE cron_jobs SET enabled = 1 WHERE name = ?
`

func (q *Queries) EnableCronJobByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, enableCronJobByName, name)
	return err
}

const getCronJob = `-- name: GetCronJob :one
SELECT id, name, schedule, command, task_type, message, deliver, instructions, enabled, last_run, run_count, last_error, created_at
FROM cron_jobs
WHERE id = ?
`

type GetCronJobRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Schedule     string         `json:"schedule"`
	Command      string         `json:"command"`
	TaskType     string         `json:"task_type"`
	Message      sql.NullString `json:"message"`
	Deliver      sql.NullString `json:"deliver"`
	Instructions sql.NullString `json:"instructions"`
	Enabled      sql.NullInt64  `json:"enabled"`
	LastRun      sql.NullTime   `json:"last_run"`
	RunCount     sql.NullInt64  `json:"run_count"`
	LastError    sql.NullString `json:"last_error"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetCronJob(ctx context.Context, id int64) (GetCronJobRow, error) {
	row := q.db.QueryRowContext(ctx, getCronJob, id)
	var i GetCronJobRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.TaskType,
		&i.Message,
		&i.Deliver,
		&i.Instructions,
		&i.Enabled,
		&i.LastRun,
		&i.RunCount,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getCronJobByName = `-- name: GetCronJobByName :one
SELECT id, name, schedule, command, task_type, message, deliver, instructions, enabled, last_run, run_count, last_error, created_at
FROM cron_jobs
WHERE name = ?
`

type GetCronJobByNameRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Schedule     string         `json:"schedule"`
	Command      string         `json:"command"`
	TaskType     string         `json:"task_type"`
	Message      sql.NullString `json:"message"`
	Deliver      sql.NullString `json:"deliver"`
	Instructions sql.NullString `json:"instructions"`
	Enabled      sql.NullInt64  `json:"enabled"`
	LastRun      sql.NullTime   `json:"last_run"`
	RunCount     sql.NullInt64  `json:"run_count"`
	LastError    sql.NullString `json:"last_error"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetCronJobByName(ctx context.Context, name string) (GetCronJobByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getCronJobByName, name)
	var i GetCronJobByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Schedule,
		&i.Command,
		&i.TaskType,
		&i.Message,
		&i.Deliver,
		&i.Instructions,
		&i.Enabled,
		&i.LastRun,
		&i.RunCount,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentCronHistory = `-- name: GetRecentCronHistory :many
SELECT id, job_id, started_at, finished_at, success, output, error
FROM cron_history
WHERE job_id = ?
ORDER BY started_at DESC
LIMIT 10
`

func (q *Queries) GetRecentCronHistory(ctx context.Context, jobID int64) ([]CronHistory, error) {
	rows, err := q.db.QueryContext(ctx, getRecentCronHistory, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CronHistory
	for rows.Next() {
		var i CronHistory
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Success,
			&i.Output,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentCronHistoryByJobName = `-- name: GetRecentCronHistoryByJobName :many
SELECT h.id, h.job_id, h.started_at, h.finished_at, h.success, h.output, h.error
FROM cron_history h
JOIN cron_jobs j ON j.id = h.job_id
WHERE j.name = ?
ORDER BY h.started_at DESC
LIMIT 10
`

func (q *Queries) GetRecentCronHistoryByJobName(ctx context.Context, name string) ([]CronHistory, error) {
	rows, err := q.db.QueryContext(ctx, getRecentCronHistoryByJobName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CronHistory
	for rows.Next() {
		var i CronHistory
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Success,
			&i.Output,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronHistory = `-- name: ListCronHistory :many
SELECT id, job_id, started_at, finished_at, success, output, error
FROM cron_history
WHERE job_id = ?
ORDER BY started_at DESC
LIMIT ?3 OFFSET ?2
`

type ListCronHistoryParams struct {
	JobID  int64 `json:"job_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCronHistory(ctx context.Context, arg ListCronHistoryParams) ([]CronHistory, error) {
	rows, err := q.db.QueryContext(ctx, listCronHistory, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CronHistory
	for rows.Next() {
		var i CronHistory
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Success,
			&i.Output,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronJobs = `-- name: ListCronJobs :many

SELECT id, name, schedule, command, task_type, message, deliver, instructions, enabled, last_run, run_count, last_error, created_at
FROM cron_jobs
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListCronJobsParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListCronJobsRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Schedule     string         `json:"schedule"`
	Command      string         `json:"command"`
	TaskType     string         `json:"task_type"`
	Message      sql.NullString `json:"message"`
	Deliver      sql.NullString `json:"deliver"`
	Instructions sql.NullString `json:"instructions"`
	Enabled      sql.NullInt64  `json:"enabled"`
	LastRun      sql.NullTime   `json:"last_run"`
	RunCount     sql.NullInt64  `json:"run_count"`
	LastError    sql.NullString `json:"last_error"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

// Cron job queries
func (q *Queries) ListCronJobs(ctx context.Context, arg ListCronJobsParams) ([]ListCronJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCronJobs, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCronJobsRow
	for rows.Next() {
		var i ListCronJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.TaskType,
			&i.Message,
			&i.Deliver,
			&i.Instructions,
			&i.Enabled,
			&i.LastRun,
			&i.RunCount,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledCronJobs = `-- name: ListEnabledCronJobs :many
SELECT id, name, schedule, command, task_type, message, deliver, instructions, enabled, last_run, run_count, last_error, created_at
FROM cron_jobs
WHERE enabled = 1
ORDER BY name
`

type ListEnabledCronJobsRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Schedule     string         `json:"schedule"`
	Command      string         `json:"command"`
	TaskType     string         `json:"task_type"`
	Message      sql.NullString `json:"message"`
	Deliver      sql.NullString `json:"deliver"`
	Instructions sql.NullString `json:"instructions"`
	Enabled      sql.NullInt64  `json:"enabled"`
	LastRun      sql.NullTime   `json:"last_run"`
	RunCount     sql.NullInt64  `json:"run_count"`
	LastError    sql.NullString `json:"last_error"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

func (q *Queries) ListEnabledCronJobs(ctx context.Context) ([]ListEnabledCronJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledCronJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledCronJobsRow
	for rows.Next() {
		var i ListEnabledCronJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Schedule,
			&i.Command,
			&i.TaskType,
			&i.Message,
			&i.Deliver,
			&i.Instructions,
			&i.Enabled,
			&i.LastRun,
			&i.RunCount,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCronJobEnabled = `-- name: SetCronJobEnabled :exec
UPDATE cron_jobs
SET enabled = ?
WHERE id = ?
`

type SetCronJobEnabledParams struct {
	Enabled sql.NullInt64 `json:"enabled"`
	ID      int64         `json:"id"`
}

func (q *Queries) SetCronJobEnabled(ctx context.Context, arg SetCronJobEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setCronJobEnabled, arg.Enabled, arg.ID)
	return err
}

const toggleCronJob = `-- name: ToggleCronJob :exec
UPDATE cron_jobs
SET enabled = NOT enabled
WHERE id = ?
`

func (q *Queries) ToggleCronJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, toggleCronJob, id)
	return err
}

const updateCronHistory = `-- name: UpdateCronHistory :exec
UPDATE cron_history
SET finished_at = CURRENT_TIMESTAMP,
    success = ?,
    output = ?,
    error = ?
WHERE id = ?
`

type UpdateCronHistoryParams struct {
	Success sql.NullInt64  `json:"success"`
	Output  sql.NullString `json:"output"`
	Error   sql.NullString `json:"error"`
	ID      int64          `json:"id"`
}

func (q *Queries) UpdateCronHistory(ctx context.Context, arg UpdateCronHistoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCronHistory,
		arg.Success,
		arg.Output,
		arg.Error,
		arg.ID,
	)
	return err
}

const updateCronJob = `-- name: UpdateCronJob :exec
UPDATE cron_jobs
SET name = COALESCE(?1, name),
    schedule = COALESCE(?2, schedule),
    command = COALESCE(?3, command),
    task_type = COALESCE(?4, task_type),
    message = COALESCE(?5, message),
    deliver = COALESCE(?6, deliver)
WHERE id = ?7
`

type UpdateCronJobParams struct {
	Name     sql.NullString `json:"name"`
	Schedule sql.NullString `json:"schedule"`
	Command  sql.NullString `json:"command"`
	TaskType sql.NullString `json:"task_type"`
	Message  sql.NullString `json:"message"`
	Deliver  sql.NullString `json:"deliver"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateCronJob(ctx context.Context, arg UpdateCronJobParams) error {
	_, err := q.db.ExecContext(ctx, updateCronJob,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.TaskType,
		arg.Message,
		arg.Deliver,
		arg.ID,
	)
	return err
}

const updateCronJobLastRun = `-- name: UpdateCronJobLastRun :exec
UPDATE cron_jobs
SET last_run = CURRENT_TIMESTAMP,
    run_count = run_count + 1,
    last_error = ?1
WHERE id = ?2
`

type UpdateCronJobLastRunParams struct {
	LastError sql.NullString `json:"last_error"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateCronJobLastRun(ctx context.Context, arg UpdateCronJobLastRunParams) error {
	_, err := q.db.ExecContext(ctx, updateCronJobLastRun, arg.LastError, arg.ID)
	return err
}

const updateCronJobLastRunByName = `-- name: UpdateCronJobLastRunByName :exec
UPDATE cron_jobs
SET last_run = CURRENT_TIMESTAMP,
    run_count = run_count + 1,
    last_error = ?1
WHERE name = ?2
`

type UpdateCronJobLastRunByNameParams struct {
	LastError sql.NullString `json:"last_error"`
	Name      string         `json:"name"`
}

func (q *Queries) UpdateCronJobLastRunByName(ctx context.Context, arg UpdateCronJobLastRunByNameParams) error {
	_, err := q.db.ExecContext(ctx, updateCronJobLastRunByName, arg.LastError, arg.Name)
	return err
}

const upsertCronJob = `-- name: UpsertCronJob :exec
INSERT INTO cron_jobs (name, schedule, command, task_type, message, deliver, instructions, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    schedule = excluded.schedule,
    command = excluded.command,
    task_type = excluded.task_type,
    message = excluded.message,
    deliver = excluded.deliver,
    instructions = excluded.instructions
`

type UpsertCronJobParams struct {
	Name         string         `json:"name"`
	Schedule     string         `json:"schedule"`
	Command      string         `json:"command"`
	TaskType     string         `json:"task_type"`
	Message      sql.NullString `json:"message"`
	Deliver      sql.NullString `json:"deliver"`
	Instructions sql.NullString `json:"instructions"`
	Enabled      sql.NullInt64  `json:"enabled"`
}

func (q *Queries) UpsertCronJob(ctx context.Context, arg UpsertCronJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertCronJob,
		arg.Name,
		arg.Schedule,
		arg.Command,
		arg.TaskType,
		arg.Message,
		arg.Deliver,
		arg.Instructions,
		arg.Enabled,
	)
	return err
}
