// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dev_mode.sql

package db

import (
	"context"
)

const deleteDevSideloadedApp = `-- name: DeleteDevSideloadedApp :exec
DELETE FROM dev_sideloaded_apps WHERE app_id = ?
`

func (q *Queries) DeleteDevSideloadedApp(ctx context.Context, appID string) error {
	_, err := q.db.ExecContext(ctx, deleteDevSideloadedApp, appID)
	return err
}

const getDevSideloadedApp = `-- name: GetDevSideloadedApp :one
SELECT app_id, path, loaded_at FROM dev_sideloaded_apps WHERE app_id = ?
`

func (q *Queries) GetDevSideloadedApp(ctx context.Context, appID string) (DevSideloadedApp, error) {
	row := q.db.QueryRowContext(ctx, getDevSideloadedApp, appID)
	var i DevSideloadedApp
	err := row.Scan(&i.AppID, &i.Path, &i.LoadedAt)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT autonomous_mode, auto_approve_read, auto_approve_write, auto_approve_bash,
       heartbeat_interval_minutes, comm_enabled, comm_plugin, developer_mode, updated_at
FROM settings WHERE id = 1
`

type GetSettingsRow struct {
	AutonomousMode           int64  `json:"autonomous_mode"`
	AutoApproveRead          int64  `json:"auto_approve_read"`
	AutoApproveWrite         int64  `json:"auto_approve_write"`
	AutoApproveBash          int64  `json:"auto_approve_bash"`
	HeartbeatIntervalMinutes int64  `json:"heartbeat_interval_minutes"`
	CommEnabled              int64  `json:"comm_enabled"`
	CommPlugin               string `json:"comm_plugin"`
	DeveloperMode            int64  `json:"developer_mode"`
	UpdatedAt                int64  `json:"updated_at"`
}

func (q *Queries) GetSettings(ctx context.Context) (GetSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i GetSettingsRow
	err := row.Scan(
		&i.AutonomousMode,
		&i.AutoApproveRead,
		&i.AutoApproveWrite,
		&i.AutoApproveBash,
		&i.HeartbeatIntervalMinutes,
		&i.CommEnabled,
		&i.CommPlugin,
		&i.DeveloperMode,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDevSideloadedApp = `-- name: InsertDevSideloadedApp :exec
INSERT OR REPLACE INTO dev_sideloaded_apps (app_id, path) VALUES (?, ?)
`

type InsertDevSideloadedAppParams struct {
	AppID string `json:"app_id"`
	Path  string `json:"path"`
}

func (q *Queries) InsertDevSideloadedApp(ctx context.Context, arg InsertDevSideloadedAppParams) error {
	_, err := q.db.ExecContext(ctx, insertDevSideloadedApp, arg.AppID, arg.Path)
	return err
}

const listDevSideloadedApps = `-- name: ListDevSideloadedApps :many
SELECT app_id, path, loaded_at FROM dev_sideloaded_apps ORDER BY loaded_at DESC
`

func (q *Queries) ListDevSideloadedApps(ctx context.Context) ([]DevSideloadedApp, error) {
	rows, err := q.db.QueryContext(ctx, listDevSideloadedApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DevSideloadedApp
	for rows.Next() {
		var i DevSideloadedApp
		if err := rows.Scan(&i.AppID, &i.Path, &i.LoadedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings SET
    autonomous_mode = ?,
    auto_approve_read = ?,
    auto_approve_write = ?,
    auto_approve_bash = ?,
    heartbeat_interval_minutes = ?,
    comm_enabled = ?,
    comm_plugin = ?,
    developer_mode = ?,
    updated_at = strftime('%s', 'now')
WHERE id = 1
`

type UpdateSettingsParams struct {
	AutonomousMode           int64  `json:"autonomous_mode"`
	AutoApproveRead          int64  `json:"auto_approve_read"`
	AutoApproveWrite         int64  `json:"auto_approve_write"`
	AutoApproveBash          int64  `json:"auto_approve_bash"`
	HeartbeatIntervalMinutes int64  `json:"heartbeat_interval_minutes"`
	CommEnabled              int64  `json:"comm_enabled"`
	CommPlugin               string `json:"comm_plugin"`
	DeveloperMode            int64  `json:"developer_mode"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings,
		arg.AutonomousMode,
		arg.AutoApproveRead,
		arg.AutoApproveWrite,
		arg.AutoApproveBash,
		arg.HeartbeatIntervalMinutes,
		arg.CommEnabled,
		arg.CommPlugin,
		arg.DeveloperMode,
	)
	return err
}
