// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: error_logs.sql

package db

import (
	"context"
	"database/sql"
)

const clearOldErrorLogs = `-- name: ClearOldErrorLogs :exec
DELETE FROM error_logs WHERE timestamp < unixepoch() - ?
`

func (q *Queries) ClearOldErrorLogs(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.ExecContext(ctx, clearOldErrorLogs, dollar_1)
	return err
}

const countErrorLogs = `-- name: CountErrorLogs :one
SELECT COUNT(*) FROM error_logs WHERE resolved = 0
`

func (q *Queries) CountErrorLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countErrorLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertErrorLog = `-- name: InsertErrorLog :exec

INSERT INTO error_logs (level, module, message, stacktrace, context)
VALUES (?, ?, ?, ?, ?)
`

type InsertErrorLogParams struct {
	Level      string         `json:"level"`
	Module     string         `json:"module"`
	Message    string         `json:"message"`
	Stacktrace sql.NullString `json:"stacktrace"`
	Context    sql.NullString `json:"context"`
}

// Error log queries
func (q *Queries) InsertErrorLog(ctx context.Context, arg InsertErrorLogParams) error {
	_, err := q.db.ExecContext(ctx, insertErrorLog,
		arg.Level,
		arg.Module,
		arg.Message,
		arg.Stacktrace,
		arg.Context,
	)
	return err
}

const listErrorLogs = `-- name: ListErrorLogs :many
SELECT id, timestamp, level, module, message, stacktrace, context, resolved
FROM error_logs
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type ListErrorLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListErrorLogs(ctx context.Context, arg ListErrorLogsParams) ([]ErrorLog, error) {
	rows, err := q.db.QueryContext(ctx, listErrorLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErrorLog
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Level,
			&i.Module,
			&i.Message,
			&i.Stacktrace,
			&i.Context,
			&i.Resolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorLogsByLevel = `-- name: ListErrorLogsByLevel :many
SELECT id, timestamp, level, module, message, stacktrace, context, resolved
FROM error_logs
WHERE level = ?
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type ListErrorLogsByLevelParams struct {
	Level  string `json:"level"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListErrorLogsByLevel(ctx context.Context, arg ListErrorLogsByLevelParams) ([]ErrorLog, error) {
	rows, err := q.db.QueryContext(ctx, listErrorLogsByLevel, arg.Level, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErrorLog
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Level,
			&i.Module,
			&i.Message,
			&i.Stacktrace,
			&i.Context,
			&i.Resolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveErrorLog = `-- name: ResolveErrorLog :exec
UPDATE error_logs SET resolved = 1 WHERE id = ?
`

func (q *Queries) ResolveErrorLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resolveErrorLog, id)
	return err
}
