// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_integrations.sql

package db

import (
	"context"
	"database/sql"
)

const clearMCPIntegrationOAuthState = `-- name: ClearMCPIntegrationOAuthState :exec
UPDATE mcp_integrations SET
    oauth_state = NULL,
    oauth_pkce_verifier = NULL,
    updated_at = unixepoch()
WHERE id = ?
`

func (q *Queries) ClearMCPIntegrationOAuthState(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearMCPIntegrationOAuthState, id)
	return err
}

const createMCPIntegration = `-- name: CreateMCPIntegration :one
INSERT INTO mcp_integrations (id, name, server_type, server_url, auth_type, is_enabled, metadata, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, unixepoch(), unixepoch())
RETURNING id, name, server_type, server_url, auth_type, is_enabled, connection_status, last_connected_at, last_error, metadata, created_at, updated_at, oauth_state, oauth_pkce_verifier, oauth_client_id, oauth_client_secret, oauth_authorization_endpoint, oauth_token_endpoint, oauth_registration_endpoint
`

type CreateMCPIntegrationParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	ServerType string         `json:"server_type"`
	ServerUrl  sql.NullString `json:"server_url"`
	AuthType   string         `json:"auth_type"`
	IsEnabled  sql.NullInt64  `json:"is_enabled"`
	Metadata   sql.NullString `json:"metadata"`
}

func (q *Queries) CreateMCPIntegration(ctx context.Context, arg CreateMCPIntegrationParams) (McpIntegration, error) {
	row := q.db.QueryRowContext(ctx, createMCPIntegration,
		arg.ID,
		arg.Name,
		arg.ServerType,
		arg.ServerUrl,
		arg.AuthType,
		arg.IsEnabled,
		arg.Metadata,
	)
	var i McpIntegration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServerType,
		&i.ServerUrl,
		&i.AuthType,
		&i.IsEnabled,
		&i.ConnectionStatus,
		&i.LastConnectedAt,
		&i.LastError,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthState,
		&i.OauthPkceVerifier,
		&i.OauthClientID,
		&i.OauthClientSecret,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthRegistrationEndpoint,
	)
	return i, err
}

const createMCPIntegrationCredential = `-- name: CreateMCPIntegrationCredential :one
INSERT INTO mcp_integration_credentials (id, integration_id, credential_type, credential_value, refresh_token, expires_at, scopes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, unixepoch(), unixepoch())
RETURNING id, integration_id, credential_type, credential_value, refresh_token, expires_at, scopes, created_at, updated_at
`

type CreateMCPIntegrationCredentialParams struct {
	ID              string         `json:"id"`
	IntegrationID   string         `json:"integration_id"`
	CredentialType  string         `json:"credential_type"`
	CredentialValue string         `json:"credential_value"`
	RefreshToken    sql.NullString `json:"refresh_token"`
	ExpiresAt       sql.NullInt64  `json:"expires_at"`
	Scopes          sql.NullString `json:"scopes"`
}

func (q *Queries) CreateMCPIntegrationCredential(ctx context.Context, arg CreateMCPIntegrationCredentialParams) (McpIntegrationCredential, error) {
	row := q.db.QueryRowContext(ctx, createMCPIntegrationCredential,
		arg.ID,
		arg.IntegrationID,
		arg.CredentialType,
		arg.CredentialValue,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var i McpIntegrationCredential
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.CredentialType,
		&i.CredentialValue,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPIntegration = `-- name: DeleteMCPIntegration :exec
DELETE FROM mcp_integrations WHERE id = ?
`

func (q *Queries) DeleteMCPIntegration(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMCPIntegration, id)
	return err
}

const deleteMCPIntegrationCredentials = `-- name: DeleteMCPIntegrationCredentials :exec
DELETE FROM mcp_integration_credentials WHERE integration_id = ?
`

func (q *Queries) DeleteMCPIntegrationCredentials(ctx context.Context, integrationID string) error {
	_, err := q.db.ExecContext(ctx, deleteMCPIntegrationCredentials, integrationID)
	return err
}

const getMCPIntegration = `-- name: GetMCPIntegration :one
SELECT id, name, server_type, server_url, auth_type, is_enabled, connection_status, last_connected_at, last_error, metadata, created_at, updated_at, oauth_state, oauth_pkce_verifier, oauth_client_id, oauth_client_secret, oauth_authorization_endpoint, oauth_token_endpoint, oauth_registration_endpoint FROM mcp_integrations WHERE id = ?
`

func (q *Queries) GetMCPIntegration(ctx context.Context, id string) (McpIntegration, error) {
	row := q.db.QueryRowContext(ctx, getMCPIntegration, id)
	var i McpIntegration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServerType,
		&i.ServerUrl,
		&i.AuthType,
		&i.IsEnabled,
		&i.ConnectionStatus,
		&i.LastConnectedAt,
		&i.LastError,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthState,
		&i.OauthPkceVerifier,
		&i.OauthClientID,
		&i.OauthClientSecret,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthRegistrationEndpoint,
	)
	return i, err
}

const getMCPIntegrationByOAuthState = `-- name: GetMCPIntegrationByOAuthState :one
SELECT id, name, server_type, server_url, auth_type, is_enabled, connection_status, last_connected_at, last_error, metadata, created_at, updated_at, oauth_state, oauth_pkce_verifier, oauth_client_id, oauth_client_secret, oauth_authorization_endpoint, oauth_token_endpoint, oauth_registration_endpoint FROM mcp_integrations WHERE oauth_state = ? AND oauth_state IS NOT NULL
`

func (q *Queries) GetMCPIntegrationByOAuthState(ctx context.Context, oauthState sql.NullString) (McpIntegration, error) {
	row := q.db.QueryRowContext(ctx, getMCPIntegrationByOAuthState, oauthState)
	var i McpIntegration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServerType,
		&i.ServerUrl,
		&i.AuthType,
		&i.IsEnabled,
		&i.ConnectionStatus,
		&i.LastConnectedAt,
		&i.LastError,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthState,
		&i.OauthPkceVerifier,
		&i.OauthClientID,
		&i.OauthClientSecret,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthRegistrationEndpoint,
	)
	return i, err
}

const getMCPIntegrationByType = `-- name: GetMCPIntegrationByType :one
SELECT id, name, server_type, server_url, auth_type, is_enabled, connection_status, last_connected_at, last_error, metadata, created_at, updated_at, oauth_state, oauth_pkce_verifier, oauth_client_id, oauth_client_secret, oauth_authorization_endpoint, oauth_token_endpoint, oauth_registration_endpoint FROM mcp_integrations WHERE server_type = ? AND is_enabled = 1 LIMIT 1
`

func (q *Queries) GetMCPIntegrationByType(ctx context.Context, serverType string) (McpIntegration, error) {
	row := q.db.QueryRowContext(ctx, getMCPIntegrationByType, serverType)
	var i McpIntegration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServerType,
		&i.ServerUrl,
		&i.AuthType,
		&i.IsEnabled,
		&i.ConnectionStatus,
		&i.LastConnectedAt,
		&i.LastError,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthState,
		&i.OauthPkceVerifier,
		&i.OauthClientID,
		&i.OauthClientSecret,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthRegistrationEndpoint,
	)
	return i, err
}

const getMCPIntegrationCredential = `-- name: GetMCPIntegrationCredential :one
SELECT id, integration_id, credential_type, credential_value, refresh_token, expires_at, scopes, created_at, updated_at FROM mcp_integration_credentials WHERE integration_id = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetMCPIntegrationCredential(ctx context.Context, integrationID string) (McpIntegrationCredential, error) {
	row := q.db.QueryRowContext(ctx, getMCPIntegrationCredential, integrationID)
	var i McpIntegrationCredential
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.CredentialType,
		&i.CredentialValue,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPIntegrationOAuthConfig = `-- name: GetMCPIntegrationOAuthConfig :one
SELECT id, oauth_client_id, oauth_client_secret, oauth_authorization_endpoint, oauth_token_endpoint, oauth_pkce_verifier, oauth_state
FROM mcp_integrations WHERE id = ?
`

type GetMCPIntegrationOAuthConfigRow struct {
	ID                         string         `json:"id"`
	OauthClientID              sql.NullString `json:"oauth_client_id"`
	OauthClientSecret          sql.NullString `json:"oauth_client_secret"`
	OauthAuthorizationEndpoint sql.NullString `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString `json:"oauth_token_endpoint"`
	OauthPkceVerifier          sql.NullString `json:"oauth_pkce_verifier"`
	OauthState                 sql.NullString `json:"oauth_state"`
}

func (q *Queries) GetMCPIntegrationOAuthConfig(ctx context.Context, id string) (GetMCPIntegrationOAuthConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getMCPIntegrationOAuthConfig, id)
	var i GetMCPIntegrationOAuthConfigRow
	err := row.Scan(
		&i.ID,
		&i.OauthClientID,
		&i.OauthClientSecret,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthPkceVerifier,
		&i.OauthState,
	)
	return i, err
}

const getMCPServerRegistry = `-- name: GetMCPServerRegistry :one
SELECT id, name, description, icon, auth_type, oauth_authorize_url, oauth_token_url, oauth_scopes, api_key_url, api_key_placeholder, default_server_url, is_builtin, display_order, created_at FROM mcp_server_registry WHERE id = ?
`

func (q *Queries) GetMCPServerRegistry(ctx context.Context, id string) (McpServerRegistry, error) {
	row := q.db.QueryRowContext(ctx, getMCPServerRegistry, id)
	var i McpServerRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.AuthType,
		&i.OauthAuthorizeUrl,
		&i.OauthTokenUrl,
		&i.OauthScopes,
		&i.ApiKeyUrl,
		&i.ApiKeyPlaceholder,
		&i.DefaultServerUrl,
		&i.IsBuiltin,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledMCPIntegrations = `-- name: ListEnabledMCPIntegrations :many
SELECT id, name, server_type, server_url, auth_type, is_enabled, connection_status, last_connected_at, last_error, metadata, created_at, updated_at, oauth_state, oauth_pkce_verifier, oauth_client_id, oauth_client_secret, oauth_authorization_endpoint, oauth_token_endpoint, oauth_registration_endpoint FROM mcp_integrations WHERE is_enabled = 1 ORDER BY created_at DESC
`

func (q *Queries) ListEnabledMCPIntegrations(ctx context.Context) ([]McpIntegration, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledMCPIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpIntegration
	for rows.Next() {
		var i McpIntegration
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ServerType,
			&i.ServerUrl,
			&i.AuthType,
			&i.IsEnabled,
			&i.ConnectionStatus,
			&i.LastConnectedAt,
			&i.LastError,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OauthState,
			&i.OauthPkceVerifier,
			&i.OauthClientID,
			&i.OauthClientSecret,
			&i.OauthAuthorizationEndpoint,
			&i.OauthTokenEndpoint,
			&i.OauthRegistrationEndpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPIntegrations = `-- name: ListMCPIntegrations :many
SELECT id, name, server_type, server_url, auth_type, is_enabled, connection_status, last_connected_at, last_error, metadata, created_at, updated_at, oauth_state, oauth_pkce_verifier, oauth_client_id, oauth_client_secret, oauth_authorization_endpoint, oauth_token_endpoint, oauth_registration_endpoint FROM mcp_integrations ORDER BY created_at DESC
`

func (q *Queries) ListMCPIntegrations(ctx context.Context) ([]McpIntegration, error) {
	rows, err := q.db.QueryContext(ctx, listMCPIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpIntegration
	for rows.Next() {
		var i McpIntegration
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ServerType,
			&i.ServerUrl,
			&i.AuthType,
			&i.IsEnabled,
			&i.ConnectionStatus,
			&i.LastConnectedAt,
			&i.LastError,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OauthState,
			&i.OauthPkceVerifier,
			&i.OauthClientID,
			&i.OauthClientSecret,
			&i.OauthAuthorizationEndpoint,
			&i.OauthTokenEndpoint,
			&i.OauthRegistrationEndpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServerRegistry = `-- name: ListMCPServerRegistry :many
SELECT id, name, description, icon, auth_type, oauth_authorize_url, oauth_token_url, oauth_scopes, api_key_url, api_key_placeholder, default_server_url, is_builtin, display_order, created_at FROM mcp_server_registry ORDER BY display_order ASC
`

func (q *Queries) ListMCPServerRegistry(ctx context.Context) ([]McpServerRegistry, error) {
	rows, err := q.db.QueryContext(ctx, listMCPServerRegistry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServerRegistry
	for rows.Next() {
		var i McpServerRegistry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.AuthType,
			&i.OauthAuthorizeUrl,
			&i.OauthTokenUrl,
			&i.OauthScopes,
			&i.ApiKeyUrl,
			&i.ApiKeyPlaceholder,
			&i.DefaultServerUrl,
			&i.IsBuiltin,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMCPIntegration = `-- name: UpdateMCPIntegration :one
UPDATE mcp_integrations
SET name = ?, server_url = ?, is_enabled = ?, metadata = ?, updated_at = unixepoch()
WHERE id = ?
RETURNING id, name, server_type, server_url, auth_type, is_enabled, connection_status, last_connected_at, last_error, metadata, created_at, updated_at, oauth_state, oauth_pkce_verifier, oauth_client_id, oauth_client_secret, oauth_authorization_endpoint, oauth_token_endpoint, oauth_registration_endpoint
`

type UpdateMCPIntegrationParams struct {
	Name      string         `json:"name"`
	ServerUrl sql.NullString `json:"server_url"`
	IsEnabled sql.NullInt64  `json:"is_enabled"`
	Metadata  sql.NullString `json:"metadata"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateMCPIntegration(ctx context.Context, arg UpdateMCPIntegrationParams) (McpIntegration, error) {
	row := q.db.QueryRowContext(ctx, updateMCPIntegration,
		arg.Name,
		arg.ServerUrl,
		arg.IsEnabled,
		arg.Metadata,
		arg.ID,
	)
	var i McpIntegration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServerType,
		&i.ServerUrl,
		&i.AuthType,
		&i.IsEnabled,
		&i.ConnectionStatus,
		&i.LastConnectedAt,
		&i.LastError,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthState,
		&i.OauthPkceVerifier,
		&i.OauthClientID,
		&i.OauthClientSecret,
		&i.OauthAuthorizationEndpoint,
		&i.OauthTokenEndpoint,
		&i.OauthRegistrationEndpoint,
	)
	return i, err
}

const updateMCPIntegrationConnectionStatus = `-- name: UpdateMCPIntegrationConnectionStatus :exec
UPDATE mcp_integrations SET
    connection_status = ?,
    last_connected_at = CASE WHEN ? = 'connected' THEN unixepoch() ELSE last_connected_at END,
    last_error = ?,
    updated_at = unixepoch()
WHERE id = ?
`

type UpdateMCPIntegrationConnectionStatusParams struct {
	ConnectionStatus sql.NullString `json:"connection_status"`
	Column2          interface{}    `json:"column_2"`
	LastError        sql.NullString `json:"last_error"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateMCPIntegrationConnectionStatus(ctx context.Context, arg UpdateMCPIntegrationConnectionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPIntegrationConnectionStatus,
		arg.ConnectionStatus,
		arg.Column2,
		arg.LastError,
		arg.ID,
	)
	return err
}

const updateMCPIntegrationCredential = `-- name: UpdateMCPIntegrationCredential :exec
UPDATE mcp_integration_credentials
SET credential_value = ?, refresh_token = ?, expires_at = ?, scopes = ?, updated_at = unixepoch()
WHERE id = ?
`

type UpdateMCPIntegrationCredentialParams struct {
	CredentialValue string         `json:"credential_value"`
	RefreshToken    sql.NullString `json:"refresh_token"`
	ExpiresAt       sql.NullInt64  `json:"expires_at"`
	Scopes          sql.NullString `json:"scopes"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateMCPIntegrationCredential(ctx context.Context, arg UpdateMCPIntegrationCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPIntegrationCredential,
		arg.CredentialValue,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scopes,
		arg.ID,
	)
	return err
}

const updateMCPIntegrationOAuthFlow = `-- name: UpdateMCPIntegrationOAuthFlow :exec
UPDATE mcp_integrations SET
    oauth_state = ?,
    oauth_pkce_verifier = ?,
    oauth_client_id = ?,
    oauth_client_secret = ?,
    oauth_authorization_endpoint = ?,
    oauth_token_endpoint = ?,
    updated_at = unixepoch()
WHERE id = ?
`

type UpdateMCPIntegrationOAuthFlowParams struct {
	OauthState                 sql.NullString `json:"oauth_state"`
	OauthPkceVerifier          sql.NullString `json:"oauth_pkce_verifier"`
	OauthClientID              sql.NullString `json:"oauth_client_id"`
	OauthClientSecret          sql.NullString `json:"oauth_client_secret"`
	OauthAuthorizationEndpoint sql.NullString `json:"oauth_authorization_endpoint"`
	OauthTokenEndpoint         sql.NullString `json:"oauth_token_endpoint"`
	ID                         string         `json:"id"`
}

func (q *Queries) UpdateMCPIntegrationOAuthFlow(ctx context.Context, arg UpdateMCPIntegrationOAuthFlowParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPIntegrationOAuthFlow,
		arg.OauthState,
		arg.OauthPkceVerifier,
		arg.OauthClientID,
		arg.OauthClientSecret,
		arg.OauthAuthorizationEndpoint,
		arg.OauthTokenEndpoint,
		arg.ID,
	)
	return err
}

const updateMCPIntegrationStatus = `-- name: UpdateMCPIntegrationStatus :exec
UPDATE mcp_integrations
SET connection_status = ?, last_connected_at = ?, last_error = ?, updated_at = unixepoch()
WHERE id = ?
`

type UpdateMCPIntegrationStatusParams struct {
	ConnectionStatus sql.NullString `json:"connection_status"`
	LastConnectedAt  sql.NullInt64  `json:"last_connected_at"`
	LastError        sql.NullString `json:"last_error"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateMCPIntegrationStatus(ctx context.Context, arg UpdateMCPIntegrationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPIntegrationStatus,
		arg.ConnectionStatus,
		arg.LastConnectedAt,
		arg.LastError,
		arg.ID,
	)
	return err
}
