// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_models.sql

package db

import (
	"context"
	"database/sql"
)

const createProviderModel = `-- name: CreateProviderModel :one
INSERT INTO provider_models (id, profile_id, model_id, display_name, is_active, is_default, context_window, input_price, output_price, capabilities, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, profile_id, model_id, display_name, is_active, is_default, context_window, input_price, output_price, capabilities, created_at, updated_at
`

type CreateProviderModelParams struct {
	ID            string          `json:"id"`
	ProfileID     string          `json:"profile_id"`
	ModelID       string          `json:"model_id"`
	DisplayName   string          `json:"display_name"`
	IsActive      sql.NullInt64   `json:"is_active"`
	IsDefault     sql.NullInt64   `json:"is_default"`
	ContextWindow sql.NullInt64   `json:"context_window"`
	InputPrice    sql.NullFloat64 `json:"input_price"`
	OutputPrice   sql.NullFloat64 `json:"output_price"`
	Capabilities  sql.NullString  `json:"capabilities"`
	CreatedAt     int64           `json:"created_at"`
	UpdatedAt     int64           `json:"updated_at"`
}

func (q *Queries) CreateProviderModel(ctx context.Context, arg CreateProviderModelParams) (ProviderModel, error) {
	row := q.db.QueryRowContext(ctx, createProviderModel,
		arg.ID,
		arg.ProfileID,
		arg.ModelID,
		arg.DisplayName,
		arg.IsActive,
		arg.IsDefault,
		arg.ContextWindow,
		arg.InputPrice,
		arg.OutputPrice,
		arg.Capabilities,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProviderModel
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ModelID,
		&i.DisplayName,
		&i.IsActive,
		&i.IsDefault,
		&i.ContextWindow,
		&i.InputPrice,
		&i.OutputPrice,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProviderModel = `-- name: DeleteProviderModel :exec
DELETE FROM provider_models WHERE id = ?
`

func (q *Queries) DeleteProviderModel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProviderModel, id)
	return err
}

const deleteProviderModelsByProfile = `-- name: DeleteProviderModelsByProfile :exec
DELETE FROM provider_models WHERE profile_id = ?
`

func (q *Queries) DeleteProviderModelsByProfile(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteProviderModelsByProfile, profileID)
	return err
}

const getDefaultModel = `-- name: GetDefaultModel :one
SELECT id, profile_id, model_id, display_name, is_active, is_default, context_window, input_price, output_price, capabilities, created_at, updated_at FROM provider_models WHERE profile_id = ? AND is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultModel(ctx context.Context, profileID string) (ProviderModel, error) {
	row := q.db.QueryRowContext(ctx, getDefaultModel, profileID)
	var i ProviderModel
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ModelID,
		&i.DisplayName,
		&i.IsActive,
		&i.IsDefault,
		&i.ContextWindow,
		&i.InputPrice,
		&i.OutputPrice,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderModel = `-- name: GetProviderModel :one
SELECT id, profile_id, model_id, display_name, is_active, is_default, context_window, input_price, output_price, capabilities, created_at, updated_at FROM provider_models WHERE id = ?
`

func (q *Queries) GetProviderModel(ctx context.Context, id string) (ProviderModel, error) {
	row := q.db.QueryRowContext(ctx, getProviderModel, id)
	var i ProviderModel
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ModelID,
		&i.DisplayName,
		&i.IsActive,
		&i.IsDefault,
		&i.ContextWindow,
		&i.InputPrice,
		&i.OutputPrice,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderModelByModelId = `-- name: GetProviderModelByModelId :one
SELECT id, profile_id, model_id, display_name, is_active, is_default, context_window, input_price, output_price, capabilities, created_at, updated_at FROM provider_models WHERE profile_id = ? AND model_id = ?
`

type GetProviderModelByModelIdParams struct {
	ProfileID string `json:"profile_id"`
	ModelID   string `json:"model_id"`
}

func (q *Queries) GetProviderModelByModelId(ctx context.Context, arg GetProviderModelByModelIdParams) (ProviderModel, error) {
	row := q.db.QueryRowContext(ctx, getProviderModelByModelId, arg.ProfileID, arg.ModelID)
	var i ProviderModel
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ModelID,
		&i.DisplayName,
		&i.IsActive,
		&i.IsDefault,
		&i.ContextWindow,
		&i.InputPrice,
		&i.OutputPrice,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveModels = `-- name: ListActiveModels :many
SELECT id, profile_id, model_id, display_name, is_active, is_default, context_window, input_price, output_price, capabilities, created_at, updated_at FROM provider_models WHERE profile_id = ? AND is_active = 1 ORDER BY display_name
`

func (q *Queries) ListActiveModels(ctx context.Context, profileID string) ([]ProviderModel, error) {
	rows, err := q.db.QueryContext(ctx, listActiveModels, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderModel
	for rows.Next() {
		var i ProviderModel
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ModelID,
			&i.DisplayName,
			&i.IsActive,
			&i.IsDefault,
			&i.ContextWindow,
			&i.InputPrice,
			&i.OutputPrice,
			&i.Capabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderModels = `-- name: ListProviderModels :many
SELECT id, profile_id, model_id, display_name, is_active, is_default, context_window, input_price, output_price, capabilities, created_at, updated_at FROM provider_models WHERE profile_id = ? ORDER BY display_name
`

func (q *Queries) ListProviderModels(ctx context.Context, profileID string) ([]ProviderModel, error) {
	rows, err := q.db.QueryContext(ctx, listProviderModels, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderModel
	for rows.Next() {
		var i ProviderModel
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ModelID,
			&i.DisplayName,
			&i.IsActive,
			&i.IsDefault,
			&i.ContextWindow,
			&i.InputPrice,
			&i.OutputPrice,
			&i.Capabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultModel = `-- name: SetDefaultModel :exec
UPDATE provider_models SET is_default = CASE WHEN id = ? THEN 1 ELSE 0 END, updated_at = ? WHERE profile_id = ?
`

type SetDefaultModelParams struct {
	ID        string `json:"id"`
	UpdatedAt int64  `json:"updated_at"`
	ProfileID string `json:"profile_id"`
}

func (q *Queries) SetDefaultModel(ctx context.Context, arg SetDefaultModelParams) error {
	_, err := q.db.ExecContext(ctx, setDefaultModel, arg.ID, arg.UpdatedAt, arg.ProfileID)
	return err
}

const updateProviderModelActive = `-- name: UpdateProviderModelActive :exec
UPDATE provider_models SET is_active = ?, updated_at = ? WHERE id = ?
`

type UpdateProviderModelActiveParams struct {
	IsActive  sql.NullInt64 `json:"is_active"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) UpdateProviderModelActive(ctx context.Context, arg UpdateProviderModelActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderModelActive, arg.IsActive, arg.UpdatedAt, arg.ID)
	return err
}
