// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profiles.sql

package db

import (
	"context"
	"database/sql"
)

const deleteUserProfile = `-- name: DeleteUserProfile :exec
DELETE FROM user_profiles WHERE user_id = ?
`

func (q *Queries) DeleteUserProfile(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserProfile, userID)
	return err
}

const getUserProfile = `-- name: GetUserProfile :one

SELECT user_id, display_name, bio, location, timezone, occupation, interests,
       communication_style, goals, context, onboarding_completed, onboarding_step,
       created_at, updated_at
FROM user_profiles
WHERE user_id = ?
`

// User profile queries
func (q *Queries) GetUserProfile(ctx context.Context, userID string) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.Location,
		&i.Timezone,
		&i.Occupation,
		&i.Interests,
		&i.CommunicationStyle,
		&i.Goals,
		&i.Context,
		&i.OnboardingCompleted,
		&i.OnboardingStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOnboardingCompleted = `-- name: SetOnboardingCompleted :exec
UPDATE user_profiles
SET onboarding_completed = 1,
    onboarding_step = NULL,
    updated_at = unixepoch()
WHERE user_id = ?
`

func (q *Queries) SetOnboardingCompleted(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, setOnboardingCompleted, userID)
	return err
}

const setOnboardingStep = `-- name: SetOnboardingStep :exec
UPDATE user_profiles
SET onboarding_step = ?,
    updated_at = unixepoch()
WHERE user_id = ?
`

type SetOnboardingStepParams struct {
	OnboardingStep sql.NullString `json:"onboarding_step"`
	UserID         string         `json:"user_id"`
}

func (q *Queries) SetOnboardingStep(ctx context.Context, arg SetOnboardingStepParams) error {
	_, err := q.db.ExecContext(ctx, setOnboardingStep, arg.OnboardingStep, arg.UserID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE user_profiles
SET display_name = COALESCE(?1, display_name),
    bio = COALESCE(?2, bio),
    location = COALESCE(?3, location),
    timezone = COALESCE(?4, timezone),
    occupation = COALESCE(?5, occupation),
    interests = COALESCE(?6, interests),
    communication_style = COALESCE(?7, communication_style),
    goals = COALESCE(?8, goals),
    context = COALESCE(?9, context),
    updated_at = unixepoch()
WHERE user_id = ?10
`

type UpdateUserProfileParams struct {
	DisplayName        sql.NullString `json:"display_name"`
	Bio                sql.NullString `json:"bio"`
	Location           sql.NullString `json:"location"`
	Timezone           sql.NullString `json:"timezone"`
	Occupation         sql.NullString `json:"occupation"`
	Interests          sql.NullString `json:"interests"`
	CommunicationStyle sql.NullString `json:"communication_style"`
	Goals              sql.NullString `json:"goals"`
	Context            sql.NullString `json:"context"`
	UserID             string         `json:"user_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Bio,
		arg.Location,
		arg.Timezone,
		arg.Occupation,
		arg.Interests,
		arg.CommunicationStyle,
		arg.Goals,
		arg.Context,
		arg.UserID,
	)
	return err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (user_id, display_name, bio, location, timezone, occupation,
                           interests, communication_style, goals, context,
                           onboarding_completed, onboarding_step, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, unixepoch(), unixepoch())
ON CONFLICT(user_id) DO UPDATE SET
    display_name = COALESCE(excluded.display_name, user_profiles.display_name),
    bio = COALESCE(excluded.bio, user_profiles.bio),
    location = COALESCE(excluded.location, user_profiles.location),
    timezone = COALESCE(excluded.timezone, user_profiles.timezone),
    occupation = COALESCE(excluded.occupation, user_profiles.occupation),
    interests = COALESCE(excluded.interests, user_profiles.interests),
    communication_style = COALESCE(excluded.communication_style, user_profiles.communication_style),
    goals = COALESCE(excluded.goals, user_profiles.goals),
    context = COALESCE(excluded.context, user_profiles.context),
    onboarding_completed = COALESCE(excluded.onboarding_completed, user_profiles.onboarding_completed),
    onboarding_step = COALESCE(excluded.onboarding_step, user_profiles.onboarding_step),
    updated_at = unixepoch()
RETURNING user_id, display_name, bio, location, timezone, occupation, interests, communication_style, goals, context, onboarding_completed, onboarding_step, created_at, updated_at
`

type UpsertUserProfileParams struct {
	UserID              string         `json:"user_id"`
	DisplayName         sql.NullString `json:"display_name"`
	Bio                 sql.NullString `json:"bio"`
	Location            sql.NullString `json:"location"`
	Timezone            sql.NullString `json:"timezone"`
	Occupation          sql.NullString `json:"occupation"`
	Interests           sql.NullString `json:"interests"`
	CommunicationStyle  sql.NullString `json:"communication_style"`
	Goals               sql.NullString `json:"goals"`
	Context             sql.NullString `json:"context"`
	OnboardingCompleted sql.NullInt64  `json:"onboarding_completed"`
	OnboardingStep      sql.NullString `json:"onboarding_step"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, upsertUserProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Bio,
		arg.Location,
		arg.Timezone,
		arg.Occupation,
		arg.Interests,
		arg.CommunicationStyle,
		arg.Goals,
		arg.Context,
		arg.OnboardingCompleted,
		arg.OnboardingStep,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Bio,
		&i.Location,
		&i.Timezone,
		&i.Occupation,
		&i.Interests,
		&i.CommunicationStyle,
		&i.Goals,
		&i.Context,
		&i.OnboardingCompleted,
		&i.OnboardingStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
