#!/usr/bin/env npx tsx
/**
 * Nebo API Code Generator
 *
 * Parses Rust backend route definitions and generates the TypeScript API client
 * (nebo.ts). Replaces the old Go-based genapi tool.
 *
 * Usage: pnpm run gen:api
 *
 * How it works:
 *   1. Scans all crates/server/src/routes/*.rs files for .route() definitions
 *   2. Reads api-catalog.json for type mappings (function name, request/response types)
 *   3. Generates src/lib/api/nebo.ts
 *   4. Reports any Rust routes missing from the catalog (new routes)
 *
 * When a new route is added in Rust:
 *   1. Run `pnpm run gen:api` — it will report the unmapped route
 *   2. Add an entry to api-catalog.json with the function name and types
 *   3. Run `pnpm run gen:api` again to regenerate
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

// ── Configuration ───────────────────────────────────────────────────────────

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = path.resolve(__dirname, "../..");
const ROUTES_DIR = path.join(ROOT, "crates/server/src/routes");
const CATALOG_PATH = path.join(__dirname, "api-catalog.json");
const OUTPUT_PATH = path.join(__dirname, "../src/lib/api/nebo.ts");

// ── Types ───────────────────────────────────────────────────────────────────

interface RustRoute {
	method: string; // GET, POST, PUT, DELETE, PATCH
	path: string; // /agent/sessions/{id}
	handler: string; // handlers::agent::list_sessions
	sourceFile: string; // agent.rs
}

interface CatalogEntry {
	/** TypeScript function name */
	fn: string;
	/** JSDoc description */
	desc?: string;
	/** Path parameter names and types (extracted from {param} in path) */
	pathParams?: Array<{ name: string; tsName?: string; type?: string }>;
	/** Query parameter type (e.g., "ListChatsRequestParams") */
	queryType?: string;
	/** Request body type for POST/PUT (e.g., "CreateChatRequest") */
	requestType?: string;
	/** Response type (e.g., "ListChatsResponse") */
	responseType?: string;
	/** Custom function body (overrides auto-generation) */
	customBody?: string;
	/** Skip code generation for this route */
	skip?: boolean;
}

interface Catalog {
	[routeKey: string]: CatalogEntry; // "GET /agent/sessions" -> entry
}

// ── Route Parser ────────────────────────────────────────────────────────────

function parseRouteFiles(): RustRoute[] {
	const routes: RustRoute[] = [];
	const files = fs.readdirSync(ROUTES_DIR).filter((f) => f.endsWith(".rs"));

	for (const file of files) {
		const content = fs.readFileSync(path.join(ROUTES_DIR, file), "utf-8");
		const fileRoutes = extractRoutes(content, file);
		routes.push(...fileRoutes);
	}

	return routes;
}

function extractRoutes(content: string, sourceFile: string): RustRoute[] {
	const routes: RustRoute[] = [];

	// Match .route("path", axum::routing::method(handler))
	// Also handles chained methods: .route("path", axum::routing::get(h1).post(h2).put(h3))
	const routeRegex =
		/\.route\(\s*"([^"]+)"\s*,\s*axum::routing::(get|post|put|delete|patch)\(([^)]+)\)((?:\s*\.\s*(?:get|post|put|delete|patch)\([^)]+\))*)\s*\)/g;

	let match;
	while ((match = routeRegex.exec(content)) !== null) {
		const routePath = match[1];
		const method = match[2].toUpperCase();
		const handler = match[3].trim();

		routes.push({ method, path: routePath, handler, sourceFile });

		// Parse chained methods: .post(handler2).put(handler3)
		const chainedMethods = match[4];
		if (chainedMethods) {
			const chainRegex =
				/\.\s*(get|post|put|delete|patch)\(\s*([^)]+)\s*\)/g;
			let chainMatch;
			while ((chainMatch = chainRegex.exec(chainedMethods)) !== null) {
				routes.push({
					method: chainMatch[1].toUpperCase(),
					path: routePath,
					handler: chainMatch[2].trim(),
					sourceFile,
				});
			}
		}
	}

	return routes;
}

// ── Catalog Management ──────────────────────────────────────────────────────

function loadCatalog(): Catalog {
	if (!fs.existsSync(CATALOG_PATH)) {
		console.error(
			`Catalog not found: ${CATALOG_PATH}\nRun with --init to create from existing nebo.ts`
		);
		process.exit(1);
	}
	return JSON.parse(fs.readFileSync(CATALOG_PATH, "utf-8"));
}

// ── Code Generator ──────────────────────────────────────────────────────────

function routeKey(method: string, routePath: string): string {
	return `${method} ${routePath}`;
}

function generateNeboTs(routes: RustRoute[], catalog: Catalog): string {
	const lines: string[] = [];

	// Header
	lines.push("// Code generated by scripts/genapi.ts. DO NOT EDIT.");
	lines.push("// To regenerate: pnpm run gen:api");
	lines.push("");
	lines.push('import webapi from "./gocliRequest"');
	lines.push('import * as components from "./neboComponents"');
	lines.push('export * from "./neboComponents"');
	lines.push("");

	// Group routes by catalog entry function name to avoid duplicates
	// (same handler can appear in multiple route groups but we need one TS function)
	const generated = new Set<string>();

	// Sort routes by path for stable output
	const sorted = [...routes].sort((a, b) => {
		const pa = a.path.replace(/\{[^}]+\}/g, "~");
		const pb = b.path.replace(/\{[^}]+\}/g, "~");
		if (pa !== pb) return pa.localeCompare(pb);
		const methodOrder = { GET: 0, POST: 1, PUT: 2, DELETE: 3, PATCH: 4 };
		return (
			(methodOrder[a.method as keyof typeof methodOrder] ?? 5) -
			(methodOrder[b.method as keyof typeof methodOrder] ?? 5)
		);
	});

	for (const route of sorted) {
		const key = routeKey(route.method, route.path);
		const entry = catalog[key];

		if (!entry) continue; // Unmapped — will be reported separately
		if (entry.skip) continue;
		if (generated.has(entry.fn)) continue;
		generated.add(entry.fn);

		lines.push(generateFunction(route, entry));
		lines.push("");
	}

	// Append custom functions from catalog that have customBody and no route match
	const customEntries = Object.entries(catalog).filter(
		([key, entry]) =>
			entry.customBody && !routes.some((r) => routeKey(r.method, r.path) === key) && !generated.has(entry.fn)
	);
	for (const [, entry] of customEntries) {
		if (generated.has(entry.fn)) continue;
		generated.add(entry.fn);
		lines.push(entry.customBody!);
		lines.push("");
	}

	return lines.join("\n");
}

function generateFunction(route: RustRoute, entry: CatalogEntry): string {
	const lines: string[] = [];
	const method = route.method.toLowerCase();
	const apiPath = `/api/v1${route.path}`;

	// If custom body is provided, use it directly
	if (entry.customBody) {
		return entry.customBody;
	}

	// Build description
	const desc = entry.desc || deriveDescription(entry.fn);
	lines.push("/**");
	lines.push(` * @description "${desc}"`);
	lines.push(" */");

	// Build function signature
	const params: string[] = [];
	const pathParams = entry.pathParams || extractPathParams(route.path);

	// Request body param comes first for POST/PUT (matches existing convention)
	if (entry.requestType && (method === "post" || method === "put" || method === "patch")) {
		params.push(`req: components.${entry.requestType}`);
	}

	// Query params
	if (entry.queryType) {
		params.push(`params: components.${entry.queryType}`);
	}

	// Path params
	for (const p of pathParams) {
		const tsName = p.tsName || camelCase(p.name);
		const tsType = p.type || "string";
		params.push(`${tsName}: ${tsType}`);
	}

	const responseType = entry.responseType
		? `components.${entry.responseType}`
		: "unknown";

	lines.push(
		`export function ${entry.fn}(${params.join(", ")}) {`
	);

	// Build URL template
	let urlTemplate = apiPath;
	for (const p of pathParams) {
		const tsName = p.tsName || camelCase(p.name);
		urlTemplate = urlTemplate.replace(`{${p.name}}`, `\${${tsName}}`);
		// Handle wildcard: {*path} → ${path}
		urlTemplate = urlTemplate.replace(`{*${p.name}}`, `\${${tsName}}`);
	}

	// Build webapi call
	const hasQuery = !!entry.queryType;
	const hasBody = !!entry.requestType && (method === "post" || method === "put" || method === "patch");

	if (method === "get") {
		if (hasQuery) {
			lines.push(
				`\treturn webapi.get<${responseType}>(\`${urlTemplate}\`, params)`
			);
		} else {
			lines.push(
				`\treturn webapi.get<${responseType}>(\`${urlTemplate}\`)`
			);
		}
	} else if (method === "delete") {
		lines.push(
			`\treturn webapi.delete<${responseType}>(\`${urlTemplate}\`)`
		);
	} else if (method === "post") {
		if (hasBody) {
			lines.push(
				`\treturn webapi.post<${responseType}>(\`${urlTemplate}\`, req)`
			);
		} else {
			lines.push(
				`\treturn webapi.post<${responseType}>(\`${urlTemplate}\`)`
			);
		}
	} else if (method === "put") {
		if (hasBody) {
			lines.push(
				`\treturn webapi.put<${responseType}>(\`${urlTemplate}\`, req)`
			);
		} else {
			lines.push(
				`\treturn webapi.put<${responseType}>(\`${urlTemplate}\`)`
			);
		}
	} else if (method === "patch") {
		if (hasBody) {
			lines.push(
				`\treturn webapi.patch<${responseType}>(\`${urlTemplate}\`, req)`
			);
		} else {
			lines.push(
				`\treturn webapi.patch<${responseType}>(\`${urlTemplate}\`)`
			);
		}
	}

	lines.push("}");
	return lines.join("\n");
}

function extractPathParams(
	routePath: string
): Array<{ name: string; type: string }> {
	const params: Array<{ name: string; type: string }> = [];
	const regex = /\{(\*?)([a-zA-Z_][a-zA-Z0-9_]*)\}/g;
	let match;
	while ((match = regex.exec(routePath)) !== null) {
		params.push({ name: match[2], type: "string" });
	}
	return params;
}

function camelCase(s: string): string {
	return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function deriveDescription(fnName: string): string {
	// Split camelCase into words
	return fnName
		.replace(/([A-Z])/g, " $1")
		.trim()
		.toLowerCase()
		.replace(/^./, (c) => c.toUpperCase());
}

// ── Report ──────────────────────────────────────────────────────────────────

function reportUnmapped(routes: RustRoute[], catalog: Catalog): void {
	const unmapped: RustRoute[] = [];
	for (const route of routes) {
		const key = routeKey(route.method, route.path);
		if (!catalog[key]) {
			unmapped.push(route);
		}
	}

	if (unmapped.length > 0) {
		console.log("\n⚠ Unmapped routes (add to api-catalog.json):\n");
		for (const route of unmapped) {
			const suggestedFn = suggestFunctionName(route);
			console.log(`  "${route.method} ${route.path}": {`);
			console.log(`    "fn": "${suggestedFn}",`);
			console.log(`    "desc": "${deriveDescription(suggestedFn)}",`);
			const params = extractPathParams(route.path);
			if (params.length) {
				console.log(
					`    "pathParams": ${JSON.stringify(params.map((p) => ({ name: p.name })))},`
				);
			}
			console.log(`    "responseType": "MessageResponse"`);
			console.log(`  },`);
		}
	}

	// Check for catalog entries with no matching route
	const orphaned: string[] = [];
	for (const key of Object.keys(catalog)) {
		const entry = catalog[key];
		if (entry.skip || entry.customBody) continue;
		if (!routes.some((r) => routeKey(r.method, r.path) === key)) {
			orphaned.push(key);
		}
	}

	if (orphaned.length > 0) {
		console.log("\n⚠ Catalog entries with no matching Rust route:\n");
		for (const key of orphaned) {
			console.log(`  ${key} → ${catalog[key].fn}`);
		}
	}
}

function suggestFunctionName(route: RustRoute): string {
	// Extract handler function name: handlers::agent::list_sessions → listSessions
	const parts = route.handler.split("::");
	const handlerFn = parts[parts.length - 1];
	return camelCase(handlerFn);
}

// ── Main ────────────────────────────────────────────────────────────────────

function main(): void {
	const args = process.argv.slice(2);

	// Parse routes
	console.log(`Scanning routes in ${ROUTES_DIR}...`);
	const routes = parseRouteFiles();
	console.log(`Found ${routes.length} routes.`);

	if (args.includes("--scan")) {
		// Just report routes, don't generate
		for (const r of routes) {
			console.log(`  ${r.method.padEnd(7)} ${r.path.padEnd(50)} → ${r.handler}`);
		}
		return;
	}

	if (args.includes("--init")) {
		// Generate a starter catalog from routes
		const catalog: Catalog = {};
		for (const route of routes) {
			const key = routeKey(route.method, route.path);
			if (route.handler.includes("ws_handler")) {
				catalog[key] = { fn: "", skip: true };
				continue;
			}
			const fn = suggestFunctionName(route);
			const params = extractPathParams(route.path);
			catalog[key] = {
				fn,
				desc: deriveDescription(fn),
				...(params.length > 0 && {
					pathParams: params.map((p) => ({ name: p.name })),
				}),
				responseType: "MessageResponse",
			};
		}
		fs.writeFileSync(CATALOG_PATH, JSON.stringify(catalog, null, "\t"));
		console.log(`Generated starter catalog: ${CATALOG_PATH}`);
		console.log("Edit the catalog to set correct types, then run again to generate.");
		return;
	}

	// Load catalog and generate
	const catalog = loadCatalog();

	// Report unmapped routes
	reportUnmapped(routes, catalog);

	// Generate
	const output = generateNeboTs(routes, catalog);
	fs.writeFileSync(OUTPUT_PATH, output);

	const routeCount = routes.filter((r) => {
		const key = routeKey(r.method, r.path);
		const entry = catalog[key];
		return entry && !entry.skip;
	}).length;
	console.log(`\nGenerated ${OUTPUT_PATH}`);
	console.log(`  ${routeCount} API functions from ${routes.length} routes`);
}

main();
